from lib import L, S

N = 1
TITLE = "El encargo"
SCENES = [
    S("intro", "Capítulo 1",
      "Pantalla oscura con el logo genérico de un kata (cinturón de práctica). Aparecen tres palabras, una por línea: pliego, arquitectura, IA. En la línea 5 entra el nombre del equipo, Five Nines, con la insignia de primer puesto redibujada en trazo simple (sin el PNG de GitHub). Título del capítulo al final.",
      [
          L("En octubre de 2025, varios equipos de ingenieros compitieron en una Architecture Kata de O'Reilly.",
            say="En octubre de dos mil veinticinco, varios equipos de ingenieros compitieron en una Architecture Kata de O'Reilly."),
          L("Una kata es un ejercicio de práctica: una empresa ficticia entrega un pliego, el documento con lo que necesita."),
          L("Y cada equipo diseña la arquitectura: qué piezas tiene el sistema, cómo se hablan, y por qué.", p=0.6),
          L("Esta vez el pliego traía una condición central: decidir dónde usar inteligencia artificial, y dónde no.", p=1),
          L("Este curso sigue, paso a paso, al equipo que ganó: Five Nines."),
          L("Capítulo 1: el encargo.", say="Capítulo uno: el encargo."),
      ]),
    S("negocio", "El negocio",
      "Mapa estilizado de una ciudad europea genérica. Una estación de tren y una casa unidas por una línea punteada: la última milla. Después la pantalla se parte en dos columnas: izquierda scooters y bicicletas (30 min, hasta 12 h), derecha autos y camionetas (7 días, tiempo fijo, enchufe). Abajo, tres íconos comunes a ambas: reloj por minuto, teléfono NFC, cámara de foto. Cada dato aparece con la frase que lo nombra.",
      [
          L("La empresa se llama MobilityCorp. Alquila vehículos eléctricos por minuto, en ciudades de la Unión Europea."),
          L("Su negocio es la última milla: el tramo final de un viaje, por ejemplo, de la estación de tren a tu casa."),
          L("Tiene dos flotas muy distintas.", p=0.6),
          L("La primera: scooters y bicicletas eléctricas. Se reservan hasta 30 minutos antes, o se toman en la calle, y se usan hasta 12 horas.",
            say="La primera: scooters y bicicletas eléctricas. Se reservan hasta treinta minutos antes, o se toman en la calle, y se usan hasta doce horas."),
          L("La segunda: autos y camionetas eléctricas. Se reservan hasta con 7 días, por un tiempo fijo, y al devolverlos hay que enchufarlos al cargador.",
            say="La segunda: autos y camionetas eléctricas. Se reservan hasta con siete días, por un tiempo fijo, y al devolverlos hay que enchufarlos al cargador."),
          L("En las dos pagas por minuto, abres el vehículo acercando el teléfono, y al terminar subes una foto como prueba de devolución.", p=1),
          L("Dos flotas, dos formas de usar el servicio, y problemas distintos para cada una."),
      ]),
    S("numeros", "Los números",
      "Cuatro barras horizontales que crecen una por una: 200 autos, 200 camionetas, 5.000 bicicletas, 5.000 scooters (escala real, las dos primeras casi invisibles). Luego se apilan en una sola barra de 10.400 con el 96 % de micromovilidad resaltado. Etiqueta pequeña y fija: «cálculo de este curso, no del equipo». Fuente al pie: captions de la sesión inaugural, minuto 26.",
      [
          L("El pliego no traía números. Alguien los pidió en la sesión de preguntas, y el cliente los inventó en vivo."),
          L("Por cada país, más o menos: 200 autos, 200 camionetas, 5.000 bicicletas y 5.000 scooters.",
            say="Por cada país, más o menos: doscientos autos, doscientas camionetas, cinco mil bicicletas y cinco mil scooters."),
          L("Haz la suma: 10.400 vehículos por país.", say="Haz la suma: diez mil cuatrocientos vehículos por país.", p=0.6),
          L("Y mira la proporción: más de 9 de cada 10 son scooters y bicicletas.",
            say="Y mira la proporción: más de nueve de cada diez son scooters y bicicletas.", p=1),
          L("Esa cuenta es nuestra, no del equipo. Pero conviene hacerla antes de diseñar nada."),
          L("Ahí está el volumen. Y, como vas a ver, ahí están también los dolores de cabeza."),
      ]),
    S("desafios", "Los problemas",
      "Tres tarjetas numeradas que entran una por vez. 1: un monumento con una montaña de bicicletas y el resto del mapa vacío. 2: un ícono de batería que se cambia a mano y una camioneta de operarios con un signo de pregunta sobre el mapa. 3: un calendario con usos salteados que se vuelve una línea diaria. Al final, una cuarta franja horizontal: «usar mejor la flota antes de comprar más». Síntesis en una línea grande.",
      [
          L("El cliente nombró tres problemas."),
          L("Primero, el más grande: los vehículos no están donde la gente los necesita."),
          L("Todos van en bicicleta a un monumento famoso y las dejan ahí. Y en el resto de la ciudad no queda ninguna.", p=0.8),
          L("Segundo, las baterías. Scooters y bicicletas usan baterías que se cambian a mano, y un equipo de operarios recorre la ciudad haciéndolo. ¿A dónde mandarlos primero?", p=0.8),
          L("Tercero: casi todos usan el servicio de vez en cuando. La empresa quiere que se vuelva un hábito, parte del viaje diario al trabajo."),
          L("Y el cliente los conectó: si el vehículo está ahí, y cargado, la gente empieza a confiar y lo usa todos los días.", p=1),
          L("Una preferencia más: antes de comprar vehículos, quiere usar mejor los que ya tiene.", p=1),
          L("Los tres problemas apuntan a lo mismo: el vehículo correcto, cargado, en el lugar correcto."),
      ]),
    S("entregables", "Las reglas",
      "Un repositorio de GitHub dibujado como carpeta con tres subcarpetas: README, diagramas, ADRs. Al nombrar el ADR, se abre una tarjeta con tres renglones: decisión, alternativas, por qué. Luego una línea de tiempo: 15 oct (inicio), 23 oct (foto del repositorio, ícono de cámara), 9 nov (video de semifinal), 13 nov (final). La línea de tiempo queda abajo, pequeña, hasta el final de la escena.",
      [
          L("Las reglas de entrega eran simples: un repositorio público en GitHub."),
          L("Adentro, un README con la historia de la solución, diagramas sencillos de cajas y flechas, y ADRs."),
          L("Un ADR es un registro de decisión de arquitectura: un documento corto que dice qué se decidió, qué alternativas hubo, y por qué.", p=1),
          L("El 23 de octubre, los jueces tomaron una foto del repositorio. Los semifinalistas grabaron después un video de 5 minutos, y la final fue el 13 de noviembre.",
            say="El veintitrés de octubre, los jueces tomaron una foto del repositorio. Los semifinalistas grabaron después un video de cinco minutos, y la final fue el trece de noviembre."),
          L("Ese calendario importa. Git guarda cada cambio con su fecha, y así podemos reconstruir cómo pensó el equipo, día por día.", p=1),
      ]),
    S("criterios", "Lo que mira el jurado",
      "Cuatro casilleros que se llenan uno por uno, con un ícono cada uno: chispa (IA generativa útil), engranaje encajando (encaje y porqué), nube con rayo (incertidumbre), lupa con tilde (verificación). Al definir «determinista», una función f(x) que siempre devuelve lo mismo contra un dado que cae distinto. Los cuatro casilleros quedan juntos 6 segundos al final.",
      [
          L("Este kata tenía un tema: arquitecturas con inteligencia artificial."),
          L("Sobre todo, IA generativa: modelos que generan texto, como los chatbots, y entienden lenguaje libre."),
          L("El jurado anunció qué iba a mirar. Primero, usos interesantes de la IA generativa, que resuelvan problemas reales del negocio."),
          L("Segundo, que la solución encaje en el negocio, y que se entienda el porqué de cada decisión."),
          L("Tercero, cómo se defiende el sistema de la incertidumbre: los modelos cambian cada mes, los precios suben y hay proveedores que cierran."),
          L("Y cuarto: cómo sabes si la IA funciona. Porque no es determinista.", p=0.6),
          L("Determinista quiere decir que, con la misma entrada, siempre da la misma salida, como una función normal de tu código. La IA generativa no lo garantiza.", p=1),
          L("Esas cuatro preguntas guían todo el curso."),
      ]),
    S("piensalo", "Piénsalo tú",
      "Un teléfono con una burbuja de chat genérica y la etiqueta «de moda». Debajo, los cuatro casilleros del jurado en miniatura. Durante la pausa, anillo de cuenta regresiva de 3 s. Luego aparecen las dos preguntas como tarjetas: «¿qué problema resuelve?» y «¿cómo sabrás si responde bien?». Quedan en pantalla hasta el cambio de escena.",
      [
          L("Ahora tú. Un equipo propone un chatbot en la app, porque la IA generativa está de moda."),
          L("Con los criterios del jurado, ¿qué dos preguntas le harías?", p=3),
          L("Primera: ¿qué problema del negocio resuelve? ¿Pone vehículos en el lugar correcto, o crea el hábito?"),
          L("Segunda: ¿cómo vas a saber si responde bien, cuando ya esté en manos de los clientes?"),
          L("Guarda las dos. El equipo ganador también puso un chatbot, y vamos a ver cómo las respondió."),
      ]),
    S("outro", "Para llevarte",
      "Tres tarjetas de repaso, una por idea: dos flotas con la barra del 96 %, los tres problemas en miniatura, los cuatro casilleros del jurado. Al final, una hoja de borrador con una frase tachada al margen (anticipo del capítulo 2).",
      [
          L("Repasemos. MobilityCorp alquila dos flotas muy distintas, y más de 9 de cada 10 vehículos son scooters y bicicletas.",
            say="Repasemos. MobilityCorp alquila dos flotas muy distintas, y más de nueve de cada diez vehículos son scooters y bicicletas.", p=0.6),
          L("Sus problemas: vehículos en el lugar equivocado, baterías que cambiar, y clientes que no vuelven.", p=0.6),
          L("Y el jurado pide IA que resuelva problemas reales, con su porqué, sus riesgos y una forma de verificarla.", p=1),
          L("En el próximo capítulo, el equipo escribe sus primeros objetivos, y alguien anota al margen de uno: esto no es un objetivo."),
          L("Capítulo 2: antes de la IA, el negocio.", say="Capítulo dos: antes de la IA, el negocio."),
      ]),
]
