from lib import L, S

N = 2
TITLE = "Antes de la IA, el negocio"
SCENES = [
    S("intro", "Capítulo 2",
      "Repaso visual del capítulo 1: los tres problemas en miniatura. Una línea de tiempo con los días 15, 16 y 17 de octubre; en el 16 se encienden dos íconos: una nube (con la nota «capítulo 3») y una hoja de objetivos (resaltada). Título.",
      [
          L("¿Recuerdas los tres problemas de MobilityCorp? Vehículos fuera de lugar, baterías por cambiar y clientes ocasionales."),
          L("En sus dos primeros días, el equipo hizo dos cosas. Eligió la nube, que veremos en el capítulo 3, y escribió qué quería lograr el negocio.",
            say="En sus dos primeros días, el equipo hizo dos cosas. Eligió la nube, que veremos en el capítulo tres, y escribió qué quería lograr el negocio."),
          L("Empecemos por lo segundo.", p=0.8),
          L("Capítulo 2: antes de la IA, el negocio.", say="Capítulo dos: antes de la IA, el negocio."),
      ]),
    S("nota", "Una nota al margen",
      "Redibujar el primer borrador real (commit b7d92fb, archivo «business requirements.md»): una hoja con seis renglones que aparecen uno por uno. El sexto, «Leverage AI for Optimization», queda resaltado; a su lado aparece en letra manuscrita la nota original, traducida: «no es un objetivo del negocio, es una solución». Al final, una fecha (19 oct) y el renglón se tacha.",
      [
          L("El 16 de octubre, el primer borrador listaba seis objetivos del negocio.",
            say="El dieciséis de octubre, el primer borrador listaba seis objetivos del negocio."),
          L("Aumentar ingresos. Crecer en Europa. Operar con más eficiencia. Mejorar la experiencia. Cumplir las normas."),
          L("Y uno más: usar IA para optimizar.", p=0.8),
          L("Al lado, una integrante del equipo dejó una nota: eso no es un objetivo del negocio, es una solución.", p=1.2),
          L("¿Por qué importa? Porque un objetivo dice qué gana la empresa. La IA es una forma de lograrlo, entre otras."),
          L("Si pones la herramienta como meta, cualquier uso de IA parece un éxito, aunque no mueva ningún número.", p=1),
          L("Tres días después, ese objetivo ya no estaba en la lista."),
      ]),
    S("cadena", "Impulsor, meta, solución",
      "Redibujar la tabla «Drivers → Goals → Solutions» de requirements/1_0_Business goals & drivers.md como tres columnas unidas por flechas. Cada columna se ilumina al nombrarla. Luego una sola fila de ejemplo recorre la cadena: Eficiencia operativa → bajar costos de mantenimiento 23 % a fines de 2026 → IA para mantenimiento y ubicación de la flota. Al final, una flecha recorre la fila de derecha a izquierda (el filtro).",
      [
          L("El equipo ordenó su razonamiento en una cadena de tres eslabones."),
          L("Primero, los impulsores del negocio: las fuerzas que deciden si le va bien o mal. Por ejemplo, la competencia: si no hay un scooter cerca, el cliente se va a otro servicio."),
          L("Después, las metas: objetivos que se pueden medir y tienen fecha."),
          L("Y recién al final, las soluciones. Ahí aparece la IA.", p=1),
          L("Un ejemplo de su tabla. La eficiencia operativa es un impulsor. La meta: bajar los costos de mantenimiento un 23 % para fines de 2026. Y la solución: IA para optimizar el mantenimiento y la ubicación de la flota.",
            say="Un ejemplo de su tabla. La eficiencia operativa es un impulsor. La meta: bajar los costos de mantenimiento un veintitrés por ciento para fines de dos mil veintiséis. Y la solución: IA para optimizar el mantenimiento y la ubicación de la flota.", p=1),
          L("Leída de derecha a izquierda, la cadena es un filtro: cada pieza de IA tiene que poder señalar la meta que mueve.", p=1),
      ]),
    S("origen", "De dónde salen los números",
      "Tres cajones etiquetados: «dado por el cliente», «calculado», «supuesto». Las cifras del equipo (23 %, 96 %, 15 %) caen en «supuesto». El 10.400 del capítulo 1 cae en «calculado» y los 5.000 scooters en «dado». Los cajones quedan en pantalla hasta el final de la escena; se reutilizan en el capítulo 8.",
      [
          L("Ojo con ese 23 %. El pliego no traía datos económicos: el cliente dijo en vivo que no los había inventado.",
            say="Ojo con ese veintitrés por ciento. El pliego no traía datos económicos: el cliente dijo en vivo que no los había inventado."),
          L("Así que las metas del equipo, como un 96 % de satisfacción o un 15 % más de mercado, son metas que el equipo eligió. El repositorio no tiene un cálculo detrás.",
            say="Así que las metas del equipo, como un noventa y seis por ciento de satisfacción o un quince por ciento más de mercado, son metas que el equipo eligió. El repositorio no tiene un cálculo detrás.", p=1),
          L("Fijar metas no está mal. Lo importante es saber qué tipo de número tienes delante."),
          L("Un número puede venir dado por el cliente, puede ser calculado, o puede ser supuesto. Cada uno merece una confianza distinta.", p=1),
      ]),
    S("supuestos", "Los supuestos",
      "Redibujar requirements/4_Assumptions and constraints.md como dos listas: «Supuestos» y «Restricciones». Al definir cada palabra, se ilumina su lista. Luego dos columnas enfrentadas, «el pliego» y «el equipo», con una sola fila: 5.000 bicicletas por país contra 500 por ciudad; un signo de desigualdad rojo entre ambas. Debajo, una miniatura de la diapositiva 2 de la presentación final con «500 eBikes» marcado.",
      [
          L("Lo mismo vale para lo que el equipo dio por cierto. Lo anotó en un documento de supuestos y restricciones."),
          L("Un supuesto es algo que das por cierto para poder avanzar, aunque nadie te lo confirmó."),
          L("Una restricción es algo que te imponen, como operar solo en la Unión Europea.", p=0.8),
          L("Escribirlos tiene una ventaja: cualquiera puede compararlos con el pliego. Y al compararlos, aparecen diferencias.", p=0.8),
          L("El cliente habló de 5.000 bicicletas por país. El documento del equipo dice 500 por ciudad. Y esa cifra llegó hasta la presentación final.",
            say="El cliente habló de cinco mil bicicletas por país. El documento del equipo dice quinientas por ciudad. Y esa cifra llegó hasta la presentación final.", p=1),
          L("El repositorio no explica el cambio. Puede ser un error al copiar, o una decisión que nadie escribió."),
      ]),
    S("piensalo", "Piénsalo tú",
      "Mapa con un scooter y su punto de GPS. Etiqueta: «supuesto del equipo: cada 30 minutos». Anillo de cuenta regresiva de 3 s. En la respuesta, el scooter recorre un viaje completo entre dos puntos de GPS (el viaje queda invisible para el sistema) y en la app aparece un scooter fantasma. Al final, dos sellos sobre el documento: «pliego: 30 segundos» y «Apéndice A del propio equipo: 30 segundos».",
      [
          L("Ahora tú. Otro supuesto del equipo: el GPS de cada vehículo informa su posición cada 30 minutos.",
            say="Ahora tú. Otro supuesto del equipo: el GPS de cada vehículo informa su posición cada treinta minutos."),
          L("El cliente había dicho al menos cada 30 segundos. ¿Qué se rompe si te quedas con el supuesto?",
            say="El cliente había dicho al menos cada treinta segundos. ¿Qué se rompe si te quedas con el supuesto?", p=3),
          L("Se rompe todo lo que necesita saber dónde está un vehículo ahora."),
          L("Un viaje corto puede empezar y terminar entre dos reportes. La app mostraría scooters que ya no están ahí."),
          L("El propio repositorio se contradice: otro documento, de los últimos días, dice cada 30 segundos. En este curso seguimos al pliego.",
            say="El propio repositorio se contradice: otro documento, de los últimos días, dice cada treinta segundos. En este curso seguimos al pliego.", p=1),
          L("La regla: escribe tus supuestos, y compáralos con el pliego antes de construir encima.", p=1),
      ]),
    S("alcance", "Qué se diseña",
      "Una base gris rotulada «lo básico del alquiler: reservar, abrir, pagar, devolver». Encima se apilan cuatro bloques de color, uno por frase: diálogo con el usuario, precios dinámicos, pronóstico de demanda, optimización del mantenimiento (en el orden del README del equipo). Al final, el bloque del pronóstico late y una etiqueta lo une al problema 1 del capítulo 1.",
      [
          L("Con las metas claras, el equipo definió qué iba a diseñar."),
          L("Primero, mantener funcionando lo básico del alquiler: reservar, abrir, pagar y devolver."),
          L("Y encima, cuatro áreas con IA.", p=0.6),
          L("El diálogo con el usuario: un asistente dentro de la app."),
          L("Los precios dinámicos: que el precio cambie según la demanda, el clima o la competencia."),
          L("El pronóstico de demanda: saber dónde se van a necesitar vehículos."),
          L("Y la optimización del mantenimiento: baterías, traslados y tareas de los operarios.", p=1),
          L("Fíjate: el problema número uno del cliente, los vehículos fuera de lugar, está en la lista. Pero no está primero. Ese orden va a tener consecuencias."),
      ]),
    S("outro", "Para llevarte",
      "Tres tarjetas de repaso: la nota al margen, la cadena de tres eslabones, el pliego contra el supuesto. Al final, un enjambre de puntos (vehículos) que envían señales hacia un centro vacío con un signo de pregunta.",
      [
          L("Repasemos. La IA no es un objetivo: es una de las formas de llegar a uno.", p=0.6),
          L("La cadena impulsor, meta, solución obliga a cada pieza de IA a señalar qué número mueve.", p=0.6),
          L("Y los supuestos se escriben para poder compararlos con el pliego. Ahí aparecieron dos diferencias: las bicicletas y el GPS.", p=1),
          L("En el próximo capítulo, miles de vehículos le hablan al sistema cada pocos segundos. ¿Quién sabe la verdad sobre cada uno?"),
          L("Capítulo 3: una sola fuente de verdad.", say="Capítulo tres: una sola fuente de verdad."),
      ]),
]
