from lib import L, S

N = 3
TITLE = "Una sola fuente de verdad"
SCENES = [
    S("intro", "Capítulo 3",
      "La barra de 10.400 vehículos del capítulo 1 se deshace en puntos sobre un mapa; cada punto muestra un mini indicador de batería y posición. Título.",
      [
          L("¿Recuerdas la cuenta del capítulo 1? Unos 10.400 vehículos por país.",
            say="¿Recuerdas la cuenta del capítulo uno? Unos diez mil cuatrocientos vehículos por país."),
          L("Cada uno sabe dónde está y cuánta batería le queda. El sistema necesita saberlo también, todo el tiempo.", p=1),
          L("Capítulo 3: una sola fuente de verdad.", say="Capítulo tres: una sola fuente de verdad."),
      ]),
    S("volumen", "Haz la cuenta",
      "Un vehículo emite un sobre pequeño (posición, batería) cada 30 s. La operación se escribe a la vista: 10.400 ÷ 30 ≈ 350 mensajes por segundo. Un contador que gira hasta 350 y queda fijo. Etiqueta permanente: «peor caso, todos en uso; cuenta de este curso». Debajo, la cita del ADR-0002: «miles a decenas de miles de dispositivos».",
      [
          L("Cada vehículo envía telemetría: datos sobre su propio estado, como posición y batería, que manda solo, sin que nadie los pida."),
          L("El cliente pidió al menos un reporte cada 30 segundos mientras el vehículo está en uso.",
            say="El cliente pidió al menos un reporte cada treinta segundos mientras el vehículo está en uso."),
          L("Hagamos el peor caso: los 10.400 en movimiento a la vez. Divides 10.400 entre 30.",
            say="Hagamos el peor caso: los diez mil cuatrocientos en movimiento a la vez. Divides diez mil cuatrocientos entre treinta.", p=0.8),
          L("Son unos 350 mensajes por segundo, en un solo país, sin parar.",
            say="Son unos trescientos cincuenta mensajes por segundo, en un solo país, sin parar.", p=1),
          L("Esa cuenta es nuestra: el equipo no la escribió. Su ADR habla de miles a decenas de miles de dispositivos."),
          L("Pero el orden de magnitud es claro: muchos mensajes pequeños, de aparatos con poca batería y una señal móvil que va y viene.", p=1),
      ]),
    S("mqtt", "Cómo hablan los vehículos",
      "Redibujar el diagrama original hld/core-func/Vehicle Connectivity.png de izquierda a derecha: Dispositivos → Gateway y balanceador → Event Backbone (MQTT, Pub/Sub). Al hablar de HTTP, una flecha alternativa gruesa aparece tachada. Al explicar Pub/Sub, metáfora visual de un tablero de anuncios: un sobre se clava una vez y tres servicios lo leen. Un cuarto servicio nuevo llega y se suscribe sin tocar al vehículo.",
      [
          L("Para ese tráfico, el equipo eligió dos piezas. La primera se llama MQTT."),
          L("MQTT es un protocolo de mensajes pensado para aparatos pequeños: mensajes livianos, que gastan poca batería y toleran cortes de señal."),
          L("La alternativa obvia era que cada vehículo hiciera peticiones HTTP, como una app cualquiera. El equipo la descartó: es más pesada para estos aparatos y no garantiza la entrega.", p=1),
          L("La segunda pieza es Pub/Sub, un servicio de mensajería de Google.", say="La segunda pieza es Pab Sab, un servicio de mensajería de Google."),
          L("Funciona como un tablero de anuncios: quien produce un dato lo publica una vez, y cada servicio interesado se suscribe y lo recibe.", p=1),
          L("Así el vehículo no necesita saber quién usa sus datos. Y si mañana aparece un servicio nuevo, solo se suscribe.", p=1),
      ]),
    S("boceto", "El primer boceto",
      "Redibujar el primer diagrama C4 (borrado del repositorio, commit c9524d4, archivo proposal_c4_container_scooter_rental_system_overview.mmd): Fleet Service, Location Service y Booking Service, con la flecha «avisa que un vehículo se reservó» de reservas a ubicación. En la línea 4 se superpone el diagrama del 19 de octubre (hld/core-func/Core Containers.drawio.png): el cuadro de Location Service se desvanece y su texto se desliza dentro de Fleet Service.",
      [
          L("Ahora, ¿quién guarda el estado de cada vehículo? El primer boceto del equipo, del 16 de octubre, tenía dos servicios para eso.",
            say="Ahora, ¿quién guarda el estado de cada vehículo? El primer boceto del equipo, del dieciséis de octubre, tenía dos servicios para eso."),
          L("Un servicio de flota, que recibía los mensajes de los vehículos. Y un servicio de ubicación, que guardaba dónde estaba cada uno."),
          L("El servicio de reservas, además, le avisaba al de ubicación cuando alguien reservaba un vehículo.", p=0.8),
          L("Tres días después, en el diagrama nuevo, el servicio de ubicación ya no estaba.", p=1),
          L("Su trabajo pasó entero al servicio de flota."),
      ]),
    S("verdad", "Fuente única de verdad",
      "El Fleet Service al centro, grande, con un sello «ADR-0007». Entra la telemetría por la izquierda; adentro se ven tres pasos: guarda el último estado, evalúa una regla (batería bajo el umbral), publica un evento «no disponible». A la derecha, viajes, mantenimiento y la app escuchan el mismo evento. Luego, versión alternativa en gris: tres servicios con tres copias distintas de la batería, con un signo de alerta.",
      [
          L("El 20 de octubre, el equipo escribió el porqué en su ADR número 7: el servicio de flota es la fuente única de verdad del estado de cada vehículo.",
            say="El veinte de octubre, el equipo escribió el porqué en su ADR número siete: el servicio de flota es la fuente única de verdad del estado de cada vehículo."),
          L("Fuente única de verdad quiere decir que hay un solo lugar donde ese dato es oficial. Los demás le preguntan a él, o escuchan lo que publica.", p=1),
          L("El servicio de flota recibe la telemetría, guarda el último estado y aplica reglas. Por ejemplo: si la batería baja del umbral, el vehículo deja de estar disponible para reservar.", p=1),
          L("La alternativa era que cada servicio leyera la telemetría por su cuenta y armara su propia versión."),
          L("El equipo la descartó por el riesgo de estados que no coinciden y de lógica repetida en varios lugares.", p=1),
      ]),
    S("piensalo", "Piénsalo tú",
      "Dos servicios lado a lado, viajes y mantenimiento, cada uno con su propio medidor de batería del mismo scooter: uno marca 40 %, el otro 8 %. Anillo de 3 s. En la respuesta, un operario camina hacia el scooter equivocado y, en la app, un cliente reserva uno que no puede salir. Al final, los dos medidores se funden en uno solo, dentro del Fleet Service.",
      [
          L("Ahora tú. Imagina esa alternativa: el servicio de viajes y el de mantenimiento guardan cada uno su copia de la batería de un scooter."),
          L("Uno ya procesó el último mensaje; el otro, todavía no. ¿Qué puede salir mal?", p=3),
          L("Mantenimiento manda a un operario a cambiar una batería que, para el otro servicio, está bien. O la app ofrece un scooter que ya no puede salir."),
          L("Con una sola fuente, las dos decisiones miran el mismo dato.", p=1),
      ]),
    S("precio", "El precio",
      "Una balanza: a la izquierda «consistencia», a la derecha «riesgo concentrado». Al definir trade-off, la balanza se inclina hacia la consistencia y en el otro platillo aparecen tres pesas: copias en marcha, escalado automático, observación (las mitigaciones del ADR-0007).",
      [
          L("Nada es gratis. El equipo anotó el costo: el servicio de flota se vuelve crítico. Si se cae, casi todo se detiene."),
          L("Su respuesta: varias copias en marcha, que se agregan solas cuando crece la carga, y buena observación de lo que pasa."),
          L("Esto es un trade-off: un intercambio en el que, para ganar algo, aceptas perder otra cosa.", p=0.8),
          L("Aquí ganas consistencia, y a cambio concentras el riesgo en una pieza que hay que cuidar mucho.", p=1),
      ]),
    S("nube", "La nube, el segundo día",
      "Línea de tiempo con el 16 de octubre marcado: aparece la tarjeta del ADR-0001 «GCP como proveedor principal». Tres íconos encajan en la nube: mapa (Google Maps), cerebro (Vertex AI), chispa (Gemini). Al final, un candado pequeño con la etiqueta «capítulo 7».",
      [
          L("Todo esto corre en la nube: servidores que alquilas a otra empresa, en vez de tener los tuyos."),
          L("El equipo eligió Google Cloud el segundo día. El 16 de octubre, el ADR número 1 ya estaba escrito.",
            say="El equipo eligió Google Cloud el segundo día. El dieciséis de octubre, el ADR número uno ya estaba escrito."),
          L("La razón principal fueron los mapas. Google Cloud se integra directo con Google Maps, y casi todo en este negocio pasa sobre un mapa."),
          L("La segunda razón: sus herramientas de IA, como Vertex AI y los modelos Gemini, vienen integradas.", p=1),
          L("Esa comodidad tiene un precio, y lo vamos a ver en el capítulo 7: depender de un solo proveedor.",
            say="Esa comodidad tiene un precio, y lo vamos a ver en el capítulo siete: depender de un solo proveedor."),
      ]),
    S("outro", "Para llevarte",
      "Tres tarjetas de repaso: el contador en 350 por segundo, el tablero de anuncios, el Fleet Service al centro. Al final, la tabla de requisitos del equipo con una columna nueva vacía que se ilumina (anticipo del capítulo 4).",
      [
          L("Repasemos. Haz la cuenta del tráfico: cientos de mensajes por segundo, en un solo país.", p=0.6),
          L("MQTT y Pub/Sub: mensajes livianos, publicados una vez, para quien los necesite.",
            say="MQTT y Pab Sab: mensajes livianos, publicados una vez, para quien los necesite.", p=0.6),
          L("Y un solo servicio que sabe la verdad sobre cada vehículo, con el riesgo concentrado y cubierto.", p=1),
          L("Con los datos en orden, llega la pregunta del kata: ¿dónde va la IA? El equipo la respondió con una columna en una tabla."),
          L("Capítulo 4: ¿IA generativa, aprendizaje automático o código?",
            say="Capítulo cuatro: ¿IA generativa, aprendizaje automático o código?"),
      ]),
]
