from lib import L, S

N = 4
TITLE = "¿IA generativa, aprendizaje automático o código?"
SCENES = [
    S("intro", "Capítulo 4",
      "Los cuatro casilleros del jurado (capítulo 1); se iluminan el primero y una nota: «¿dónde decidiste no usarla?». Luego la tabla de requisitos del equipo, en gris, con una columna vacía a la derecha que se ilumina con la fecha 17 oct. Título.",
      [
          L("¿Recuerdas al jurado? Quería IA generativa útil, y saber dónde decidiste no usarla."),
          L("El 17 de octubre, el equipo agregó una columna a su tabla de requisitos. Esa columna ordenó todo lo demás.",
            say="El diecisiete de octubre, el equipo agregó una columna a su tabla de requisitos. Esa columna ordenó todo lo demás.", p=1),
          L("Capítulo 4: ¿IA generativa, aprendizaje automático o código?",
            say="Capítulo cuatro: ¿IA generativa, aprendizaje automático o código?"),
      ]),
    S("herramientas", "Tres herramientas",
      "Tres tarjetas que entran una por vez y quedan alineadas: «Código» (un if con umbral; etiquetas: siempre igual, barato, se prueba), «Aprendizaje automático» (una curva aprendida de puntos históricos que predice las 8 de la mañana; etiquetas: necesita datos, rápido, devuelve números), «IA generativa / LLM» (una burbuja con texto libre; etiquetas: entiende lenguaje, cobra por uso, más lenta, puede equivocarse con seguridad). Las tres quedan en pantalla al final.",
      [
          L("Antes de la columna, las tres herramientas, una por una."),
          L("La primera es código: reglas que escribes tú. Si la batería baja de cierto umbral, avisa. Hace siempre lo mismo, es barato, y lo puedes probar.", p=1),
          L("La segunda es aprendizaje automático, en inglés machine learning: un modelo que aprende patrones de datos históricos y predice."),
          L("Por ejemplo, cuántas bicicletas se van a pedir mañana a las 8 en una estación. Necesita datos para entrenarse, pero responde rápido, y con números.",
            say="Por ejemplo, cuántas bicicletas se van a pedir mañana a las ocho en una estación. Necesita datos para entrenarse, pero responde rápido, y con números.", p=1),
          L("La tercera es IA generativa. Su motor es un LLM, un modelo de lenguaje grande: aprendió de enormes cantidades de texto, y genera texto nuevo.",
            say="La tercera es IA generativa. Su motor es un ele ele eme, un modelo de lenguaje grande: aprendió de enormes cantidades de texto, y genera texto nuevo."),
          L("Entiende pedidos en lenguaje libre, como «quiero una ruta linda hasta el río». Pero cobra por uso, tarda más, y puede equivocarse con total seguridad.", p=1),
          L("Para cada problema, la pregunta es cuál de las tres alcanza."),
      ]),
    S("columna", "La columna",
      "Redibujar la tabla de requirements/2_FRs.md en su versión del 17 de octubre (commits 0d0036f y 95046f0), con solo tres filas visibles y la columna «Tech Choice» resaltada: Pronóstico de demanda → ML; Consejo de precios → Código; Asistente de la app → Híbrido (GenAI, ML, Código). Al final se ilumina el comentario original de la fila del asistente: «Risk of overspending by using GenAI», con su traducción.",
      [
          L("Eso hizo el equipo. Su tabla listaba cada escenario de IA, con sus datos de entrada y de salida."),
          L("Y la columna nueva decía qué herramienta usar: código, aprendizaje automático, IA generativa, o una mezcla, que llamaron híbrido.", p=0.8),
          L("El pronóstico de demanda: aprendizaje automático. Es predecir números a partir de la historia."),
          L("El consejo de precios al usuario: código. Solo muestra lo que el motor de precios ya calculó."),
          L("El asistente de la app: híbrido. Y al lado, un comentario: riesgo de gastar de más con la IA generativa.", p=1),
          L("Esa nota es el centro del capítulo."),
      ]),
    S("asistente", "El asistente híbrido",
      "Diagrama de flujo basado en el ADR-0012: un teléfono con botones y un campo de texto. Rama 1 (botones) → «función programada», en verde, con la etiqueta «sin costo por mensaje». Rama 2 (texto libre) → «IA generativa entiende» → «clasificador ML decide» → tres salidas: función programada, soporte, respuesta conversada. Un candado sobre «reservar / pagar» que siempre termina en código.",
      [
          L("El asistente vive dentro de la app. Puedes tocar botones, o escribir lo que quieras."),
          L("Casi todo lo que la gente pide es predecible: reservar, ver un precio, buscar estacionamiento cerca."),
          L("Para eso, el equipo usa código: cada botón dispara una función ya programada. Sin IA generativa, y sin costo por mensaje.", p=1),
          L("Cuando escribes texto libre, la IA generativa entiende el pedido. Y un clasificador de aprendizaje automático decide a dónde va: a una función programada, a soporte, o a una respuesta conversada."),
          L("Las acciones con dinero, como reservar o pagar, siempre terminan en código. La IA generativa conversa, pero no ejecuta.", p=1),
          L("Así, lo caro y lo probabilístico quedan solo donde aportan: entender lenguaje libre."),
      ]),
    S("carga", "Dónde no usarla",
      "Un scooter avanzando por un mapa con pendiente; su batería baja. Aparece un cálculo simple: carga, distancia, pendiente → «probabilidad de no llegar: alta». Sale una notificación de plantilla con un hueco que se rellena con el estacionamiento más cercano. Al lado, la tarjeta de la IA generativa se tacha con la etiqueta «ADR-0021: no hace falta».",
      [
          L("Ahora el caso contrario: el consejo de carga."),
          L("Vas en un scooter y la batería baja. ¿Llegas a destino, o te conviene cambiar de ruta?"),
          L("Un modelo de aprendizaje automático sencillo calcula la probabilidad de quedarte sin batería, con tu carga, la distancia y la pendiente."),
          L("Si el riesgo es alto, te avisa con un mensaje de plantilla: el estacionamiento más cercano está en tal lugar.", p=1),
          L("El equipo descartó la IA generativa a propósito: el aviso cabe en plantillas, y no justifica el costo.", p=1.2),
          L("Es la respuesta directa a la pregunta del jurado: aquí decidimos no usarla, y este es el porqué."),
      ]),
    S("piensalo", "Piénsalo tú",
      "Una etiqueta de precio que cambia con íconos alrededor (demanda, nube de lluvia, estadio, competidor). Debajo, dos casilleros vacíos: «calcular el precio» y «explicar el precio». Anillo de 3 s. En la respuesta se llenan: calcular → ML + reglas (margen mínimo, normas locales); explicar → IA generativa, con una burbuja de ejemplo. Fuente: ADR-0018.",
      [
          L("Ahora tú. Los precios dinámicos: el precio cambia según la demanda, el clima, los eventos y la competencia."),
          L("Hay dos trabajos: calcular el precio, y explicárselo al cliente. ¿Qué herramienta pondrías a cargo de cada uno?", p=3),
          L("El equipo lo partió así: un modelo de aprendizaje automático calcula el precio, y reglas en código aplican los límites, como el margen mínimo o las normas locales."),
          L("La IA generativa solo explica: el precio está más alto por un evento en la zona."),
          L("Que calculara ella fue una alternativa descartada: no es confiable con la precisión de los números.", p=1),
      ]),
    S("regla", "La regla",
      "Una escalera de tres peldaños: código abajo, aprendizaje automático en el medio, IA generativa arriba, con la leyenda «sube solo si el de abajo no alcanza». Al final, una tarjeta pequeña en gris: «rutas de los operarios → capítulo 6».",
      [
          L("La regla del capítulo: empieza por lo más simple que resuelve el problema."),
          L("Código si alcanza. Aprendizaje automático si hay que predecir. IA generativa solo donde hace falta entender o producir lenguaje.", p=1),
          L("No todas las etiquetas del equipo siguen esa regla. En el capítulo 6 veremos una, las rutas de los operarios, que el podio resolvió distinto.",
            say="No todas las etiquetas del equipo siguen esa regla. En el capítulo seis veremos una, las rutas de los operarios, que el podio resolvió distinto."),
      ]),
    S("outro", "Para llevarte",
      "Tres tarjetas de repaso: las tres herramientas, la columna Tech Choice, el asistente con el candado en el pago. Al final, una foto de un auto devuelto con un sello «¿sucio?» y un signo de pregunta (anticipo del capítulo 5).",
      [
          L("Repasemos. Tres herramientas: código, aprendizaje automático e IA generativa, cada una con su costo y su riesgo.", p=0.6),
          L("Una columna en la tabla obliga a elegir, escenario por escenario.", p=0.6),
          L("Y lo híbrido pone la IA generativa solo donde aporta, con el dinero siempre en código.", p=1),
          L("Pero aun bien ubicada, la IA se equivoca. ¿Qué haces cuando una IA decide cobrarle una tarifa a un cliente?"),
          L("Capítulo 5: confiar en una IA que se equivoca.", say="Capítulo cinco: confiar en una IA que se equivoca."),
      ]),
]
