from lib import L, S

N = 5
TITLE = "Confiar en una IA que se equivoca"
SCENES = [
    S("intro", "Capítulo 5",
      "La cámara del teléfono del capítulo 1 toma una foto de un auto devuelto. Una caja «IA» mira la foto y emite un sello «limpieza: 100 €». Título.",
      [
          L("¿Recuerdas la foto que el cliente sube al devolver un vehículo? Es la prueba de que lo dejó bien."),
          L("Con autos y camionetas, el equipo quiso que una IA mirara esas fotos y decidiera si el vehículo quedó sucio. Si quedó sucio, se cobra una tarifa de limpieza.", p=1),
          L("Capítulo 5: confiar en una IA que se equivoca.", say="Capítulo cinco: confiar en una IA que se equivoca."),
      ]),
    S("riesgo", "Dos errores",
      "Una regla horizontal de 0 a 100 % con un indicador: la confianza del modelo. Luego una tabla de dos por dos simple: lo que dice la IA (sucio / limpio) contra la realidad. Se iluminan solo dos celdas, una por frase: falso positivo (rojo, cliente cobrado de más) y falso negativo (ámbar, tarifa perdida). Al final, la celda roja crece y aparece la cita del requisito FR#2L: «AI false positives damaging customer trust».",
      [
          L("El modelo mira las fotos y da un veredicto, con un número de confianza: qué tan seguro está, de 0 a 100 %.",
            say="El modelo mira las fotos y da un veredicto, con un número de confianza: qué tan seguro está, de cero a cien por ciento."),
          L("El problema es que se equivoca. Y hay dos formas de equivocarse.", p=0.6),
          L("Un falso positivo: dice sucio, y estaba limpio. Le cobras a alguien que no lo merece."),
          L("Un falso negativo: dice limpio, y estaba sucio. Pierdes la tarifa, y el próximo cliente encuentra el auto sucio.", p=1),
          L("El equipo escribió cuál le preocupaba más: los falsos positivos, porque dañan la confianza del cliente.", p=1),
          L("Y ese cliente es justo el que la empresa quiere convertir en usuario de todos los días."),
      ]),
    S("bandas", "Tres bandas",
      "La regla de 0 a 100 se parte en tres franjas de color que aparecen una por frase: verde (>90 %, decide solo, guarda evidencia), ámbar (80–90 %, una persona revisa), gris (<80 %, no se cobra). Un ícono de persona entra en la franja ámbar. Al definir human-in-the-loop, un circuito con la persona dentro. Al hablar de costos, los cortes se deslizan y la franja ámbar se ensancha y se angosta.",
      [
          L("La respuesta del equipo fue partir la confianza en tres bandas."),
          L("Por encima del 90 %, el sistema decide solo, y guarda la evidencia.",
            say="Por encima del noventa por ciento, el sistema decide solo, y guarda la evidencia."),
          L("Entre 80 y 90 %, el caso va a una persona, que mira las fotos y confirma o corrige.",
            say="Entre ochenta y noventa por ciento, el caso va a una persona, que mira las fotos y confirma o corrige.", p=1),
          L("Por debajo del 80 %, no se cobra nada. La duda favorece al cliente.",
            say="Por debajo del ochenta por ciento, no se cobra nada. La duda favorece al cliente.", p=1.2),
          L("Este diseño se llama human-in-the-loop: humano en el circuito. La máquina decide lo fácil, y una persona decide lo dudoso.", p=1),
          L("Y los cortes tienen su costo: más casos a revisión es más trabajo humano; menos casos, más errores automáticos."),
      ]),
    S("circuito", "Cerrar el circuito",
      "Basado en el ADR-0016: la persona revisora corrige un caso; la corrección se convierte en una foto etiquetada que viaja a una pila de «datos de entrenamiento»; la pila alimenta una versión nueva del modelo (v2). Luego dos revisoras miran la misma foto: si coinciden, tilde; si no, el signo de alerta apunta a las personas, no al modelo.",
      [
          L("Hay un detalle que convierte esto en algo más que un filtro."),
          L("Cada vez que una persona corrige al modelo, esa corrección se guarda como un ejemplo nuevo, bien etiquetado."),
          L("Con esos ejemplos se vuelve a entrenar el modelo, y la versión siguiente duda menos en esos casos.", p=1),
          L("El equipo también pidió medir si los revisores coinciden entre sí. Si dos personas no se ponen de acuerdo, el problema no es el modelo.", p=1),
          L("Las revisiones no son un costo perdido: son la fábrica de datos del modelo siguiente."),
      ]),
    S("mlops", "MLOps",
      "Redibujar el diagrama hld/mlops/MLOps on GCP.png simplificado en un ciclo de cinco estaciones: datos → entrenar → evaluar (compuerta: ¿supera al anterior?) → producción → monitorear deriva → vuelta a entrenar. Al hablar de deriva, las fotos de entrada cambian de tono (estaciones del año, cámaras nuevas) y se separan de la nube de entrenamiento. El ciclo queda en pantalla al final, con la etiqueta «Vertex AI».",
      [
          L("Ahora el modelo ya está en producción. ¿Cómo sabes, un mes después, que sigue funcionando?"),
          L("Los modelos se degradan. Cambian las cámaras de los teléfonos, cambian las estaciones del año, y los datos dejan de parecerse a los del entrenamiento."),
          L("A eso se le llama deriva.", p=1),
          L("Para manejarla existe MLOps: las prácticas que automatizan la vida de un modelo, desde entrenarlo hasta vigilarlo en producción.",
            say="Para manejarla existe eme ele ops: las prácticas que automatizan la vida de un modelo, desde entrenarlo hasta vigilarlo en producción.", p=1),
          L("El plan del equipo, sobre Vertex AI, la plataforma de modelos de Google: cada versión nueva se evalúa antes de salir, y solo pasa si supera a la anterior."),
          L("En producción, un monitor vigila la deriva. Si el modelo cae debajo del 80 % de acierto durante 14 días, se vuelve a entrenar.",
            say="En producción, un monitor vigila la deriva. Si el modelo cae debajo del ochenta por ciento de acierto durante catorce días, se vuelve a entrenar."),
      ]),
    S("negocio", "La señal del negocio",
      "Dos tableros lado a lado: «métrica técnica» (acierto del modelo, estable) y «métrica del negocio» (costo de mantenimiento por vehículo, subiendo). Un signo de alerta aparece solo en el segundo. Síntesis en dos líneas grandes.",
      [
          L("Una idea más, de su documento de MLOps: mirar también los números del negocio.",
            say="Una idea más, de su documento de eme ele ops: mirar también los números del negocio."),
          L("Si un modelo de mantenimiento funciona, los costos de mantenimiento deberían bajar. Si suben, algo anda mal, aunque las métricas técnicas digan que todo va bien.", p=1),
          L("La métrica técnica dice si el modelo acierta. La del negocio dice si acertar sirvió.", p=1),
      ]),
    S("piensalo", "Piénsalo tú",
      "La regla de tres bandas con un marcador en 85 %. Anillo de 3 s. En la respuesta, el marcador cae en la franja ámbar, entra la persona revisora y la flecha de corrección hacia los datos de entrenamiento.",
      [
          L("Ahora tú. Llega una devolución, y el modelo está seguro en un 85 % de que el auto quedó sucio.",
            say="Ahora tú. Llega una devolución, y el modelo está seguro en un ochenta y cinco por ciento de que el auto quedó sucio."),
          L("Con las bandas del equipo, ¿qué pasa con esa tarifa?", p=3),
          L("Va a revisión humana: está entre 80 y 90.", say="Va a revisión humana: está entre ochenta y noventa."),
          L("Una persona mira las fotos antes de cobrar. Y si el modelo se equivocó, su corrección entrena al siguiente.", p=1),
      ]),
    S("abierto", "Lo que queda abierto",
      "Las tres bandas de limpieza (90 / 80) junto a las de detección de daños (85 / 70), del ADR-0020. Etiqueta sobre ambas: «metas elegidas por el equipo, no resultados medidos».",
      [
          L("Un aviso honesto: esos porcentajes son metas que el equipo eligió, no resultados medidos."),
          L("Y los cortes cambian de modelo a modelo. Para detectar daños en la carrocería, el equipo usó otros: 85 y 70.",
            say="Y los cortes cambian de modelo a modelo. Para detectar daños en la carrocería, el equipo usó otros: ochenta y cinco y setenta."),
          L("Eso está bien. Cada decisión tiene su propio costo de error, y sus cortes se ajustan con datos reales.", p=1),
      ]),
    S("outro", "Para llevarte",
      "Tres tarjetas de repaso: la tabla de dos errores con la celda roja, las tres bandas, el ciclo de MLOps. Al final, un monumento con bicicletas amontonadas (el problema 1 del capítulo 1) y un reloj de arena casi vacío.",
      [
          L("Repasemos. Una IA probabilística se equivoca: decide qué error te duele más.", p=0.6),
          L("Bandas de confianza: decide solo lo seguro, revisa lo dudoso, y en la duda, favorece al cliente.", p=0.6),
          L("Y MLOps vigila la deriva, con métricas técnicas y del negocio.",
            say="Y eme ele ops vigila la deriva, con métricas técnicas y del negocio.", p=1),
          L("Ahora sí, el problema número uno del cliente: vehículos en el lugar equivocado. El equipo lo diseñó al final."),
          L("Capítulo 6: el vehículo correcto, en el lugar correcto.", say="Capítulo seis: el vehículo correcto, en el lugar correcto."),
      ]),
]
