from lib import L, S

N = 6
TITLE = "El vehículo correcto, en el lugar correcto"
SCENES = [
    S("intro", "Capítulo 6",
      "El monumento con bicicletas amontonadas y el resto del mapa vacío (capítulo 1, problema 1). Debajo, la línea de tiempo del repositorio, todavía apagada. Título.",
      [
          L("¿Recuerdas el problema más grande de MobilityCorp? Los vehículos no están donde la gente los necesita."),
          L("El historial del repositorio muestra algo curioso: fue lo último que el equipo diseñó en detalle.", p=1),
          L("Capítulo 6: el vehículo correcto, en el lugar correcto.", say="Capítulo seis: el vehículo correcto, en el lugar correcto."),
      ]),
    S("orden", "El orden real",
      "Línea de tiempo del 17 al 23 de octubre con una tarjeta por escenario, en la fecha de su primer commit: opiniones (17), rutas (18–19), precios y baterías (19), pronóstico de demanda (22) y su ADR-0022 (23, junto al ícono de cámara de la foto del repositorio). La tarjeta del pronóstico entra última y más grande. Una marca tenue en el 17 indica «el pronóstico ya era requisito». La frase de inferencia aparece con la etiqueta «lectura posible».",
      [
          L("Mira las fechas de cada escenario en el repositorio."),
          L("El análisis de opiniones, el 17 de octubre. El asistente de rutas, entre el 18 y el 19. Los precios y las baterías, el 19.",
            say="El análisis de opiniones, el diecisiete de octubre. El asistente de rutas, entre el dieciocho y el diecinueve. Los precios y las baterías, el diecinueve."),
          L("El pronóstico de demanda tuvo su diseño propio recién el 22, y su ADR, un día antes de la entrega.",
            say="El pronóstico de demanda tuvo su diseño propio recién el veintidós, y su ADR, un día antes de la entrega.", p=1),
          L("Como requisito, el pronóstico estaba en la tabla desde el tercer día. Lo que llegó tarde fue su diseño."),
          L("El repositorio no dice por qué. Una lectura posible: el jurado premiaba usos interesantes de IA generativa, y los escenarios con chat se diseñaron primero.", p=1),
          L("Veamos qué hizo el equipo cuando llegó."),
      ]),
    S("operarios", "El circuito de los operarios",
      "Redibujar hld/scenarios/battery-replacement-and-fleet-allocation/Battery Replacement and Fleet Allocation.drawio.png como un flujo numerado de izquierda a derecha: scooter → Fleet Service (marca no disponible, avisa al cliente) → pedido de mantenimiento → modelo ML de batería (recargar o reemplazar) → app de los operarios. En la línea 5, una camioneta de operarios con baterías cargadas recoge un scooter y lo deja junto a una estación de tren (unión del 20 de octubre).",
      [
          L("Primero, las baterías. El servicio de flota, ¿recuerdas?, ve que la batería de un scooter bajó del umbral."),
          L("Lo marca como no disponible, le avisa al cliente que termine su viaje, y crea un pedido de mantenimiento."),
          L("Un modelo de aprendizaje automático estima el estado de la batería: cuánta vida útil le queda, para decidir si se recarga o se reemplaza."),
          L("Y la app de los operarios les dice a dónde ir.", p=1),
          L("El 20 de octubre, el equipo juntó dos tareas en este mismo circuito: cambiar baterías, y llevar vehículos a donde habrá demanda.",
            say="El veinte de octubre, el equipo juntó dos tareas en este mismo circuito: cambiar baterías, y llevar vehículos a donde habrá demanda."),
          L("El operario que ya está en la calle con baterías cargadas, de paso, lleva scooters a donde se van a necesitar.", p=1),
          L("Pero para eso, alguien tiene que saber dónde habrá demanda."),
      ]),
    S("pronostico", "Pronosticar la demanda",
      "Un gráfico de líneas por hora a lo largo de una semana: picos de bicicletas a la hora de ir y volver del trabajo (curva azul), camionetas que suben el fin de semana (curva naranja). Al nombrar el clima, una nube de lluvia aplana la curva azul; al nombrar eventos, un estadio produce un pico aislado.",
      [
          L("Pronosticar la demanda es predecir cuántos vehículos se van a pedir, en cada zona y a cada hora."),
          L("Es un problema de series de tiempo: datos ordenados en el tiempo, como las reservas de cada hora, que repiten patrones.", p=0.8),
          L("Las bicicletas se piden más a la hora de ir al trabajo. Las camionetas, más los fines de semana."),
          L("Y el clima y los eventos de la ciudad lo mueven todo.", p=1),
          L("Con aprendizaje automático, podrías lanzarte a un modelo grande y complejo. El equipo no empezó por ahí."),
      ]),
    S("escalera", "Empezar simple",
      "Una escalera de dos peldaños (basada en el ADR-0022). Peldaño 1: «modelo estadístico (Prophet)», con la curva descompuesta en tendencia + patrón diario + patrón semanal + feriados, y dos instancias: scooters y bicicletas / autos y camionetas. Peldaño 2: «ML más potente», con un candado. La condición del candado se escribe a la vista: error a 24 h > 30 % durante 4 semanas seguidas. Al final, un eco visual de las bandas del capítulo 5.",
      [
          L("Su ADR número 22 propone una escalera.", say="Su ADR número veintidós propone una escalera."),
          L("Primer peldaño: un modelo estadístico clásico, llamado Prophet, que entiende patrones por hora, por día y por semana, y también feriados."),
          L("Se pone en marcha rápido, y se puede explicar: muestra cuánto pesa la tendencia y cuánto pesa cada patrón."),
          L("Hay un modelo para scooters y bicicletas, y otro para autos y camionetas, porque sus patrones son distintos.", p=1),
          L("Segundo peldaño: modelos de aprendizaje automático más potentes. Pero solo si el primero falla de forma medible."),
          L("La condición está escrita: si el error del pronóstico a 24 horas supera el 30 % durante cuatro semanas seguidas, se sube un peldaño.",
            say="La condición está escrita: si el error del pronóstico a veinticuatro horas supera el treinta por ciento durante cuatro semanas seguidas, se sube un peldaño.", p=1.2),
          L("¿Te suena? Es la lógica del capítulo anterior: una meta medible decide cuándo gastar más."),
      ]),
    S("piensalo", "Piénsalo tú",
      "Un mapa de una ciudad nueva, sin puntos, con un calendario vacío: «0 meses de datos». Anillo de 3 s. En la respuesta, una línea plana que sigue el promedio de los últimos días, con la etiqueta «hasta tener 3 meses», y flechas que traen patrones de dos ciudades parecidas. Fuente: tabla de riesgos del ADR-0022 (cold start).",
      [
          L("Ahora tú. MobilityCorp abre en una ciudad nueva. No hay historia: cero meses de datos."),
          L("¿Qué pronóstico usarías al principio?", p=3),
          L("El equipo lo anotó en sus riesgos: un promedio simple, que se mueve con los últimos días, hasta juntar 3 meses de datos.",
            say="El equipo lo anotó en sus riesgos: un promedio simple, que se mueve con los últimos días, hasta juntar tres meses de datos."),
          L("Y patrones prestados de ciudades parecidas. Sin datos, ni el modelo más sofisticado tiene de dónde aprender.", p=1),
      ]),
    S("podio", "Lo que el podio hizo distinto",
      "Un mapa con muchas paradas, una camioneta con capacidad limitada y un reloj de turno. Pantalla partida: izquierda, Five Nines (ADR-0019): «IA generativa arma la ruta + reglas para límites duros»; derecha, Nimrods, segundo puesto (docs/decisions/012-redistribution-optimizer-algo.md): «solver OR-Tools calcula la ruta; IA generativa conversa con el operario». Al final, la escalera de herramientas del capítulo 4 con la frase «calcular es matemática; conversar es lenguaje».",
      [
          L("Falta una pieza: con el pronóstico en la mano, ¿qué ruta sigue cada operario?"),
          L("Es un problema clásico de optimización: muchas paradas, camionetas con capacidad limitada, y turnos con horario."),
          L("El equipo le encargó el armado de rutas a la IA generativa, con reglas en código para los límites duros, como la capacidad de cada camioneta.", p=1),
          L("El segundo puesto, el equipo Nimrods, eligió otra cosa: un solver, una herramienta matemática hecha para calcular rutas, llamada OR-Tools."),
          L("Su argumento: está diseñada para estos problemas, usa algoritmos probados, y es gratuita. La IA generativa la usaron para conversar con el operario sobre la propuesta.", p=1),
          L("Calcular rutas es matemática; conversar es lenguaje. Es la regla del capítulo 4, y aquí el diseño ganador no la siguió.",
            say="Calcular rutas es matemática; conversar es lenguaje. Es la regla del capítulo cuatro, y aquí el diseño ganador no la siguió.", p=1),
      ]),
    S("outro", "Para llevarte",
      "Tres tarjetas de repaso: la línea de tiempo con el pronóstico al final, la camioneta que cambia baterías y reubica, la escalera con su candado. Al final, el logo de Google Cloud con una etiqueta de precio que sube (anticipo del capítulo 7).",
      [
          L("Repasemos. El problema número uno del cliente se diseñó al final, y vale la pena notarlo.", p=0.6),
          L("Cambiar baterías y mover vehículos van en el mismo circuito de los operarios.", p=0.6),
          L("Y el pronóstico sube de peldaño solo cuando una meta medible lo pide.", p=1),
          L("Hasta aquí, todo el diseño apuesta por Google. ¿Qué pasa si Google cambia los precios mañana?"),
          L("Capítulo 7: cuando el proveedor cambia las reglas.", say="Capítulo siete: cuando el proveedor cambia las reglas."),
      ]),
]
