from lib import L, S

N = 7
TITLE = "Cuando el proveedor cambia las reglas"
SCENES = [
    S("intro", "Capítulo 7",
      "El tercer casillero del jurado (nube con rayo) del capítulo 1 se agranda. Tres íconos aparecen con cada ejemplo: etiqueta de precio con flecha hacia arriba, calendario que pasa de mes, puerta que se cierra. Título.",
      [
          L("¿Recuerdas el tercer criterio del jurado? La incertidumbre de la IA."),
          L("El anfitrión del kata dio ejemplos concretos: hoy los precios de la IA generativa están subsidiados, los modelos cambian cada mes, y algunos proveedores van a cerrar.", p=1),
          L("Capítulo 7: cuando el proveedor cambia las reglas.", say="Capítulo siete: cuando el proveedor cambia las reglas."),
      ]),
    S("apuesta", "Todo en Google",
      "La nube del capítulo 3 con sus tres piezas: Vertex AI, Gemini, Google Maps. Al definir vendor lock-in, unas cadenas finas unen cada pieza al sistema, y una flecha de «salida» se vuelve más larga con cada pieza agregada. Cita del anfitrión al pie: «puedes ir con todo a un proveedor; explica por qué en un ADR» (captions, minuto 57).",
      [
          L("Ya viste la apuesta del equipo: Google Cloud para todo."),
          L("Vertex AI, la plataforma de Google para entrenar y servir modelos. Gemini, sus modelos de lenguaje. Y Google Maps, para los mapas.", p=0.8),
          L("Su ADR de la nube daba un argumento más: competidores directos, como Bird y Dott, ya funcionan sobre Google Cloud. Es una tecnología probada en este negocio.", p=0.8),
          L("Eso tiene un nombre en inglés: vendor lock-in, quedar atado a un proveedor. Cuantas más piezas suyas usas, más caro es irte.", p=1),
          L("El jurado no prohibía atarse. Pedía otra cosa: que lo eligieras sabiendo el costo, y que lo escribieras."),
          L("Eso hizo el equipo, aunque no desde el principio."),
      ]),
    S("seccion", "Una sección nueva",
      "Redibujar la plantilla adrs/ADR-0000 - Template.md: secciones Context, Decision, Key Differentiators, Alternatives, Conclusion. El 20 de octubre (commit 4497171) se inserta una sección nueva, «Risks & Trade-offs», con una tabla de tres columnas: riesgo, descripción, mitigación. Luego las tarjetas de los ADRs 1 a 4 reciben la misma tabla, una tras otra, con relojes que marcan 10:59, 11:01, 11:02 y 11:03. Varias tablas muestran «Vendor lock-in» en sus primeras filas.",
      [
          L("Sus primeros ADRs, los de la nube, la telemetría, Vertex y Gemini, explicaban por qué elegir cada pieza. No tenían una tabla de riesgos."),
          L("El 20 de octubre, el equipo agregó esa sección a su plantilla de ADR: riesgos y trade-offs. Y esa misma mañana la completó en los cuatro ADRs anteriores.",
            say="El veinte de octubre, el equipo agregó esa sección a su plantilla de ADR: riesgos y trade-offs. Y esa misma mañana la completó en los cuatro ADRs anteriores.", p=1),
          L("Desde ese día, cada decisión trae su tabla: el riesgo, qué lo causa, y cómo se mitiga. En muchas, el lock-in está entre los primeros.", p=1),
          L("Una decisión sin su precio escrito está tomada a medias."),
      ]),
    S("salidas", "Las salidas de emergencia",
      "Un plano de edificio con tres puertas de emergencia que se encienden una por frase: 1) Gemini → API tradicional de Google Maps (ADR-0004), 2) Gemini → modelo propio más chico (hld/scenarios/feedback-analysis/README.md), 3) modelos entrenados → formatos portables (ADR-0003, ADR-0014). Al final, una etiqueta de precio que sube choca contra una pared sin puertas (versión sin salidas).",
      [
          L("Escribir el riesgo no alcanza: hay que dejar puertas para salir."),
          L("Primera puerta: si Gemini falla o cambia, las funciones de mapas críticas vuelven a la API tradicional de Google Maps, que es determinista."),
          L("Segunda: para analizar las opiniones de los usuarios, el equipo anotó que, si Gemini sube mucho de precio, se cambia a un modelo propio más chico."),
          L("Tercera: los modelos que entrena el equipo se guardan en formatos portables, para poder llevarlos a otra plataforma.", p=1),
          L("Ninguna puerta es gratis. Pero sin ellas, cada suba de precio del proveedor te encuentra sin opciones."),
      ]),
    S("intermediario", "Un intermediario",
      "Basado en el ADR-0013: tres aplicaciones (asistente, precios, mantenimiento) que antes apuntaban a un solo modelo ahora apuntan a una caja intermedia, «plano de control de modelos (MoCoP)». De la caja salen flechas a tres modelos; una regla cambia y la flecha salta de un modelo caro a uno más barato sin que las aplicaciones se muevan. Íconos en la caja: monedero (gasto), escudo (políticas), libreta (registro). Al final, un calendario «revisar a los 12 meses».",
      [
          L("La puerta más grande es una pieza que el equipo llamó plano de control de modelos."),
          L("Funciona como un intermediario: las aplicaciones no le hablan directo a un modelo. Le hablan a esta pieza, y ella decide a qué modelo mandar cada pedido."),
          L("Si un modelo empeora o se encarece, cambias la regla en el intermediario, y las aplicaciones ni se enteran.", p=1),
          L("Además controla el gasto, aplica políticas, y registra cada pedido para poder auditarlo."),
          L("El equipo eligió contratarlo como servicio, en vez de construirlo, para salir rápido. Y anotó revisar esa decisión a los 12 meses.",
            say="El equipo eligió contratarlo como servicio, en vez de construirlo, para salir rápido. Y anotó revisar esa decisión a los doce meses.", p=1),
      ]),
    S("cabos", "Lo que no cierra",
      "Dos tarjetas de «cabos sueltos». 1: el ADR-0013 tacha la opción «control plane nativo de Vertex» mientras los ADRs 0003, 0009 y 0011 ponen a Vertex en el centro; una flecha de interrogación entre ambos. 2: la sigla MCP con dos globos: «Model Control Plane» y «Model Context Protocol» (el servidor MCP de clima del diagrama de rutas); el commit 17db325 la renombra MoCoP, pero el ADR-0005 conserva «MCP».",
      [
          L("Hay dos cosas que no cierran del todo."),
          L("Primera: ese ADR descarta la versión de Google del intermediario, mientras otros ADRs ponen a Vertex en el centro. El repositorio no explica cómo conviven las dos piezas.", p=1),
          L("Segunda: el equipo llamó a esa pieza MCP. Pero MCP también es la sigla de otro estándar que aparece en sus diagramas, el Model Context Protocol, que conecta modelos con herramientas.",
            say="Segunda: el equipo llamó a esa pieza eme ce pe. Pero eme ce pe también es la sigla de otro estándar que aparece en sus diagramas, el Model Context Protocol, que conecta modelos con herramientas."),
          L("Lo notó y la rebautizó MoCoP, pero en un ADR quedó el nombre viejo. Una sigla con dos significados confunde a cualquier lector.",
            say="Lo notó y la rebautizó Mocop, pero en un ADR quedó el nombre viejo. Una sigla con dos significados confunde a cualquier lector.", p=1),
      ]),
    S("piensalo", "Piénsalo tú",
      "Una etiqueta de Gemini cuyo precio se multiplica por tres. Dos tarjetas: «asistente de la app» y «consejo de carga». Anillo de 3 s. En la respuesta, la tarjeta del consejo de carga muestra la etiqueta «sin IA generativa (capítulo 4)» y no se mueve; la del asistente muestra los botones en verde (código) y solo el campo de texto libre en rojo.",
      [
          L("Ahora tú. Mañana, Gemini triplica su precio."),
          L("¿Qué sufre menos: el asistente de la app, o el consejo de carga del scooter?", p=3),
          L("El consejo de carga no sufre nada: no usa IA generativa. ¿Recuerdas el capítulo 4?",
            say="El consejo de carga no sufre nada: no usa IA generativa. ¿Recuerdas el capítulo cuatro?"),
          L("Y el asistente sufre poco, porque la mayoría de los pedidos van por botones y código."),
          L("Elegir bien la herramienta también es una defensa contra la incertidumbre.", p=1),
      ]),
    S("outro", "Para llevarte",
      "Tres tarjetas de repaso: la cadena del lock-in con su tabla de riesgos, las tres puertas, el intermediario. Al final, la cámara de la foto del repositorio (23 oct) y un claquetazo de video (anticipo del capítulo 8).",
      [
          L("Repasemos. Atarse a un proveedor es una decisión válida, si escribes su precio.", p=0.6),
          L("Desde el 20 de octubre, cada ADR del equipo trae su tabla de riesgos.",
            say="Desde el veinte de octubre, cada ADR del equipo trae su tabla de riesgos.", p=0.6),
          L("Y las salidas: alternativas deterministas, modelos portables, y un intermediario que elige el modelo.", p=1),
          L("El 23 de octubre se tomó la foto del repositorio. El equipo pasó a la semifinal, y tenía que contar todo esto en 5 minutos.",
            say="El veintitrés de octubre se tomó la foto del repositorio. El equipo pasó a la semifinal, y tenía que contar todo esto en cinco minutos."),
          L("Capítulo 8: contar la arquitectura.", say="Capítulo ocho: contar la arquitectura."),
      ]),
]
