from lib import L, S

N = 8
TITLE = "Contar la arquitectura"
SCENES = [
    S("intro", "Capítulo 8",
      "Gráfico de commits por día (datos reales del historial): barras altas del 15 al 24 de octubre, un hueco plano del 24 de octubre al 7 de noviembre, y tres barras pequeñas del 7 al 9 de noviembre. En el hueco, una marca «5 nov: semifinalistas (calendario de la sesión inaugural)». Título.",
      [
          L("Después de la foto del 23 de octubre, el repositorio queda quieto dos semanas. Ni un cambio.",
            say="Después de la foto del veintitrés de octubre, el repositorio queda quieto dos semanas. Ni un cambio."),
          L("Según el calendario, el 5 de noviembre se anunciaron los semifinalistas. El 7, el equipo vuelve a escribir.",
            say="Según el calendario, el cinco de noviembre se anunciaron los semifinalistas. El siete, el equipo vuelve a escribir.", p=1),
          L("Capítulo 8: contar la arquitectura.", say="Capítulo ocho: contar la arquitectura."),
      ]),
    S("congelado", "Qué cambió",
      "Un «diff» visual entre el repositorio de la semifinal (ebf6d83) y el final (e930bcb): las carpetas adrs/ y hld/ aparecen en gris con «0 cambios»; se iluminan solo los archivos nuevos: la tabla de metas (OKRs.md), el guion del video, la narrativa, la presentación en PDF y el README.",
      [
          L("Compara el repositorio de la semifinal con el de la final, y verás algo llamativo."),
          L("Ni un ADR cambió. Ni un diagrama.", p=0.8),
          L("Todo lo nuevo es comunicación: una tabla de metas de negocio, el guion del video, y la presentación.", p=1),
          L("El guion del video lo dice en su título: es para una audiencia de negocio. Y una nota para quien presenta pide nombrar beneficios, no tecnologías.", p=0.8),
          L("La arquitectura ya estaba decidida. Faltaba contarla para quien decide."),
      ]),
    S("reorden", "Otro orden",
      "Izquierda: los cinco escenarios en el orden del README (asistente de rutas, opiniones, baterías, precios, pronóstico). Derecha: los tres casos de uso de la presentación final (diapositiva 7). Las tarjetas se reacomodan con animación: el pronóstico salta al primer lugar, mantenimiento al segundo, visión al tercero; el asistente de rutas se desvanece. Al nombrar visión artificial, un ícono de cámara con un marco sobre un rayón.",
      [
          L("¿Recuerdas el orden del README? Primero el asistente de rutas, después las opiniones, las baterías y los precios. El pronóstico, al final."),
          L("En la presentación final, el orden se dio vuelta.", p=0.8),
          L("Tres casos de uso, nada más. Primero, pronosticar la demanda y reubicar vehículos."),
          L("Segundo, mantenimiento predictivo, y uso parejo de la flota."),
          L("Tercero, visión artificial, la IA que analiza fotos, para daños y limpieza, con revisión humana.", p=1),
          L("El asistente de rutas, el primero del README, no está entre los tres."),
          L("El problema número uno del cliente pasó a ser lo primero que se cuenta.", p=1),
      ]),
    S("compuertas", "Compuertas de valor",
      "Redibujar la diapositiva 8 («Phased Rollout: Earn Sooner, Spend Later») como cuatro tramos de un camino separados por compuertas: Fase 0 (instrumentos de medición), Fase 1 (pronóstico estadístico, bandas de precio iniciales, registro manual de daños), Fase 2 (consejo de carga, uso parejo, visión en modo sombra con un ojo semitransparente), Fase 3 (automatización). Cada compuerta tiene un medidor que debe llegar a su marca para abrirse. Al final, miniaturas de la escalera del capítulo 6 y las bandas del capítulo 5 se encajan en las compuertas.",
      [
          L("El otro cambio es una idea que ordena todo: un portafolio de IA con compuertas de valor."),
          L("Una compuerta es una condición medible que una fase tiene que cumplir para que se apruebe la siguiente.", p=1),
          L("El plan tiene cuatro fases. La fase 0 solo instala medición: cuánto se usa la flota, cuánto se equivoca el pronóstico, cuántas disputas hay.",
            say="El plan tiene cuatro fases. La fase cero solo instala medición: cuánto se usa la flota, cuánto se equivoca el pronóstico, cuántas disputas hay."),
          L("La fase 1 hace lo simple: pronóstico estadístico, y daños registrados a mano.",
            say="La fase uno hace lo simple: pronóstico estadístico, y daños registrados a mano."),
          L("La fase 2 suma el consejo de carga y la visión en modo sombra, que observa sin decidir. Y recién la fase 3 automatiza.",
            say="La fase dos suma el consejo de carga y la visión en modo sombra, que observa sin decidir. Y recién la fase tres automatiza.", p=1),
          L("Su lema: ganar antes, gastar después."),
          L("¿Te suena? Es la escalera del pronóstico y las bandas de confianza, llevadas a todo el proyecto.", p=1),
      ]),
    S("cifras", "Las cifras del video",
      "Dos hojas superpuestas: el guion del 8 de noviembre (video-scenario-business-management-5min.md) con renglones «__ % → __ %» en blanco, y el texto del 9 de noviembre (narrative.md) con «+32 %» y «240.000 €/mes». Luego, la misma métrica en dos fuentes, lado a lado: costo de mantenimiento por vehículo, narrative.md «78 € → 60 €» contra la diapositiva 7 «117,1 € → 79,08 €», con un signo de desigualdad. Al final vuelven los tres cajones del capítulo 2: las cifras caen en «supuesto».",
      [
          L("Ahora, un punto que hay que mirar con cuidado."),
          L("El 8 de noviembre, el guion del video tenía las cifras en blanco: utilización, de tanto a tanto. Costo por vehículo, de tanto a tanto.",
            say="El ocho de noviembre, el guion del video tenía las cifras en blanco: utilización, de tanto a tanto. Costo por vehículo, de tanto a tanto."),
          L("Al día siguiente aparecieron: 32 % más de utilización, 240.000 euros más de ingresos por mes.",
            say="Al día siguiente aparecieron: treinta y dos por ciento más de utilización, doscientos cuarenta mil euros más de ingresos por mes.", p=1),
          L("Pero el repositorio no tiene el cálculo detrás. Y el texto del video y las diapositivas dan cifras distintas para lo mismo, como el costo de mantenimiento por vehículo.", p=1.2),
          L("¿Recuerdas el capítulo 2? Un número puede ser dado, calculado o supuesto. Estos son supuestos, presentados como resultados.",
            say="¿Recuerdas el capítulo dos? Un número puede ser dado, calculado o supuesto. Estos son supuestos, presentados como resultados.", p=1),
          L("Las compuertas, en cambio, se sostienen: son reglas que cualquiera puede verificar."),
      ]),
    S("piensalo", "Piénsalo tú",
      "Un atril frente a tres siluetas de jueces y un reloj de 5:00. Dos tarjetas en la mano: «+32 % de utilización» y «solo pasamos a la fase 2 si el pronóstico mejora hasta tal error». Anillo de 3 s. En la respuesta, la tarjeta de la regla se apoya sobre una pila de ADRs; la de la proyección queda flotando con un signo de pregunta.",
      [
          L("Ahora tú. Tienes 5 minutos frente al jurado. Puedes mostrar una proyección, 32 % más de utilización, o una regla: solo pasamos a la fase 2 si el pronóstico baja su error hasta cierto punto.",
            say="Ahora tú. Tienes cinco minutos frente al jurado. Puedes mostrar una proyección, treinta y dos por ciento más de utilización, o una regla: solo pasamos a la fase dos si el pronóstico baja su error hasta cierto punto."),
          L("¿Cuál puedes defender con lo que hay en tu repositorio?", p=3),
          L("La regla. Se apoya en decisiones escritas, y se puede comprobar."),
          L("La proyección necesita su cálculo. Sin él, un juez atento lo va a preguntar.", p=1),
      ]),
    S("metodo", "El método",
      "Seis tarjetas numeradas que se acumulan en una columna, una por frase, cada una con el ícono de su capítulo: nota al margen (2), Fleet Service (3), escalera de herramientas (4), bandas de confianza (5), puertas de emergencia (7), compuertas (6 y 8). Quedan juntas 6 segundos al final.",
      [
          L("Recorramos el método del equipo de punta a punta."),
          L("Uno: la IA es una solución, no un objetivo. Cada pieza señala la meta que mueve."),
          L("Dos: datos en orden, con una sola fuente de verdad."),
          L("Tres: para cada problema, la herramienta más simple que alcanza. Código, aprendizaje automático o IA generativa."),
          L("Cuatro: confiar con método. Bandas de confianza, personas en lo dudoso, y vigilancia en producción."),
          L("Cinco: escribir el precio de cada apuesta, y dejar salidas.", p=0.8),
          L("Y seis: crecer por compuertas, ganando antes de gastar.", p=1.2),
      ]),
    S("outro", "Para llevarte",
      "La insignia de primer puesto en trazo simple. Debajo, la dirección del repositorio escrita: github.com/TheKataLog/Five-Nines. Las cuatro preguntas finales aparecen una por una y quedan en pantalla hasta el cierre.",
      [
          L("Five Nines ganó el kata con este razonamiento, con sus aciertos y con sus huecos, que también viste."),
          L("Todos sus documentos son públicos, en el repositorio Five-Nines de TheKataLog, en GitHub.",
            say="Todos sus documentos son públicos, en el repositorio Five Nines de The Kata Log, en GitHub.", p=1),
          L("Ahora tienes sus preguntas. ¿Qué meta mueve esta IA? ¿Cuál es la herramienta más simple que alcanza?"),
          L("¿Qué pasa cuando se equivoca? ¿Y cuánto cuesta salir?", p=1.2),
          L("Gracias por recorrer este curso. Ahora, a diseñar."),
      ]),
]
