// Copies the course's shared kit (video/kit/) into every chapter and writes the project files each chapter needs.
// Never touched here: compositions/, narration.json (fuentes/build.py writes it), README.md, tools/icons.extra.json,
// and chapter-only assets (assets/team/). index.html is only created when missing (tools/timing.mjs lays out its film).
//   node video/sync-kit.mjs
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync, readdirSync } from 'node:fs';
const V = new URL('./', import.meta.url).pathname;
const KIT = V + 'kit/';
const HF = '0.8.139'; // same pinned HyperFrames as KatArch's chapters
const css = readFileSync(KIT + 'assets/kit.base.css', 'utf8') + readFileSync(KIT + 'assets/kit.pr.css', 'utf8');
for (let n = 1; n <= 8; n++) {
  const D = `${V}ch${n}/`;
  if (!existsSync(D + 'narration.json')) continue;
  const N = JSON.parse(readFileSync(D + 'narration.json', 'utf8'));
  for (const d of ['assets/fonts', 'tools', 'compositions']) mkdirSync(D + d, { recursive: true });
  writeFileSync(D + 'assets/kit.css', '/* generated by video/sync-kit.mjs from video/kit/assets/kit.base.css + kit.pr.css: edit those */\n' + css);
  copyFileSync(KIT + 'assets/kit.js', D + 'assets/kit.js');
  // a chapter with its own extra icons regenerates icons.js itself (NODE_PATH=... node tools/icons.mjs)
  if (!existsSync(D + 'tools/icons.extra.json')) copyFileSync(KIT + 'assets/icons.js', D + 'assets/icons.js');
  for (const f of readdirSync(KIT + 'assets/fonts')) copyFileSync(KIT + 'assets/fonts/' + f, D + 'assets/fonts/' + f);
  for (const f of readdirSync(KIT + 'tools')) copyFileSync(KIT + 'tools/' + f, D + 'tools/' + f);
  const id = `pragmatic-ch${n}`;
  const run = (c) => `DO_NOT_TRACK=1 HYPERFRAMES_NO_TELEMETRY=1 npx --yes hyperframes@${HF} ${c}`;
  writeFileSync(D + 'package.json', JSON.stringify({ name: id, private: true, type: 'module', scripts: { dev: run('preview'), check: run('check'), render: run('render'), publish: `npx --yes hyperframes@${HF} publish` } }, null, 2) + '\n');
  writeFileSync(D + 'hyperframes.json', JSON.stringify({ $schema: 'https://hyperframes.heygen.com/schema/hyperframes.json', registry: 'https://raw.githubusercontent.com/heygen-com/hyperframes/main/registry', paths: { blocks: 'compositions', components: 'compositions/components', assets: 'assets' }, media: { autoProxy: true } }, null, 2) + '\n');
  writeFileSync(D + 'meta.json', JSON.stringify({ id, name: id, createdAt: '2026-10-07T12:00:00.000Z' }, null, 2) + '\n');
  writeFileSync(D + '.gitignore', 'renders/\nsnapshots/\n.hf*/\nassets/voice/\nvoice.json\n');
  if (!existsSync(D + 'index.html')) writeFileSync(D + 'index.html', readFileSync(KIT + 'index.tpl.html', 'utf8').replaceAll('{{TITLE}}', N.title).replaceAll('{{N}}', String(n)));
}
console.log('kit synced');
