// One-off: renders the Lucide icons the video uses into assets/icons.js (window.ICONS), so the composition needs no network.
// The course-wide list lives here (synced from video/kit/); a chapter can add its own in tools/icons.extra.json ({ "key": "LucideName" }).
//   node tools/icons.mjs   (react, react-dom and lucide-react must resolve: run with NODE_PATH=<repo>/node_modules)
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
const require = createRequire(process.env.NODE_PATH ? process.env.NODE_PATH.split(':')[0] + '/' : import.meta.url);
const { createElement } = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const L = require('lucide-react');
const names = {
  // people and organisations
  user: 'User', users: 'Users', userCheck: 'UserCheck', userX: 'UserX', building: 'Building2', briefcase: 'BriefcaseBusiness', handshake: 'Handshake', heart: 'HeartHandshake', graduation: 'GraduationCap', expert: 'UserRoundSearch',
  // documents and records
  doc: 'ScrollText', file: 'FileText', fileSearch: 'FileSearch', fileUser: 'FileUser', notebook: 'NotebookPen', sticky: 'StickyNote', book: 'BookOpen', glossary: 'BookA', listChecks: 'ListChecks', list: 'List', clipboard: 'ClipboardCheck', stamp: 'Stamp', archive: 'Archive', history: 'History', pencil: 'PenLine', quote: 'Quote', hash: 'Hash',
  // software pieces
  server: 'Server', db: 'Database', container: 'Container', boxes: 'Boxes', box: 'Box', layers: 'Layers', network: 'Network', plug: 'Plug', cable: 'Cable', puzzle: 'Puzzle', cloud: 'Cloud', cpu: 'Cpu', bot: 'Bot', brain: 'Brain', sparkles: 'Sparkles', terminal: 'SquareTerminal', workflow: 'Workflow', git: 'GitBranch', commit: 'GitCommitHorizontal', inbox: 'Inbox', mail: 'Mail', send: 'Send', radio: 'Radio', megaphone: 'Megaphone', monitor: 'Monitor', phone: 'Smartphone', key: 'KeyRound', lock: 'Lock', unlock: 'LockOpen', shield: 'ShieldCheck', shieldAlert: 'ShieldAlert', eye: 'Eye', eyeOff: 'EyeOff', fingerprint: 'Fingerprint', filter: 'Filter', search: 'Search', link: 'Link', unlink: 'Unlink', copy: 'Copy', ghost: 'Ghost', wrench: 'Wrench', hammer: 'Hammer', settings: 'Settings', sliders: 'SlidersHorizontal',
  // numbers, money, time
  coins: 'Coins', piggy: 'PiggyBank', dollar: 'DollarSign', receipt: 'Receipt', chart: 'BarChart3', trend: 'TrendingUp', trendDown: 'TrendingDown', radar: 'Radar', sigma: 'Sigma', calculator: 'Calculator', ruler: 'Ruler', gauge: 'Gauge', scale: 'Scale', grid: 'Grid3x3', clock: 'Clock', timer: 'Timer', hourglass: 'Hourglass', calendar: 'CalendarDays', moon: 'Moon', refresh: 'RefreshCw', rotate: 'RotateCw', zap: 'Zap', dice: 'Dices', thermometer: 'Thermometer', flask: 'FlaskConical', target: 'Target',
  // marks
  check: 'Check', x: 'X', ban: 'Ban', help: 'CircleHelp', alert: 'TriangleAlert', pause: 'Pause', flag: 'Flag', trophy: 'Trophy', medal: 'Medal', crown: 'Crown', star: 'Star', arrowRight: 'ArrowRight', route: 'Route', door: 'DoorOpen', thumbsUp: 'ThumbsUp', thumbsDown: 'ThumbsDown', message: 'MessageSquare', messages: 'MessagesSquare', lightbulb: 'Lightbulb', compass: 'Compass', map: 'Map',
};
const extraFile = new URL('./icons.extra.json', import.meta.url);
if (existsSync(extraFile)) Object.assign(names, JSON.parse(readFileSync(extraFile, 'utf8')));
const out = {};
for (const [k, n] of Object.entries(names)) {
  if (!L[n]) throw new Error('missing icon ' + n);
  out[k] = renderToStaticMarkup(createElement(L[n], { size: 24, strokeWidth: 1.75, color: 'currentColor' })).replace(/ class="[^"]*"/, '');
}
writeFileSync(new URL('../assets/icons.js', import.meta.url), '/* generated by tools/icons.mjs (Lucide, ISC) */\nwindow.ICONS = ' + JSON.stringify(out, null, 0) + ';\n');
console.log(Object.keys(out).length, 'icons');
