import type { Chapter } from '../types';
import { c, doc } from './helpers';

export const costos: Chapter = {
  id: 'costos',
  number: 9,
  phase: 'The economic reality',
  title: 'The yearly bill',
  subtitle: 'Volume estimates, three cost scenarios and why paid monitoring won.',
  minutes: 13,
  learn: [
    'Size a system with <strong>volumetry</strong>: the weight and frequency of every message, before choosing any server.',
    'Read the three yearly cost scenarios and explain why <strong>ten times the load</strong> did not cost ten times more.',
    'Explain why paid monitoring came out <strong>cheaper than free</strong>.',
    'Recognize when the same yardstick says <strong>build it yourself</strong>.',
  ],
  steps: [
    {
      id: 'cover',
      layout: 'cover',
      title: 'The yearly bill',
      blocks: [
        { t: 'p', html: 'Chapter after chapter, the team chose the simple option. This one checks the price: the winning team’s cost spreadsheet, from the bytes of a single message to the yearly bill in three growth scenarios.' },
      ],
    },

    /* ── the spreadsheet ── */
    {
      id: 'planilla',
      kicker: 'The spreadsheet',
      title: 'The only finalist that sent a bill',
      visual: { scene: 'cost-scenarios' },
      describe: '<p>Three rows, one per scenario in the spreadsheet. Minimum: 500 requests a day, 15,000 a month, about 0.006 per second. Projected growth: 1,000 a day, 31,000 a month, about 0.012 per second. Rapid growth: 10,000 a day, 310,000 a month, about 0.12 per second. Each bar sits on a track that ends at one request per second, the yardstick from chapter 1.</p>',
      blocks: [
        { t: 'p', html: `Of the kata’s ten finalists, only the winning team delivered a cost analysis ${doc('cost-analysis')}: a spreadsheet with the full calculation, measured as ${c('tco', 'TCO')}. Not each piece’s list price, but the yearly cost of keeping everything running.` },
        { t: 'p', html: 'It models three scenarios: <strong>500, 1,000 and 10,000</strong> customer requests a day. The third one is the rapid growth that chapter 1 announced.' },
        { t: 'p', html: 'Look at them against the chapter 1 yardstick: even rapid growth stays around a tenth of one request per second.' },
      ],
    },

    /* ── volumetry ── */
    {
      id: 'volumetria',
      kicker: 'Volumetry',
      title: 'Weight times frequency',
      visual: { scene: 'cost-volumetry', state: 'guess' },
      describe: '<p>The team’s volumetry table. Confirming an order: 0.2 kb, 1 to 3 a day per user. Full catalog without images: 500 to 700 kb, downloaded once a day, lives 24 hours on the device. Stock update for one fridge: 0.1 to 150 kb, with every order and per fridge batch. Cancelling an order: 0.1 kb, 2 to 5% of orders. Daily dispatch to a kitchen: 20 to 50 kb, 0 to 2 a day per fridge. Review with a photo: about 4 MB; 10% of users write reviews and 5% report a problem.</p>',
      blocks: [
        { t: 'p', html: 'Where do the figures come from? From what the team called <strong>volumetry</strong>: for every message that travels through the system, how much it weighs and how often it happens. Bandwidth and storage follow from that table.' },
        {
          t: 'predict',
          question: 'Which message is the heaviest in the whole system?',
          options: [
            { label: 'Downloading the full meal catalog', feedback: 'Close: 500 to 700 kb, once a day. Heavy for a phone, light next to the winner.' },
            { label: 'A stock update for one fridge', feedback: 'Between 0.1 and 150 kb. Frequent, but small.' },
            { label: 'A customer review with a photo', correct: true, feedback: '<strong>Right: about 4 MB.</strong> The heaviest message is not generated by the business. It is a customer complaining with a photo.' },
            { label: 'The daily dispatch to a kitchen', feedback: '20 to 50 kb, at most twice a day per fridge.' },
          ],
        },
      ],
    },
    {
      id: 'habito',
      kicker: 'Volumetry',
      title: 'Bytes and frequencies before servers',
      visual: { scene: 'cost-volumetry', state: 'habit' },
      describe: '<p>The same table, with two groups highlighted. The catalog (500 to 700 kb, once a day) and the fridge stock updates (from 0.1 kb) keep the phone’s copy fresh without downloading it again. The review with a photo, about 4 MB, is by far the heaviest row.</p>',
      blocks: [
        { t: 'p', html: 'The habit worth copying for any project: size <strong>bytes and frequencies before choosing servers</strong>.' },
        { t: 'p', html: 'The table also justifies decisions you have already seen: the catalog is downloaded whole once a day and lives 24 hours on the device, kept fresh by small stock messages, instead of being fetched again on every screen.' },
        { t: 'p', html: 'And the 4 MB photo explains why reviews made it into the calculation: the raw spreadsheet shows they are, by far, the biggest consumer of traffic and storage.' },
      ],
    },

    /* ── the forecasts ── */
    {
      id: 'base-datos',
      kicker: 'The forecasts',
      title: 'About 4 GiB of database a month',
      visual: { scene: 'cost-forecast', state: 'db' },
      evidence: { src: '/img/database_forecast.png', alt: 'The team’s spreadsheet: data types and database size forecast', caption: 'The database forecast in the team’s spreadsheet: 3.96 GiB a month for 1,000 records a day (30,000 a month).' },
      describe: '<p>Monthly database growth for four volumes. 500 requests a day, 15,000 records a month: 1.98 GiB. 1,000 a day, 30,000 records: 3.96 GiB. 5,000 a day, 150,000 records: 19.80 GiB. 10,000 a day, 300,000 records: 39.61 GiB.</p>',
      blocks: [
        { t: 'p', html: 'With the table in hand, the spreadsheet projects four volumes: 500, 1,000, 5,000 and 10,000 requests a day.' },
        { t: 'p', html: 'In the projected scenario, 1,000 a day, about 30,000 records a month take <strong>3.96 GiB</strong> of database a month. Tiny figures, computed before choosing any machine.' },
        { t: 'p', html: 'Tap each column to read its volume.' },
      ],
    },
    {
      id: 'trafico',
      kicker: 'The forecasts',
      title: 'The hidden giant in the traffic',
      visual: { scene: 'cost-forecast', state: 'traffic' },
      evidence: { src: '/img/traffic_forecst.png', alt: 'The team’s spreadsheet: request payloads and monthly traffic forecast', caption: 'The traffic forecast in the team’s spreadsheet: 16.50 GiB a month at 1,000 requests a day, almost all of it review and complaint photos.' },
      describe: '<p>Monthly traffic next to database growth. 500 requests a day: 8.25 GiB. 1,000: 16.50 GiB. 5,000: 82.51 GiB. 10,000: 165.02 GiB. At 1,000 a day, 16.42 of the 16.50 GiB are photos attached to reviews and complaints.</p>',
      blocks: [
        { t: 'p', html: 'The traffic forecast uses the same four volumes. At 1,000 requests a day the system moves about <strong>16.5 GiB</strong> a month: four times its database growth.' },
        { t: 'p', html: 'The cause is not the business. The spreadsheet assumes 10% of users write reviews and 5% report a problem, each with a 4 MiB photo. Those photos are 16.4 of the 16.5 GiB.' },
        { t: 'p', html: 'Volumetry finds giants like this before they reach the bill.' },
      ],
    },
    {
      id: 'supuestos',
      kicker: 'The forecasts',
      title: 'An estimate you can argue with',
      visual: { scene: 'cost-assumptions' },
      describe: '<p>Three cards. Uniform traffic: the 3.96 GiB are the high end, reality could be up to 60% smaller. No compression: the 16.5 GiB are uncompressed, and GZIP would lower them significantly. Database sized for 12 months: a fixed 1 TB of DynamoDB costs $3,072 a year, almost the same as all the machines combined, $3,115.</p>',
      blocks: [
        { t: 'p', html: `The unpolished spreadsheet also leaves its assumptions in plain sight ${doc('assumptions')}, and that is a compliment, not a flaw.` },
        { t: 'p', html: 'It assumes <strong>uniform</strong> traffic (“in reality the number could be up to 60% smaller”), includes <strong>no compression</strong> (with GZIP it would drop significantly) and sizes the database for 12 months: a fixed 1 TB of DynamoDB at $3,072 a year, almost as much as all the machines ($3,115).' },
        { t: 'callout', tone: 'note', title: 'Why it matters', html: 'An estimate that shows its assumptions can be debated. One that hides them cannot.' },
      ],
    },

    /* ── the bill ── */
    {
      id: 'diez-veces',
      kicker: 'The bill',
      title: 'Ten times the load, how much more money?',
      visual: { scene: 'cost-totals' },
      describe: '<p>Year-1 total cost by scenario. Minimum: $12,248. Projected: $12,548, about $1,046 a month. Rapid growth, ten times the projected requests: $22,481, 1.8 times the projected bill. A dashed column shows what ten times the projected bill would be if cost grew in proportion to load: $125,482.</p>',
      blocks: [
        { t: 'p', html: 'The spreadsheet adds up every line for one year. Minimum: <strong>$12,248</strong>. Projected: <strong>$12,548</strong>, about $1,000 a month to run the whole business.' },
        {
          t: 'predict',
          question: 'The rapid scenario has ten times the projected requests. What happens to the yearly bill?',
          options: [
            { label: 'It grows about tenfold, to ~$125,000', feedback: 'That is what cost in proportion to load would look like. The spreadsheet says otherwise.' },
            { label: 'It grows about fivefold, to ~$63,000', feedback: 'Still far too high: many lines do not depend on the number of requests.' },
            { label: 'It stays at ~$12,500', feedback: 'Not quite: the machines, the file storage and the queues do grow.' },
            { label: 'It less than doubles, to ~$22,500', correct: true, feedback: '<strong>Right: $22,481.</strong> Ten times the load, 1.8 times the bill.' },
          ],
        },
      ],
    },
    {
      id: 'lineas',
      kicker: 'The bill',
      title: 'Where each dollar goes',
      visual: { scene: 'cost-bill', state: 'explore' },
      evidence: { src: '/img/1y-min-tco.png', alt: 'Three pie charts: the yearly cost distribution in the minimum, projected and rapid-growth scenarios', caption: 'The team’s three yearly bills as pie charts: minimum (in dollars), projected and rapid growth (in percentages).' },
      describe: '<p>Yearly cost per service, switchable by scenario. Minimum: DataDog $3,336, Tableau $1,440, DynamoDB $3,072, EC2 $3,115, Amazon MQ $508, SNS $366, S3 $262, Kafka $139, VPN $9; total $12,248. Projected: MQ $547 and S3 $525; total $12,548. Rapid: EC2 $6,230, Tableau $2,880, MQ $1,203 and S3 $5,245; total $22,481. Load balancer and outbound transfer are marked TBD.</p>',
      blocks: [
        { t: 'p', html: 'Switch between the three scenarios. The lines are the same; only a few of them grow.' },
        { t: 'p', html: 'In the rapid scenario the machines double (8 instances become 16), Tableau doubles and file storage in S3 grows twentyfold. The database, monitoring and notifications do not move: the database was already sized for a year.' },
        { t: 'p', html: 'That is why ten times the load did not cost ten times more: the cheap architecture absorbs the growth.' },
      ],
    },

    /* ── buy or build ── */
    {
      id: 'alquilado',
      kicker: 'Buy or build',
      title: 'The priciest line is not a server',
      visual: { scene: 'cost-bill', state: 'rented' },
      describe: '<p>The minimum bill with two lines highlighted: DataDog monitoring, $3,336 a year, and Tableau reporting, $1,440. Together they are 39% of the $12,248. The machines, EC2, cost $3,115.</p>',
      blocks: [
        { t: 'p', html: 'Look at the minimum bill again. The most expensive line is <strong>monitoring</strong> (DataDog, $3,336 a year), followed by <strong>reporting</strong> (Tableau, $1,440): together, about 40% of the budget.' },
        { t: 'p', html: 'Add DynamoDB and the services the team rents ($7,848) outweigh all the machines ($3,115).' },
        { t: 'p', html: 'So why pay for tools that have free, open-source alternatives?' },
      ],
    },
    {
      id: 'monitoreo',
      kicker: 'Buy or build',
      title: 'Free software, paid in developer hours',
      visual: { scene: 'cost-compare' },
      describe: '<p>Monitoring: DataDog, chosen, at $15 per host per month as a managed service; Grafana and the ELK stack, free and open source, rejected because they demand in-house maintenance. Reporting: Tableau, chosen, $1,440 a year in the table; Power BI, viable only with a Microsoft subscription; KoolReport, the third option. With open source, monitoring would have taken 0.2 to 0.5 of a developer.</p>',
      blocks: [
        { t: 'p', html: `Because the “free” option, standing up open-source tools on your own servers, costs the most expensive thing a small team has: developer hours. ${doc('adr-003', 'ADR 003')} puts it at 0.2 to 0.5 of a developer just to look after monitoring.` },
        { t: 'p', html: 'And it was not faith: they compared. Grafana and the ELK stack were rejected for demanding in-house maintenance; Tableau was weighed against Power BI and KoolReport.' },
        { t: 'decision', id: 'datadog' },
      ],
    },
    {
      id: 'privacidad',
      kicker: 'Buy or build',
      title: 'Same yardstick, opposite answer',
      visual: { scene: 'cost-privacy' },
      describe: '<p>Inside the Farmacy Food platform: the subscriber app sends reviews to the feedback module, built in-house, next to the health profiles (diabetes, celiac disease, diets). Outside, the ready-made third-party surveys appear crossed out, marked ADR 010, declined. The line from the health profiles toward them is cut at the platform boundary.</p>',
      blocks: [
        { t: 'p', html: 'With reviews and surveys, the “buy” option existed too: ready-made third-party web surveys. The team still rejected it.' },
        { t: 'p', html: `Farmacy Food handles nutritional and health profiles, and that data was not going to end up on third-party servers. ${doc('adr-010', 'ADR 010')} records the discarded idea, the reason, and what the in-house alternative costs.` },
        { t: 'decision', id: 'privacy' },
      ],
    },
    {
      id: 'leccion',
      kicker: 'Buy or build',
      title: 'The real price includes who maintains it',
      visual: { scene: 'cost-yardstick' },
      describe: '<p>Two cards. Monitoring: buying costs $15 per host per month with no maintenance; building means a free license plus 0.2 to 0.5 of a developer. Verdict: rent DataDog. Surveys: buying means health data on third-party servers; building means more in-house code with the data kept inside. Verdict: in-house feedback.</p>',
      blocks: [
        { t: 'p', html: 'Two decisions, one question: <strong>what does this really cost us?</strong> For monitoring, the free option cost developer hours, so they paid. For surveys, the paid option would have sent health data outside, so they built.' },
        { t: 'callout', tone: 'warn', title: 'The budget lesson', html: 'Comparing “free” against “paid” by looking only at the monthly bill is the classic mistake. A tool’s real cost includes whoever will maintain it. Sometimes paid software is the cheapest in the world.' },
      ],
    },

    /* ── checkpoint ── */
    {
      id: 'checkpoint',
      kicker: 'Checkpoint',
      title: 'Four questions before moving on',
      visual: {
        scene: 'quiz',
        props: {
          questions: [
            {
              q: 'What is volumetry?',
              options: [
                'Counting how many servers the system will need',
                'Measuring response times under peak load',
                'Noting the weight and frequency of every message, to derive traffic and storage',
                'Estimating how many users will sign up in a year',
              ],
              answer: 2,
              why: 'Weight times frequency, message by message. Bandwidth and storage follow, and costs stop being guesswork.',
            },
            {
              q: 'At 1,000 requests a day, why is traffic (16.5 GiB a month) four times the database growth (3.96 GiB)?',
              options: [
                'Review and complaint photos of about 4 MB each',
                'The full catalog is downloaded on every screen',
                'Order confirmations are sent several times',
                'The fridges send their stock every second',
              ],
              answer: 0,
              why: 'The photos are 16.4 of the 16.5 GiB. The heaviest message comes from a customer, not from the business.',
            },
            {
              q: 'The rapid scenario has ten times the requests. Why does the yearly bill less than double?',
              options: [
                'AWS gives large volume discounts',
                'The team dropped monitoring in that scenario',
                'Every photo is compressed with GZIP',
                'Many lines, like the database and monitoring, do not depend on traffic',
              ],
              answer: 3,
              why: 'Only machines, file storage, queues and reporting grow. The database was sized for a year from the start.',
            },
            {
              q: 'Why did the team pay for DataDog instead of running Grafana or ELK for free?',
              options: [
                'DataDog was the only tool that works on AWS',
                'The free tools would take 0.2 to 0.5 of a developer to maintain',
                'The client already paid for a DataDog license',
                'Open-source tools cannot send alerts',
              ],
              answer: 1,
              why: 'For a small team, developer hours are the most expensive resource. Paid software can be the cheapest option.',
            },
          ],
        },
      },
      blocks: [
        { t: 'p', html: 'Review the essentials before moving on.' },
        { t: 'p', html: 'You have now seen the case’s decisions one chapter at a time, each with its price. The next chapter puts them all on a single map: the ten structural decisions, grouped in three pillars.' },
      ],
    },
  ],
};
