// Builds timing.js (window.TIMING) and lays the film out in index.html: the scene slots and the voice clips.
//
//   node tools/timing.mjs           → with voice.json (tools/voice.mjs): the real voice; otherwise an estimate
//   node tools/timing.mjs estimate  → force the estimate (a calm simulated narrator)
//
// Every animation is anchored to a line or a word of the narration, so this re-times the whole video.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const here = (p) => new URL('../' + p, import.meta.url);
const N = JSON.parse(readFileSync(here('narration.json'), 'utf8'));
const VO = process.argv[2] !== 'estimate' && existsSync(here('voice.json')) ? JSON.parse(readFileSync(here('voice.json'), 'utf8')) : null;
const mode = VO ? 'voice' : 'estimated';

const LEAD_IN = 1.4, TAIL = 3.2, SCENE_GAP = 0.9; // silence before the first word, after the last, between scenes
const SCENE_LEAD = 0.7, XFADE = 0.7; // a scene arrives a little before its first line, and overlaps the previous one
const words = (s) => s.split(/\s+/).filter(Boolean);

/** Caption words keep the written form (digits); when the voice said something else (numbers in letters), map by position. */
function captionWords(text, said, offset) {
  const cw = words(text);
  if (cw.length === said.length) return cw.map((w, i) => ({ w, s: +(offset + said[i].s).toFixed(3), e: +(offset + said[i].e).toFixed(3) }));
  const sayLen = said.reduce((a, w) => a + w.w.length + 1, 0);
  const at = (f) => { let acc = 0; for (const w of said) { const n = w.w.length + 1; if (acc + n >= f * sayLen) return w.s + ((f * sayLen - acc) / n) * (w.e - w.s); acc += n; } return said.at(-1).e; };
  const len = cw.reduce((a, w) => a + w.length + 1, 0);
  let acc = 0;
  return cw.map((w) => { const s = at(acc / len), e = at((acc + w.length) / len); acc += w.length + 1; return { w, s: +(offset + s).toFixed(3), e: +(offset + e).toFixed(3) }; });
}

/** The simulated narrator: words spread at a calm pace, with pauses after punctuation. */
function estimateLine(text, say) {
  const CPS = 14.5, PAUSE = { ',': 0.2, ';': 0.3, ':': 0.32, '.': 0.42, '?': 0.45, '!': 0.42 };
  let t = 0;
  const said = words(say).map((w) => { const d = w.replace(/[^\p{L}\p{N}]/gu, '').length / CPS + 0.07; const o = { w, s: t, e: t + d }; t += d + (PAUSE[w.at(-1)] ?? 0.035); return o; });
  return said;
}

let t = LEAD_IN;
const clips = [];
const scenes = N.scenes.map((sc, si) => {
  if (si > 0) t += SCENE_GAP;
  const lines = [];
  if (VO) {
    const v = VO.scenes[sc.id];
    if (!v) throw new Error(`no voice for scene ${sc.id}: run tools/voice.mjs`);
    v.segments.forEach((seg, k) => {
      const start = +t.toFixed(3);
      clips.push({ id: `vo-${sc.id}-${k}`, file: seg.file, start, duration: seg.duration });
      for (let i = seg.first; i <= seg.last; i++) {
        const w = captionWords(sc.lines[i].text, v.lines[i].words, start - seg.from);
        lines[i] = { text: sc.lines[i].text, start: w[0].s, end: w.at(-1).e, words: w };
      }
      const last = sc.lines[seg.last];
      // a cut segment keeps its tail of silence and adds the scripted pause; the scene's last one ends at its last word
      t = k < v.segments.length - 1 ? start + seg.duration + (last.pauseAfter ?? 0) : lines[seg.last].end + (last.pauseAfter ?? 0);
    });
  } else {
    sc.lines.forEach((ln, i) => {
      const w = captionWords(ln.text, estimateLine(ln.text, ln.say ?? ln.text), t);
      lines[i] = { text: ln.text, start: w[0].s, end: w.at(-1).e, words: w };
      t = lines[i].end + 0.45 + (ln.pauseAfter ?? 0);
    });
    t -= 0.45;
  }
  return { id: sc.id, kicker: sc.kicker, lines };
});
const duration = +(t + TAIL).toFixed(2);
scenes.forEach((sc, i) => (sc.start = i === 0 ? 0 : +Math.max(0, sc.lines[0].start - SCENE_LEAD).toFixed(3)));
scenes.forEach((sc, i) => (sc.end = i === scenes.length - 1 ? duration : +(scenes[i + 1].start + XFADE).toFixed(3)));

writeFileSync(here('timing.js'), `/* generated by tools/timing.mjs from narration.json (${mode}) */\nwindow.TIMING = ${JSON.stringify({ duration, mode, scenes })};\n`);

// lay the film out: the root's length, the scene slots, the voice clips
let html = readFileSync(here('index.html'), 'utf8');
html = html.replace(/(id="root"[\s\S]*?data-duration=")[^"]*"/, `$1${duration}"`);
for (const id of ['chrome', 'captions']) html = html.replace(new RegExp(`(id="${id}"[^>]*?data-duration=")[^"]*"`), `$1${duration}"`);
const slots = scenes.map((sc) => `      <div id="el-${sc.id}" data-composition-id="${sc.id}" data-composition-src="compositions/${sc.id}.html" data-start="${sc.start}" data-duration="${+(sc.end - sc.start).toFixed(3)}" data-track-index="1" data-width="1920" data-height="1080"></div>`);
const voice = clips.map((c) => `      <audio id="${c.id}" src="${c.file}" data-start="${c.start}" data-duration="${c.duration}" data-track-index="10"></audio>`);
html = html.replace(/<!-- film -->[\s\S]*?<!-- \/film -->/, `<!-- film -->\n${[...slots, ...voice].join('\n')}\n      <!-- /film -->`);
writeFileSync(here('index.html'), html);

// what the voice says, one paragraph per scene (for reading it over, or for pasting into ElevenLabs by hand)
writeFileSync(here('narration.txt'), N.scenes.map((sc) => sc.lines.map((ln) => ln.say ?? ln.text).join(' ')).join('\n\n') + '\n');
console.log(`${scenes.length} scenes · ${scenes.reduce((a, s) => a + s.lines.length, 0)} lines · ${clips.length} voice clips · ${duration}s (${mode})`);
