// One-off: renders the Lucide icons the video uses into assets/icons.js (window.ICONS), so the composition needs no network.
// ZAItects course: one shared list for the eight chapters (KatArch's base set plus the course's own icons).
// A chapter can add names in tools/icons-extra.json ({ "key": "LucideName" }) without touching the shared list.
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import * as L from 'lucide-react';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
const names = {
  // KatArch base
  chef: 'ChefHat', fridge: 'Refrigerator', store: 'Store', user: 'User', userCheck: 'UserCheck', calendar: 'CalendarCheck',
  phone: 'Smartphone', server: 'Server', card: 'CreditCard', books: 'BookOpenCheck', truck: 'Truck', cpu: 'Cpu',
  packageX: 'PackageX', pin: 'MapPin', heart: 'HeartPulse', cash: 'Banknote', radio: 'Radio', lock: 'Lock',
  doc: 'ScrollText', trophy: 'Trophy', x: 'X', users: 'Users', clock: 'Clock', building: 'Building2', utensils: 'UtensilsCrossed',
  receipt: 'Receipt', book: 'BookOpen', inbox: 'Inbox', heart2: 'Heart', chart: 'BarChart3', db: 'Database', container: 'Container', check: 'Check', gavel: 'Gavel', network: 'Network', scale: 'Scale', ruler: 'Ruler', file: 'FileText', square: 'Square', sparkles: 'Sparkles', coins: 'Coins', hammer: 'Hammer', listChecks: 'ListChecks', flag: 'Flag', help: 'CircleHelp', brain: 'Brain', activity: 'Activity', mail: 'Mail', boxes: 'Boxes', box: 'Box', target: 'Target', calendarDays: 'CalendarDays', glossary: 'BookA', shieldAlert: 'ShieldAlert', notebook: 'NotebookPen', key: 'KeyRound', arrowRight: 'ArrowRight', pencil: 'PenLine', search: 'Search', thumbsDown: 'ThumbsDown', eyeOff: 'EyeOff', pause: 'Pause', apple: 'Apple', wheat: 'Wheat', stethoscope: 'Stethoscope', terminal: 'MonitorSmartphone', cloudRain: 'CloudRain', gauge: 'Gauge', map: 'Map', wifiOff: 'WifiOff', message: 'MessageSquare', rotate: 'RotateCw', camera: 'Camera', compass: 'Compass', git: 'GitBranch', swords: 'Swords', route: 'Route', alert: 'TriangleAlert',
  // ZAItects course
  bot: 'Bot', award: 'Award', badge: 'BadgeCheck', grad: 'GraduationCap', globe: 'Globe', landmark: 'Landmark', stamp: 'Stamp',
  hourglass: 'Hourglass', timer: 'Timer', folder: 'Folder', folderOpen: 'FolderOpen', files: 'Files', fileCheck: 'FileCheck', fileX: 'FileX', fileQ: 'FileQuestion',
  clipboard: 'ClipboardCheck', shield: 'Shield', shieldCheck: 'ShieldCheck', filter: 'Filter', layers: 'Layers', puzzle: 'Puzzle', wrench: 'Wrench',
  image: 'Image', lightbulb: 'Lightbulb', repeat: 'Repeat', refresh: 'RefreshCw', undo: 'Undo2', copy: 'Copy', scissors: 'Scissors', workflow: 'Workflow',
  zap: 'Zap', ban: 'Ban', link: 'Link', split: 'Split', merge: 'Merge', sliders: 'SlidersHorizontal', toggle: 'ToggleRight', flask: 'FlaskConical',
  microscope: 'Microscope', quote: 'Quote', star: 'Star', sticky: 'StickyNote', eye: 'Eye', door: 'DoorOpen', calculator: 'Calculator',
  trending: 'TrendingUp', commit: 'GitCommitHorizontal', dollar: 'DollarSign', percent: 'Percent', cloud: 'Cloud', globeLock: 'Globe2', laptop: 'Laptop',
  monitor: 'Monitor', listTodo: 'ListTodo', list: 'List', pen: 'Pen', penOff: 'PenOff', bookmark: 'Bookmark', archive: 'Archive', history: 'History',
  medal: 'Medal', thumbsUp: 'ThumbsUp', scan: 'ScanSearch', binoculars: 'Binoculars', circleCheck: 'CircleCheck', circleX: 'CircleX', infinity: 'Infinity',
  rocket: 'Rocket', mountain: 'Mountain', sprout: 'Sprout', handshake: 'Handshake', userX: 'UserX', userPlus: 'UserPlus', userCog: 'UserCog',
  cog: 'Cog', hash: 'Hash', type: 'Type', textSearch: 'TextSearch', messageQ: 'MessageCircleQuestion', bug: 'Bug', siren: 'Siren', unlock: 'LockOpen',
  plug: 'Plug', cable: 'Cable', send: 'Send', download: 'Download', upload: 'Upload', layout: 'LayoutGrid', github: 'FolderGit2', pin2: 'Pin',
  arrowLeft: 'ArrowLeft', arrowDown: 'ArrowDown', arrowUp: 'ArrowUp', minus: 'Minus', plus: 'Plus', equal: 'Equal', divide: 'Divide',
  briefcase: 'Briefcase', fingerprint: 'Fingerprint', robot: 'BotMessageSquare', languages: 'Languages', telescope: 'Telescope', dice: 'Dices',
};
const extra = new URL('./icons-extra.json', import.meta.url);
if (existsSync(extra)) Object.assign(names, JSON.parse(readFileSync(extra, 'utf8')));
const out = {};
for (const [k, n] of Object.entries(names)) {
  if (!L[n]) throw new Error('missing icon ' + n);
  out[k] = renderToStaticMarkup(createElement(L[n], { size: 24, strokeWidth: 1.75, color: 'currentColor' })).replace(/ class="[^"]*"/, '');
}
writeFileSync(new URL('../assets/icons.js', import.meta.url), '/* generated by tools/icons.mjs (Lucide, ISC) */\nwindow.ICONS = ' + JSON.stringify(out, null, 0) + ';\n');
console.log(Object.keys(out).length, 'icons');
