# Conceptos clave y dónde se trabajan: {escena: "all" | [índices de línea]}
KEYS = {
 1: [("El recorrido de ClearView (historia anónima, match, desbloqueo, medición)", {"clearview": "all", "outro": [0]}),
     ("Los huecos del pliego", {"huecos": [0, 1, 2, 3, 5], "outro": [1]}),
     ("ADR", {"storming": [1, 2]}),
     ("Event storming (técnica, evento, actor, comando, dudas)", {"storming": [3, 4, 5, 6, 7], "mesa": "all", "piensalo": [0, 1], "outro": [2]}),
     ("Historia legible frente a números comparables", {"piensalo": [2, 3, 4, 5], "outro": [3]})],
 2: [("Característica de arquitectura", {"que": "all", "outro": [0]}),
     ("Factibilidad (y su sustitución por costo y simplicidad)", {"top3": [1, 2], "piensalo": [2, 3, 4, 5], "outro": [1, 2]}),
     ("Interoperabilidad", {"top3": [3, 4, 5]}),
     ("Testabilidad y determinismo", {"top3": [6, 7]}),
     ("Estilo: service-based + event-driven (y microkernel descartado)", {"piensalo": [0, 1], "estilo": "all", "outro": [3]}),
     ("Elegir temprano con criterio escrito", {"historial": "all"})],
 3: [("Requisitos, supuestos, códigos estables y trazabilidad", {"lista": "all", "supuestos": [6], "outro": [0]}),
     ("Suponer un número con fuente (A17)", {"numero": "all", "outro": [1]}),
     ("La contradicción A9/A10 y «la menor IA posible»", {"nota": "all", "supuestos": [5], "outro": [2]}),
     ("Prompt, token y costo", {"respuestas": [0, 1, 2], "piensalo": "all"}),
     ("Temperatura (determinismo)", {"respuestas": [3, 4, 5]}),
     ("Rate limit y demora (vuelven en los capítulos 4, 7 y 8)", {"respuestas": [6, 7, 8]}),
     ("De la entrevista a supuestos y requisitos (Q14, Q15)", {"supuestos": [0, 1, 2, 3, 4, 5]})],
 4: [("Separar el modelo en su contenedor (ADR-006)", {"primera": "all"}),
     ("Tres caminos y la elección de alquilar (ADR-007)", {"tres": "all", "piensalo": "all", "decision": [0, 1, 2], "outro": [1]}),
     ("Estado «reemplazado»", {"decision": [3, 4, 5, 6], "outro": [2]}),
     ("Estimar el costo de una historia (A24)", {"precio": "all", "outro": [3]}),
     ("El precio de alquilar y los clientes por mensajes", {"costo": [0, 1, 2, 3, 4]})],
 5: [("Escala supuesta: fallar es lo normal", {"cuenta": "all", "outro": [0]}),
     ("Sincrónico frente a asíncrono", {"asincronia": "all"}),
     ("Evento publicado, cola y tema", {"eventos": "all", "outro": [1]}),
     ("Adaptador por sistema", {"adaptadores": [0, 2, 4, 5, 6], "outro": [2]}),
     ("Dead-letter queue y backoff exponencial", {"dlq": "all", "outro": [3]}),
     ("Un ADR rechazado (cache)", {"piensalo": "all"})],
 6: [("Características desde la historia, con permisos (ADR-010)", {"regla": "all", "outro": [0]}),
     ("Vectorial frente a legible", {"piezas": "all", "decision": [2]}),
     ("Los seis caminos", {"caminos": "all", "piensalo": "all", "decision": [0, 1]}),
     ("Contar prompts: n + m frente a n × m", {"contar": [1, 2, 3, 4, 5], "decision": [0, 1], "numeros": [0, 1, 2, 3, 4], "outro": [1]}),
     ("Matching determinista (opción B)", {"decision": [3, 4, 5], "outro": [2]}),
     ("El precio de B", {"precio": "all", "outro": [3]}),
     ("Contrapunto del podio", {"podio": "all"})],
 7: [("Lo lento en segundo plano (ADR-008)", {"camino": "all", "outro": [0]}),
     ("Servicio propio para la historia (ADR-009)", {"muro": "all", "outro": [1]}),
     ("Probar lo no determinista: conjuntos y tramos (ADR-025)", {"problema": "all", "conjuntos": "all", "outro": [2]}),
     ("Regresión sin el proveedor: adaptadores y dobles", {"doble": "all"}),
     ("Lo que no se automatiza y el costo de probar", {"piensalo": "all", "outro": [3]}),
     ("Cambiar de modelo como procedimiento", {"cambio": "all"})],
 8: [("La tesis de ahorro", {"tesis": "all", "cierre": [0]}),
     ("Base compartida con dueño único (ADR-014/015)", {"base": "all"}),
     ("Reportes por lotes fuera del camino del usuario", {"reportes": "all"}),
     ("Encuestas alquiladas", {"encuestas": "all"}),
     ("Lo no hecho, a la vista", {"no": "all"}),
     ("El método completo", {"cierre": [1, 2, 3, 4, 5, 6, 7, 8]})],
}
