# Capítulos 5 a 8 (usa L y A de part1).

CH5 = {
 "n": 5, "title": "Miles de puertas",
 "ideas": [
  "La escala supuesta: unos 100 sistemas de RR. HH., 100.000 empresas, hasta 200.000 configuraciones (A29–A31, Q16). Con tantos sistemas ajenos, fallar es lo normal.",
  "No esperar: a lo externo se le envía de forma asíncrona (ADR-005, del primer día), y cada cambio de estado de un match se publica como evento (ADR-016).",
  "Un servicio de integración con orquestador, un adaptador por sistema y un almacén de secretos. Los adaptadores nuevos los escribe el equipo de ClearView (por eso se descartó la configurabilidad).",
  "Lo fallido espera en una dead-letter queue con backoff exponencial (ADR-023). Y la copia en memoria se rechaza por escrito (ADR-024): un ADR rechazado también enseña.",
 ],
 "anchors": [
  "`Requirements/requirements-and-assumptions.md`: A29–A31, Q16 (`72923e5`); esqueleto ADR-023 con «around 10'000 employers» (`4923a1c`).",
  "`ADR/ADR-005-async-with-external-systems.md` (`246c55e`, 23/09).",
  "`ADR/ADR-016-matches-published-as-events.md`.",
  "`C4/C3-components-hr-integration.md` y su diagrama (`af4443a`, 28/09: el primer C3 del repositorio).",
  "`ADR/ADR-023-adapters-for-hr-systems.md` (título: «Dead-letter queue for HR systems») y `ADR/ADR-024-caching-of-resumes.md` (*Denied*).",
 ],
 "learn": [
  "Dimensionar una integración a partir de supuestos y sacar la conclusión correcta (diseñar para la falla).",
  "Explicar la diferencia entre comunicación sincrónica y asíncrona, y qué es una cola de eventos.",
  "Diseñar reintentos con una dead-letter queue y backoff exponencial.",
  "Escribir un ADR que rechaza una optimización y dice cuándo revisarla.",
 ],
 "cut": [
  "El caso de empresas sin sistema de RR. HH. (R27: envío por correo o enlace de descarga).",
  "Los hilos concurrentes de los adaptadores y el detalle de la base documental de configuraciones.",
  "Billing como consumidor del mismo evento (se ve en pantalla, la voz lo nombra en una frase).",
 ],
 "questions": [
  "«¿De dónde salen 200.000?» Se muestra la multiplicación de los supuestos, y se dice honestamente que el repositorio no explica el salto de 10.000 a 100.000.",
  "«¿Sincrónico, asíncrono?» Con la analogía llamada / mensaje, que ya usa el curso.",
  "«¿Cola? ¿Tema? ¿Publicar?» Se definen como buzón entre programas, con quién escucha qué.",
  "«¿Adaptador?» Se define por lo que hace: traduce el idioma de un solo sistema ajeno.",
  "«¿Dead-letter queue? ¿Backoff exponencial?» Cada uno con su definición y un ejemplo numérico marcado como ejemplo.",
  "«¿Por qué no cachear?» Se da como piénsalo, y la respuesta trae las dos razones del ADR.",
 ],
 "scenes": [
  {"id": "intro", "kicker": "Capítulo 5",
   "visual": "El recorrido del capítulo 1; zoom al último tramo: candado abierto → currículum que viaja a un sistema de RR. HH. El tramo se multiplica en muchas puertas de colores. Título.",
   "lines": [
    L("¿Recuerdas el final del recorrido del capítulo 1? La empresa paga, y el currículum viaja a su sistema de recursos humanos."),
    L("Parece un paso menor. Pero fue lo primero que el equipo dibujó en detalle.", p=0.6),
    L("Capítulo 5: miles de puertas."),
   ],
   "audit": A([("Puente", [0, 1])], "—", "—", "—", "Sí", "Bien")},
  {"id": "cuenta", "kicker": "La cuenta",
   "visual": "Los 11 logos de ejemplo del pliego. Después, tres supuestos que se multiplican: A29 «~100 sistemas», A30 «100.000 empresas», A31 «× 2 = hasta 200.000 configuraciones». Una nota tachada «10.000» (esqueleto del 26/09) reemplazada por «100.000» (29/09), con la etiqueta «sin motivo escrito». Al final, un tablero con luces: siempre hay alguna roja.",
   "lines": [
    L("El pliego nombra once sistemas de recursos humanos, y aclara que son ejemplos. El equipo supuso cuántos habría en la práctica."),
    L("Supuesto A29: unos cien sistemas distintos. A30: unas 100.000 empresas de tecnología que podrían usar ClearView.", say="Supuesto A veintinueve: unos cien sistemas distintos. A treinta: unas cien mil empresas de tecnología que podrían usar ClearView."),
    L("A31: si cada una tiene, en promedio, dos sistemas, son hasta 200.000 configuraciones.", say="A treinta y uno: si cada una tiene, en promedio, dos sistemas, son hasta doscientas mil configuraciones.", p=0.8),
    L("Un detalle del historial: en la sesión del jueves, la nota decía diez mil empresas. Tres días después, cien mil. El repositorio no dice por qué."),
    L("Pero cualquiera de las dos cifras lleva a la misma conclusión: con tantos sistemas ajenos, algo va a fallar todos los días.", p=1),
    L("No es un riesgo. Es lo normal. La pregunta deja de ser cómo evitar las fallas, y pasa a ser cómo vivir con ellas."),
   ],
   "audit": A([("La escala supuesta (A29–A31)", [0, 1, 2]), ("El cambio sin motivo (honestidad)", [3]), ("Fallar es lo normal", [4, 5])],
              "Sí: los números antes de la conclusión", "—", "Sí: miles de sistemas ajenos fallan", "Sí: la multiplicación queda armada", "Bien")},
  {"id": "asincronia", "kicker": "No esperar",
   "visual": "ADR-005 con su fecha (23/09, el primer día). Dos escenas lado a lado: una llamada (teléfono, reloj de arena, pantalla congelada) y un mensaje (sobre en un buzón, la persona sigue con lo suyo). Debajo, la consecuencia escrita del ADR: «hace falta un mecanismo de reintento».",
   "lines": [
    L("La primera respuesta es del primer día, el ADR 005: a los sistemas externos se les envía de forma asíncrona."),
    L("Sincrónico es como una llamada: pides algo, y esperas en línea la respuesta. Asíncrono es como un mensaje: lo dejas, y sigues con lo tuyo."),
    L("Si el sistema de una empresa está caído, ningún proceso de ClearView se queda trabado esperándolo.", p=1),
    L("El precio quedó escrito en el mismo ADR: hace falta un mecanismo para reintentar."),
   ],
   "audit": A([("Sincrónico frente a asíncrono", [0, 1, 2]), ("El precio: reintentar", [3])],
              "Sí: viene de «fallar es lo normal»", "Sí, con analogía", "Sí: un sistema caído no bloquea", "Sí", "Bien")},
  {"id": "eventos", "kicker": "El aviso",
   "visual": "Un match cambia de estado a «desbloqueado» y deja un mensaje en un buzón con el rótulo «tema de matches». Tres servicios lo escuchan: integración (recoge los desbloqueos), cobro (también), análisis (lee todo). El servicio que publica no tiene flechas hacia ellos. Uno de los oyentes se pone rojo; los otros siguen en verde.",
   "lines": [
    L("¿Y cómo se entera el servicio de integración de que la empresa desbloqueó un match?"),
    L("ADR 016: cada cambio de estado de un match se publica como evento, en una cola."),
    L("Una cola es un buzón entre programas: uno deja mensajes, y otros los retiran. Aquí es un topic, un tema de matches: varios servicios escuchan el mismo buzón."),
    L("Integración escucha los desbloqueos. Cobro, también. Y el análisis de datos lo lee todo."),
    L("Quien publica no sabe quién escucha. Si uno de ellos falla, los demás siguen.", p=1),
    L("¿Recuerdas el estilo dirigido por eventos del capítulo 2, solo donde haga falta? Este es el lugar."),
   ],
   "audit": A([("Evento publicado (ADR-016)", [0, 1]), ("Cola y tema", [2, 3]), ("Desacople y su porqué", [4, 5])],
              "Sí: la pregunta concreta antes del mecanismo", "Sí", "Sí: si uno falla, los demás siguen", "Sí: los tres oyentes quedan en pantalla", "Bien")},
  {"id": "adaptadores", "kicker": "Una puerta por sistema",
   "visual": "El C3 de HR Integration redibujado, pieza por pieza: suscriptor al tema → orquestador → adaptadores (uno por sistema, con logos genéricos) → sistemas externos; abajo, una base de configuraciones y un almacén de secretos con una llave. Después, una empresa intenta agregar un sistema no soportado y aparece un candado: «lo agrega el equipo de ClearView, en una versión nueva». Al final, «100 adaptadores ≠ 200.000 programas».",
   "lines": [
    L("Adentro del servicio de integración, el diagrama muestra tres piezas."),
    L("Un orquestador: recibe el desbloqueo, busca qué sistemas configuró esa empresa, y pide el currículum."),
    L("Un adaptador por cada sistema de recursos humanos. Un adaptador traduce: habla el idioma de un solo sistema ajeno, para que el resto no tenga que hacerlo."),
    L("Y un almacén de secretos para las credenciales de cada empresa, separado de los datos comunes.", p=1),
    L("Una regla: una empresa no puede agregar un sistema que no esté soportado. Cada adaptador nuevo lo escribe el equipo de ClearView, y llega en una versión nueva."),
    L("¿Recuerdas la configurabilidad que dejaron afuera en el capítulo 2? Esta es la razón."),
    L("Cien sistemas, cien adaptadores. Pero 200.000 configuraciones no son 200.000 programas.", say="Cien sistemas, cien adaptadores. Pero doscientas mil configuraciones no son doscientos mil programas.", p=1),
   ],
   "audit": A([("Orquestador", [1]), ("Adaptador", [2]), ("Almacén de secretos", [3]), ("Adaptadores por versión (configurabilidad)", [4, 5]), ("Síntesis", [6])],
              "Sí: el desbloqueo que llega por el tema", "Sí: adaptador por lo que hace", "Sí: secretos aparte; configurabilidad atada al capítulo 2", "Sí: el C3 se arma pieza por pieza", "Bien (orquestador y secretos son detalle: una frase cada uno)")},
  {"id": "dlq", "kicker": "La cola de los fallidos",
   "visual": "Un envío que falla cae a una cola aparte, rotulada «dead-letter queue». Un reloj procesa la cola periódicamente. Ejemplo (rotulado «ejemplo»): reintentos a 1, 2, 4 y 8 minutos, en una línea de tiempo que se estira. Un sistema caído todo el día recibe pocos intentos espaciados. Al final, el pedido sube a colas de reintento más espaciadas.",
   "lines": [
    L("Falta lo más importante: ¿qué pasa cuando un envío falla?"),
    L("ADR 023: el envío fallido va a una cola aparte, la dead-letter queue, o cola de mensajes muertos."),
    L("Es donde esperan los mensajes que no se pudieron entregar, en lugar de perderse. Cada cierto tiempo, se procesa, y se reintenta.", p=0.8),
    L("Pero no a ciegas: con backoff exponencial. Cada espera es más larga que la anterior. Por ejemplo, el doble: un minuto, dos, cuatro, ocho."),
    L("Así, un sistema caído todo un día no recibe miles de intentos inútiles.", p=1),
    L("Y si sigue fallando, el pedido pasa a colas de reintento todavía más espaciadas, hasta que se deja de intentar."),
    L("Una falla deja de ser una emergencia, y pasa a ser una espera."),
   ],
   "audit": A([("Dead-letter queue", [1, 2]), ("Backoff exponencial", [3, 4]), ("Escalamiento de reintentos", [5]), ("Síntesis", [6])],
              "Sí: la pregunta concreta antes del nombre", "Sí, ambos; el ejemplo numérico se marca como ejemplo", "Sí: no saturar un sistema caído", "Sí: la línea de tiempo queda ~8 s", "Bien")},
  {"id": "piensalo", "kicker": "Piénsalo tú",
   "visual": "En cada reintento, una flecha vuelve a pedir el currículum al servicio de candidatos. Aparece la idea: una copia en memoria junto al orquestador. Anillo de 3 s. Después, el ADR-024 con el sello «Denied» y sus dos razones; al pie, la condición para revisarlo.",
   "lines": [
    L("Un detalle más. En cada reintento, el orquestador vuelve a pedirle el currículum al servicio de candidatos."),
    L("Piénsalo tú: ¿guardarías una copia del currículum en memoria, para no pedirlo cada vez?", p=3),
    L("El equipo lo pensó, en el ADR 024, y dijo que no."),
    L("Si el sistema de la empresa está caído, la entrega ya no es urgente: basta con reintentar más espaciado."),
    L("Y una copia en memoria tiene costo: la memoria es cara, y hay que saber cuándo la copia quedó vieja.", p=0.8),
    L("Prefirieron la carga a la memoria. Y dejaron escrito cuándo revisarlo: si el servicio de candidatos se vuelve un cuello de botella.", p=1),
    L("Un ADR rechazado también sirve: evita que alguien proponga lo mismo sin conocer el motivo."),
   ],
   "audit": A([("Aplicar: una optimización tentadora", [0, 1]), ("El rechazo y sus razones", [2, 3, 4, 5]), ("El valor de un ADR rechazado", [6])],
              "Sí: después de ver los reintentos", "Cache se explica por lo que hace (copia en memoria)", "Sí: urgencia, costo de memoria e invalidación", "Sí: el sello y las razones quedan ~12 s", "Bien")},
  {"id": "outro", "kicker": "Para llevarte",
   "visual": "Cuatro tarjetas: el tablero con luces rojas; el buzón del tema de matches; el C3 con los adaptadores; la línea de reintentos espaciados. Avance: una historia y un puesto frente a frente, con un signo de pregunta entre ellos.",
   "lines": [
    L("Repasemos. Con hasta 200.000 configuraciones, las fallas son lo normal.", say="Repasemos. Con hasta doscientas mil configuraciones, las fallas son lo normal."),
    L("A lo externo se le habla de forma asíncrona, y los matches se publican como eventos."),
    L("Un adaptador por sistema, escrito por el equipo, y los secretos aparte."),
    L("Lo fallido espera en una cola de mensajes muertos, con reintentos cada vez más espaciados.", p=1),
    L("Con las puertas resueltas, quedaba el corazón del producto: quién decide si una historia y un puesto encajan. Capítulo 6: dónde decide la IA."),
   ],
   "audit": A([("Repaso", [0, 1, 2, 3]), ("Avance", [4])], "—", "—", "—", "Sí", "Bien")},
 ],
}

CH6 = {
 "n": 6, "title": "Dónde decide la IA",
 "ideas": [
  "Primera regla: las características se sacan de la historia, nunca del currículum (ADR-010), y lo hace cumplir un permiso, no una promesa.",
  "Seis caminos para decidir un match (ADR-011), entendidos con dos piezas: características vectoriales (ilegibles) y características legibles (ejes definidos por especialistas).",
  "El criterio que los separa: contar prompts. n + m frente a n × m. Solo A y B son lineales; con los números del capítulo 3, la diferencia es enorme (cuenta nuestra, declarada como tal).",
  "La decisión B: la IA extrae características legibles una vez por historia y por puesto; el puntaje es una fórmula fija. Su precio: definir esas características, que quedó abierto. Contrapunto del podio.",
 ],
 "anchors": [
  "`ADR/ADR-010-create-features-from-story-not-resumes.md` (esqueleto `4923a1c`, texto `72923e5`).",
  "`ADR/ADR-011-deterministic-matching.md`: dos versiones el 29/09 (`7f015e4` y `72923e5`), fusión `86c346e`; diagrama `ADR/images/ADR-011-matching-process.png` (`0f2599c`).",
  "Semillas: nota rosada del tablero (capítulo 1), «A9 y A10…» y «use as little AI as necessary» (`cad0b4f`), «complejidad cuadrática» en `Characteristics.md` (`c277932`).",
  "Glosario: *Features* (relacionadas con *embeddings*) y *Human-readable features* (definidas por profesionales de RR. HH.).",
  "Corrección del C3 de matching el 15/10 (`3641df8`). *Known limitations* del README.",
  "Podio: `Katamarans/ADR/ADR-011-matching-engine-solution.md`; `Ctrl-Alt-Elite/README.md` (Vector Database, re-ranker).",
 ],
 "learn": [
  "Comparar alternativas de diseño con IA contando llamadas al modelo en función del tamaño de los datos.",
  "Explicar la diferencia entre un vector de características y unas características legibles, y qué se gana con cada una.",
  "Separar en un diseño lo que hace la IA (traducir) de lo que decide una regla fija (puntuar).",
 ],
 "cut": [
  "La notación O(n+m): se dice «n más m» y «n por m» sin notación.",
  "La opción F en detalle (características por puesto): una frase.",
  "Las definiciones del ADR (Resume, Story, Features, Spyder, Score) como lista: se usan en contexto.",
  "El nombre «Spyder» del equipo: se dice «gráfico de araña».",
 ],
 "questions": [
  "«¿Por qué la IA no puede ver el currículum, si va a anonimizarlo?» Se responde con A8: los modelos traen sesgos; solo el servicio de historia trata el currículum (capítulo 7).",
  "«¿Qué es un vector? ¿Y características legibles?» Dos líneas propias antes de las opciones, cada una con quién puede leerla.",
  "«¿Seis opciones de golpe?» Se agrupan: C cae por la regla; el resto se separa con dos preguntas (cuántos prompts, quién entiende el resultado). En pantalla, el diagrama real queda fijo.",
  "«¿n y m?» Se define con historias y puestos, y se ata a la palabra «cuadrática» del capítulo 2.",
  "«¿De dónde salen 600 millones?» Se dice que es una cuenta nuestra con su supuesto A17, y se da el límite que el propio ADR anota (prefiltrado).",
  "«¿Entonces la IA no decide nada?» Se dice exactamente: traduce texto a números revisables; la fórmula decide.",
 ],
 "scenes": [
  {"id": "intro", "kicker": "Capítulo 6",
   "visual": "Tres recortes del pasado que se juntan: la nota rosada «Human readable?» (capítulo 1), la palabra «cuadrática» (capítulo 2) y la nota «usar la menor IA posible» (capítulo 3). Fecha: domingo 29/09. Título.",
   "lines": [
    L("¿Recuerdas la nota rosada del capítulo 1: la historia, ¿es legible por humanos? ¿Y la del capítulo 3: usar la menor IA posible?"),
    L("El domingo 29, las dos se encontraron.", say="El domingo veintinueve, las dos se encontraron.", p=0.6),
    L("Capítulo 6: dónde decide la IA."),
   ],
   "audit": A([("Puente", [0, 1])], "—", "—", "—", "Sí", "Bien")},
  {"id": "regla", "kicker": "Primera regla",
   "visual": "Un currículum y una historia. Una flecha del currículum hacia «matching» se tacha. Un LLM con una mochila rotulada «sesgos del texto de entrenamiento». Después, dos servicios con candado: el currículum vive en «candidatos»; «matching» intenta leerlo y un permiso lo bloquea.",
   "lines": [
    L("Antes de elegir cómo comparar, el equipo fijó qué se compara. ADR 010: las características se sacan de la historia, nunca del currículum."),
    L("La razón está en sus supuestos: los modelos de lenguaje traen sesgos de los textos con que se entrenaron. Justo los que ClearView quiere eliminar."),
    L("Si el modelo ve datos personales, puede usarlos, aunque nadie se lo pida.", p=1),
    L("Y no lo dejaron como una buena intención: el currículum vive solo en el servicio de candidatos, y el de matching no tiene permiso para leerlo."),
    L("Una regla que la arquitectura hace cumplir vale más que una que depende de la memoria de alguien.", p=1),
   ],
   "audit": A([("Características desde la historia (ADR-010)", [0, 1, 2]), ("Hacerlo cumplir con permisos", [3, 4])],
              "Sí: el riesgo del sesgo antes de la regla", "—", "Sí: A8, los modelos traen sesgos", "Sí", "Bien")},
  {"id": "piezas", "kicker": "Dos piezas",
   "visual": "Una historia entra a una IA y sale una tira larga de números (vector), con una persona confundida al lado. Después, la misma historia sale como un gráfico de araña con pocos ejes rotulados genéricamente («eje 1…eje 5») y una persona que asiente; rótulo «ejes definidos por especialistas de RR. HH.». Los dos quedan lado a lado: «vectorial / legible».",
   "lines": [
    L("Para entender los caminos que el equipo dibujó, hacen falta dos piezas."),
    L("La primera: características vectoriales. Una IA convierte un texto en una lista larga de números, un vector, que sirve para medir parecidos."),
    L("Para la máquina funciona muy bien. Pero ninguna persona puede leerlo.", p=0.8),
    L("La segunda: características legibles. Unos pocos ejes, definidos por especialistas en recursos humanos, con un valor en cada uno."),
    L("Se dibujan como un gráfico de araña, y una persona entiende qué está mirando.", p=1),
   ],
   "audit": A([("Características vectoriales", [1, 2]), ("Características legibles", [3, 4])],
              "Sí: la nota «¿legible por humanos?» ya planteó la tensión", "Sí, ambas, con quién puede leerlas", "Sí: legible = revisable", "Sí: las dos imágenes quedan lado a lado", "Bien")},
  {"id": "caminos", "kicker": "Seis caminos",
   "visual": "El diagrama real de ADR-011 redibujado, fila por fila, A a F. Cada fila se ilumina cuando la voz la nombra: A (vectores + cálculo fijo), B (legibles + cálculo fijo), C (currículum y puesto directo a la IA, tachado), D (historia y puesto a la IA), E (legibles, pero puntúa la IA), F (características por puesto). Las filas que puntúa la IA llevan un ícono de IA en el centro; las de cálculo fijo, un ícono de fórmula.",
   "lines": [
    L("Con esas dos piezas, el equipo dibujó seis caminos."),
    L("En A, la IA saca vectores de la historia y del puesto, y una cuenta fija los compara. B es igual, pero con características legibles."),
    L("En C, la IA lee el currículum y el puesto, y pone el puntaje. Cayó enseguida: rompe la regla del ADR 010."),
    L("En D, la IA lee la historia y el puesto, y decide si encajan."),
    L("En E, saca características legibles, pero el puntaje lo pone otra vez la IA."),
    L("Y en F, cada puesto elige sus propias características, y la IA evalúa cada historia según las de ese puesto.", p=1),
   ],
   "audit": A([("A y B (cálculo fijo)", [1]), ("C (descartada por la regla)", [2]), ("D, E y F (la IA juzga)", [3, 4, 5])],
              "Sí: las piezas y la regla ya están dadas", "—", "C sí; el resto se resuelve con el criterio de la escena siguiente", "Sí: el diagrama real queda fijo y se ilumina por filas", "Aceptable: seis opciones en ~37 s; se compensa porque el criterio y el piénsalo las vuelven a recorrer (~75 s más)")},
  {"id": "contar", "kicker": "Contar prompts",
   "visual": "Q14 en una tarjeta. Después, n historias en una columna y m puestos en otra. Modo «una vez por elemento»: un rayo de IA por cada historia y cada puesto (n + m). Modo «una vez por par»: una grilla n × m que se llena de rayos. Primero con 3 y 3 (6 frente a 9), después con números grandes, donde la grilla desborda la pantalla. Rótulo: «cuadrática» (la palabra del capítulo 2).",
   "lines": [
    L("Para elegir, el equipo usó dos criterios. El primero ya lo conoces: Q14, poder probar que un cambio de modelo no empeora los matches."),
    L("El segundo es nuevo: contar cuántos prompts exige cada camino."),
    L("Imagina n historias y m puestos. Si la IA trabaja una vez sobre cada historia y una vez sobre cada puesto, son n más m prompts."),
    L("Si tiene que mirar cada par, historia contra puesto, son n por m.", p=1),
    L("Con tres historias y tres puestos casi da igual: seis prompts contra nueve. Con miles, ya no."),
    L("¿Recuerdas la palabra del capítulo 2, cuadrática? Es esta: n por m.", p=1),
   ],
   "audit": A([("Q14 como criterio", [0]), ("Contar prompts: n + m frente a n × m", [1, 2, 3, 4, 5])],
              "Sí: el ejemplo chico antes de la generalización", "Sí: n y m", "Sí: los prompts se pagan (capítulo 4)", "Sí: la grilla crece al ritmo de la voz", "Bien")},
  {"id": "piensalo", "kicker": "Piénsalo tú",
   "visual": "El diagrama de los seis caminos, a la izquierda; a la derecha, dos preguntas: «¿n + m prompts?» y «¿una persona entiende por qué hubo match?». Anillo de 3 s.",
   "lines": [
    L("Piénsalo tú. De los seis caminos, ¿cuáles cuestan n más m prompts? ¿Y cuál deja que una persona entienda por qué hubo match?", p=3),
   ],
   "audit": A([("Aplicar los dos criterios a las seis opciones", [0])],
              "Sí: después de las piezas, las opciones y el criterio", "—", "—", "Sí: el diagrama sigue visible", "Bien")},
  {"id": "decision", "kicker": "La opción B",
   "visual": "Las filas A y B quedan iluminadas con «n + m»; D, E y F se oscurecen con «n × m». Entre A y B, una lupa: los vectores de A ilegibles, el gráfico de araña de B legible. B se marca. Animación final: historia → (IA) → gráfico de araña; puesto → (IA) → gráfico de araña; los dos entran a una fórmula fija que da un número; se repite y da el mismo número.",
   "lines": [
    L("Solo A y B son lineales: la IA trabaja una vez por historia y una vez por puesto, y el puntaje es una cuenta fija."),
    L("En D, E y F, en cambio, la IA trabaja sobre cada par."),
    L("Entre A y B, la diferencia es quién puede leer el resultado. Los vectores de A no los entiende nadie. Las características de B, sí.", p=1),
    L("El equipo eligió B. La IA extrae características legibles de cada historia y de cada puesto. Y el puntaje lo calcula una fórmula, siempre igual."),
    L("Misma historia, mismo puesto, mismo puntaje. Eso quiere decir matching determinista.", p=1.5),
    L("La IA solo traduce texto a números que una persona puede revisar. No decide."),
   ],
   "audit": A([("Lineales frente a cuadráticas", [0, 1]), ("Legible frente a vectorial", [2]), ("Matching determinista", [3, 4, 5])],
              "Sí: la respuesta del piénsalo, paso a paso", "Sí: matching determinista", "Sí: costo lineal y resultado revisable (ADR-011)", "Sí: la animación final se repite y queda", "Bien")},
  {"id": "numeros", "kicker": "La cuenta",
   "visual": "Rótulo visible todo el tiempo: «cuenta nuestra, con el supuesto A17 del equipo». Dos barras: 50.000 prompts (B) y más de 600 millones (un juicio por par), con la segunda fuera de escala. Debajo, a una décima de centavo: 50 USD frente a más de 600.000 USD. Después, un filtro que la candidata ajusta: la grilla se achica. Al final, Q15: cambiar de modelo re-extrae cada historia y cada puesto una vez.",
   "lines": [
    L("El ADR da la regla, pero no hace la cuenta. Hagámosla con su supuesto del capítulo 3: 25.000 puestos, y unos 25.000 candidatos.", say="El A-D-R da la regla, pero no hace la cuenta. Hagámosla con su supuesto del capítulo tres: veinticinco mil puestos, y unos veinticinco mil candidatos."),
    L("Con B: 25.000 más 25.000, unos 50.000 prompts.", say="Con B: veinticinco mil más veinticinco mil, unos cincuenta mil prompts."),
    L("Con un juicio por par: 25.000 por 25.000, más de 600 millones.", say="Con un juicio por par: veinticinco mil por veinticinco mil, más de seiscientos millones.", p=1),
    L("Aunque cada prompt costara una décima de centavo, el precio más bajo que midieron, serían 50 dólares contra más de 600.000.", say="Aunque cada prompt costara una décima de centavo, el precio más bajo que midieron, serían cincuenta dólares contra más de seiscientos mil.", p=1),
    L("Es nuestra cuenta, no la del equipo. Pero muestra por qué contaron prompts."),
    L("El mismo ADR anota un límite: si la candidata filtra antes a qué puestos se postula, los pares bajan mucho, y la diferencia se achica."),
    L("Y cuando cambia el modelo, como pide Q15, B vuelve a extraer cada historia y cada puesto una vez. No cada par.", p=1),
   ],
   "audit": A([("La cuenta con A17 (declarada como propia)", [0, 1, 2, 3, 4]), ("El límite: prefiltrado", [5]), ("Q15: cambiar de modelo", [6])],
              "Sí: números del curso, ya vistos", "—", "Sí: el costo de la diferencia; y su límite según el ADR", "Sí: el rótulo «cuenta nuestra» está siempre visible", "Bien")},
  {"id": "precio", "kicker": "El precio de B",
   "visual": "El gráfico de araña con los ejes en blanco y un signo de pregunta: «¿qué ejes?». El renglón de *Known limitations* sobre las características. Una línea de tiempo: 29/09 ADR-011; el C3 de matching dice «califica con IA» hasta el 15/10, cuando se corrige.",
   "lines": [
    L("B tiene su precio, y el equipo lo dejó escrito entre sus limitaciones: definir bien esas características, para cualquier historia y cualquier puesto, es difícil."),
    L("El repositorio no dice qué ejes tendría el gráfico. Es el hueco más grande del diseño.", p=1),
    L("Y la idea era tan nueva que un diagrama siguió diciendo que la IA calificaba los matches dos semanas más. Lo corrigieron antes de la final."),
   ],
   "audit": A([("El costo de B y el hueco del repositorio", [0, 1]), ("La corrección tardía", [2])],
              "—", "—", "Sí: lo admite el equipo", "Sí", "Bien")},
  {"id": "podio", "kicker": "El podio",
   "visual": "Tres columnas: 1.º Pragmatic (IA → características legibles → fórmula), 2.º Katamarans (palabras clave con pesos → comparación, sin LLM), 3.º Ctrl+Alt+Elite (base vectorial + grafo → LLM que reordena). Una línea horizontal separa «el modelo fuera del puntaje» (1.º y 2.º) de «el modelo en el centro» (3.º).",
   "lines": [
    L("¿Cómo respondieron la misma pregunta los otros dos equipos del podio?"),
    L("Katamarans, segundo puesto, tampoco dejó que un LLM pusiera el puntaje: separa currículum y puesto en palabras clave, con un peso cada una, y compara."),
    L("Ctrl+Alt+Elite, tercer puesto, hizo lo contrario: una base de datos que guarda vectores y busca los más parecidos, y después un LLM que reordena los resultados.", say="Control Alt Elite, tercer puesto, hizo lo contrario: una base de datos que guarda vectores y busca los más parecidos, y después un L-L-M que reordena los resultados."),
    L("El primero y el segundo sacaron al modelo del puntaje. El tercero lo puso en el centro.", p=1),
    L("Ninguna es correcta por definición. Pero la de Pragmatic se puede explicar, probar y presupuestar."),
   ],
   "audit": A([("Contrapunto: Katamarans", [1]), ("Contrapunto: Ctrl+Alt+Elite", [2]), ("Síntesis", [3, 4])],
              "Sí: la misma pregunta del capítulo", "Base vectorial definida por lo que hace", "Sí: explicar, probar y presupuestar (el top 3)", "Sí: tres columnas fijas", "Bien (único uso del podio en el curso)")},
  {"id": "outro", "kicker": "Para llevarte",
   "visual": "Cuatro tarjetas: el candado del currículum; «n + m frente a n × m»; la animación historia → araña → fórmula; el gráfico de araña con ejes en blanco. Avance: tres flechas de IA antes de la fórmula, cada una con un signo de pregunta.",
   "lines": [
    L("Repasemos. La IA nunca ve el currículum: lo impide un permiso, no una promesa."),
    L("Para comparar caminos, se cuentan prompts: n más m crece tranquilo, n por m se dispara."),
    L("Pragmatic eligió que la IA extraiga características legibles, y que el puntaje sea una cuenta fija."),
    L("Su precio: definir esas características, que quedó como problema abierto.", p=1),
    L("La fórmula fija se puede probar como cualquier código. Pero la IA que extrae, no. Capítulo 7: probar lo impredecible."),
   ],
   "audit": A([("Repaso", [0, 1, 2, 3]), ("Avance", [4])], "—", "—", "—", "Sí", "Bien")},
 ],
}

CH7 = {
 "n": 7, "title": "Probar lo impredecible",
 "ideas": [
  "El camino de un currículum (caso de uso): todo lo que llama a un LLM va en segundo plano, porque puede tardar un minuto (ADR-008). El precio: los matches no son en tiempo real.",
  "La historia vive en su propio servicio (ADR-009): candidatos no necesita la historia, matching no necesita el currículum; ninguno tiene las dos cosas.",
  "Probar lo no determinista (ADR-025): conjuntos de prueba grandes con respuestas esperadas, y pruebas por tramos, posibles gracias al punto intermedio legible de ADR-011.",
  "Lo que no se automatiza: la anonimización la verifican personas u otro LLM; y probar también gasta prompts. El resto del sistema se prueba sin el proveedor, con dobles detrás de los adaptadores de IA; y cambiar de modelo se vuelve un procedimiento (Q14 → Q15 → recalcular).",
 ],
 "anchors": [
  "`UseCases/use-case-upload-a-resume.md` y sus diagramas de secuencia (`72df315`, `06b6cfc`, 30/09).",
  "`ADR/ADR-008-ui-reactivity.md`; R30 «soportar demoras de 60 s»; *Known limitations* («Delayed Matching Process»).",
  "`ADR/ADR-009-creation-of-story-as-own-microservice.md`.",
  "`ADR/ADR-025-ai-test-concept.md` (`9a3c22b`, 30/09 12:24: la última decisión nueva antes de la entrega).",
  "`ADR/ADR-011-deterministic-matching.md`: «la representación intermedia permite pruebas más chicas y precisas».",
  "`ArchitectureCharacteristics/Characteristics.md` → *Testability*: pruebas de regresión sin depender de terceros; ADR-006 (*Superseded*): «mock AI centrally»; adaptadores de IA en `C4/C3-components-*.md`.",
 ],
 "learn": [
  "Identificar qué pasos de un flujo deben ir en segundo plano y qué se paga por eso.",
  "Diseñar un concepto de pruebas para componentes con IA: conjuntos con respuesta esperada y alcances por tramo.",
  "Reconocer qué propiedades no se pueden verificar con una igualdad y cómo se cubren.",
  "Aislar un proveedor externo en las pruebas con un adaptador y un doble.",
 ],
 "cut": [
  "El autocompletado de datos de la empresa por IA (R9) como tramo de prueba: aparece en pantalla.",
  "Las características fortalecidas y debilitadas de ADR-008 y ADR-009.",
  "La notificación por correo de los consejos listos (extensión posible del caso de uso).",
  "La contradicción del C3 de historia que cita ADR-006 (en `HISTORIA.md` §6).",
 ],
 "questions": [
  "«¿Por qué la subida «termina» antes de los consejos?» Se ata a los 60 s del capítulo 3.",
  "«¿Por qué un servicio más, si cuesta?» Se explica con quién necesita qué dato, y se dice el costo.",
  "«¿Conjunto de prueba?» Se define con su forma: entrada más respuesta esperada.",
  "«¿Por qué por tramos?» Se responde con el ejemplo de un match que sale mal y dónde buscar.",
  "«¿Qué no se puede probar así?» Es el piénsalo; la respuesta viene del ADR.",
  "«¿Prueba de regresión? ¿Doble?» Cada uno con su línea, después del pedido del equipo que los vuelve necesarios.",
  "«¿Esto lo escribió el equipo?» En `cambio` se dice explícitamente que el procedimiento lo arma el curso con piezas del repositorio.",
 ],
 "scenes": [
  {"id": "intro", "kicker": "Capítulo 7",
   "visual": "La fórmula fija del capítulo 6 con un tilde verde («se prueba como código»). Delante, tres pasos con IA con signos de pregunta: currículum → historia, historia → características, puesto → características. Fecha: lunes 30/09, día de la entrega. Título.",
   "lines": [
    L("En el capítulo 6, el puntaje quedó como una cuenta fija. Pero antes de esa cuenta hay pasos con IA, y ninguno es determinista."),
    L("El lunes 30, día de la entrega, el equipo escribió cómo probarlos.", say="El lunes treinta, día de la entrega, el equipo escribió cómo probarlos.", p=0.6),
    L("Capítulo 7: probar lo impredecible."),
   ],
   "audit": A([("Puente", [0, 1])], "—", "—", "—", "Sí", "Bien")},
  {"id": "camino", "kicker": "El camino de un currículum",
   "visual": "El diagrama de secuencia real del caso de uso, redibujado simple. 1) La candidata sube el currículum; se guarda; se dispara el pedido de consejos; la subida termina (tilde). 2) En segundo plano, el pedido va al LLM; un reloj de hasta 60 s; los consejos vuelven y se guardan. 3) La candidata vuelve y los ve. 4) Envía el currículum; la historia se crea en segundo plano. 5) Un reloj periódico: matching extrae características y calcula puntajes. Al final, la limitación «los matches no son en tiempo real».",
   "lines": [
    L("Sigue un currículum por el sistema, con el caso de uso que dibujó el equipo."),
    L("La candidata lo sube. Se guarda, y se le pide a la IA una lista de consejos para mejorarlo."),
    L("Y aquí está el detalle: la subida termina ahí. Los consejos llegan después, en segundo plano."),
    L("¿Recuerdas los 60 segundos que puede tardar un LLM? Nadie mira una pantalla congelada durante un minuto.", say="¿Recuerdas los sesenta segundos que puede tardar un L-L-M? Nadie mira una pantalla congelada durante un minuto.", p=0.8),
    L("Cuando la candidata vuelve a la página, los consejos ya están."),
    L("Después, envía el currículum. Su historia se crea también en segundo plano."),
    L("Y cada cierto tiempo, el servicio de matching extrae características de lo nuevo, y calcula puntajes.", p=1),
    L("El precio quedó entre las limitaciones: los matches no aparecen en el momento."),
   ],
   "audit": A([("Lo lento en segundo plano (ADR-008)", [1, 2, 3, 4]), ("Historia y matching asíncronos", [5, 6]), ("El precio", [7])],
              "Sí: el caso de uso antes de la regla", "Segundo plano, por su efecto", "Sí: los 60 s del capítulo 3", "Sí: el diagrama avanza paso a paso", "Bien")},
  {"id": "muro", "kicker": "Un servicio para la historia",
   "visual": "Tres cajas candidatas: «candidatos», «matching», «servicio propio». En cada una, qué datos tendría: si la historia vive en candidatos, esa caja tiene currículum + historia; si vive en matching, matching tendría que recibir el currículum. La tercera opción deja cada dato en su caja. Al final, la etiqueta de costo: «un servicio más».",
   "lines": [
    L("¿Y dónde se crea la historia? Había tres lugares posibles: en el servicio de candidatos, en el de matching, o en uno propio."),
    L("Eligieron uno propio, en el ADR 009."),
    L("El servicio de candidatos no necesita la historia. El de matching no necesita el currículum. Si la historia viviera en uno de ellos, ese servicio quedaría acoplado a los dos modelos."),
    L("Un servicio aparte deja cada dato donde se usa, y refuerza la regla del capítulo 6.", p=1),
    L("El costo, anotado: un servicio más que construir y mantener."),
   ],
   "audit": A([("Servicio de historia propio (ADR-009)", [0, 1, 2, 3]), ("El costo", [4])],
              "Sí: las tres ubicaciones antes de la elección", "Acoplado, por su efecto", "Sí: quién necesita qué dato (texto del ADR)", "Sí", "Bien")},
  {"id": "problema", "kicker": "El problema de probar",
   "visual": "Una prueba clásica: «2 + 2 → espero 4 → ✓». Después, un LLM: la misma entrada da dos textos distintos. Un cambio de modelo (etiqueta «versión nueva») y los matches se mueven sin que nadie lo vea. La casilla de testabilidad del top 3 se ilumina.",
   "lines": [
    L("Ahora, el problema de fondo. Una prueba normal compara la salida con un valor esperado: si sumas dos más dos, esperas cuatro."),
    L("Con un LLM, la misma entrada puede dar textos distintos. Y cada modelo nuevo, o cada prompt nuevo, puede cambiarlo todo."),
    L("Si un cambio de modelo empeora los matches, nadie lo notaría a tiempo.", p=1),
    L("Por eso la testabilidad estaba en el top 3."),
   ],
   "audit": A([("Probar algo no determinista", [0, 1, 2, 3])],
              "Sí: la prueba clásica antes del problema", "Determinismo ya definido", "Sí: Q14 (capítulo 3)", "Sí", "Bien")},
  {"id": "conjuntos", "kicker": "Conjuntos y tramos",
   "visual": "Una tabla que se llena: columna «entrada», columna «respuesta esperada». Filas: currículum → historia esperada y características esperadas; puesto → características esperadas; pares → matches esperados. Después, la cadena currículum → historia → características → fórmula → match, con cada tramo encerrado en su propio recuadro de prueba. Un match sale mal: una lupa recorre los tramos y se detiene en uno.",
   "lines": [
    L("El ADR 025 responde con dos ideas."),
    L("La primera: conjuntos de prueba grandes, armados con cuidado, con los casos importantes del negocio."),
    L("Un conjunto de prueba es una colección de entradas, cada una con su respuesta esperada: currículums con su historia esperada, puestos con sus características esperadas, y matches esperados.", p=0.8),
    L("La segunda: probar por tramos. De currículum a historia, con foco en la anonimización. De historia a características. De puesto a características."),
    L("Cada tramo se prueba por separado.", p=1),
    L("¿Por qué funciona? Por la decisión del capítulo 6. Las características legibles son un punto intermedio que se puede revisar."),
    L("Si un match sale mal, sabes en qué tramo se rompió: en la historia, en las características, o en la fórmula."),
    L("Y la fórmula, que es fija, se prueba como cualquier código.", p=1),
   ],
   "audit": A([("Conjunto de prueba", [1, 2]), ("Pruebas por tramos", [3, 4]), ("Por qué funciona: el punto intermedio", [5, 6, 7])],
              "Sí: el problema de la escena anterior", "Sí: conjunto de prueba", "Sí: la representación intermedia (ADR-011)", "Sí: la tabla y la cadena quedan armadas", "Bien")},
  {"id": "doble", "kicker": "Probar sin el proveedor",
   "visual": "La frase de `Characteristics.md` resaltada: «las pruebas de regresión deben poder correr sin depender de sistemas de terceros». Los tres C3 en miniatura con sus adaptadores de IA iluminados (consejos, anonimizar, extraer características), al lado de los adaptadores de RR. HH. del capítulo 5. En modo prueba, cada adaptador de IA se reemplaza por una pieza gris rotulada «doble», que devuelve siempre la misma respuesta. Un contador de prompts queda en cero.",
   "lines": [
    L("Hay un tercer pedido, que el equipo escribió entre sus razones para la testabilidad: las pruebas de regresión tienen que correr aunque los sistemas de terceros no funcionen."),
    L("Una prueba de regresión verifica que lo que ya funcionaba siga funcionando después de un cambio.", p=0.8),
    L("Mira los diagramas de componentes: cada llamada a un LLM pasa por un adaptador, como las puertas del capítulo 5. Uno para los consejos, uno para anonimizar, uno para extraer características."),
    L("En una prueba, ese adaptador se puede reemplazar por un doble: una pieza falsa que responde siempre lo mismo, sin llamar a nadie."),
    L("Así se prueba el resto del sistema sin gastar prompts, y sin depender de que el proveedor esté disponible.", p=1),
    L("La IA real se prueba aparte, con los conjuntos. Todo lo demás, con dobles."),
   ],
   "audit": A([("Prueba de regresión", [0, 1]), ("Adaptadores de IA y dobles de prueba", [2, 3, 4]), ("Síntesis", [5])],
              "Sí: el pedido escrito del equipo antes de la técnica", "Sí: regresión y doble", "Sí: sin pagar prompts ni depender del proveedor", "Sí: la sustitución se anima y queda", "Bien (el doble es la técnica general; el repositorio lo anota como «mock AI centrally» en ADR-006 y exige la independencia en `Characteristics.md`)")},
  {"id": "piensalo", "kicker": "Piénsalo tú",
   "visual": "La cadena de tramos con sus recuadros. Anillo de 3 s. Después, el tramo «currículum → historia» se pone ámbar: «¿no revela raza, género, salud?» no es una igualdad. Dos verificadores: una persona y un segundo LLM (con la etiqueta «más complejidad»). Al final, un contador de prompts que sube en cada corrida de pruebas.",
   "lines": [
    L("Piénsalo tú: de todos esos tramos, ¿cuál no se puede verificar comparando con una respuesta esperada?", p=3),
    L("La anonimización. Que una historia no revele raza, género o salud no se comprueba con una igualdad."),
    L("El ADR lo admite: solo lo pueden verificar personas, o un segundo LLM, que agrega complejidad.", p=1),
    L("Y anotaron otro costo: probar también gasta prompts. Cada corrida de pruebas se paga."),
    L("¿Recuerdas al experto? Cada cambio de prompt o de modelo obliga a correr todo el conjunto otra vez.", p=1),
   ],
   "audit": A([("Aplicar: qué no se prueba con igualdad", [0, 1, 2]), ("El costo de probar", [3, 4])],
              "Sí: después de los tramos", "—", "Sí: texto del ADR-025", "Sí", "Bien")},
  {"id": "cambio", "kicker": "El día que cambia el modelo",
   "visual": "Un aviso del proveedor: «modelo retirado». Tres pasos numerados que se encienden: 1) el modelo nuevo corre los conjuntos, tramo por tramo, contra las respuestas esperadas (etiqueta Q14); 2) re-extraer características de todas las historias y todos los puestos, una vez cada uno (etiqueta Q15, contador n + m); 3) la fórmula recalcula los puntajes (etiqueta «sin IA, gratis»). Rótulo al pie: «piezas del equipo, procedimiento armado por el curso».",
   "lines": [
    L("Juntemos las piezas. ¿Qué pasa el día que el proveedor retira el modelo?"),
    L("El repositorio no lo escribe como un procedimiento único, pero las piezas están."),
    L("Primero, el modelo nuevo corre los conjuntos de prueba, tramo por tramo, contra las respuestas esperadas. Es Q14: que no empeore."),
    L("Si pasa, se vuelven a extraer las características de todas las historias y todos los puestos, una vez cada uno. Es Q15: todos medidos con el mismo modelo."),
    L("Y la fórmula recalcula los puntajes. Esa parte no usa IA: no cuesta prompts.", p=1),
    L("Cambiar de modelo deja de ser un salto al vacío, y pasa a ser un procedimiento.", p=1),
   ],
   "audit": A([("El procedimiento de cambio de modelo (Q14, Q15, ADR-025, ADR-011)", [0, 1, 2, 3, 4]), ("Síntesis", [5])],
              "Sí: el retiro de modelos del capítulo 3 como caso", "—", "Sí: cada paso con su requisito", "Sí: tres pasos numerados fijos", "Bien (se declara que el procedimiento lo arma el curso con piezas del repositorio)")},
  {"id": "outro", "kicker": "Para llevarte",
   "visual": "Cuatro tarjetas: el reloj en segundo plano; tres cajas con cada dato en la suya; la tabla entrada / esperado con los tramos y el doble gris; la persona que revisa la anonimización. Avance: una alcancía y la frase del README del capítulo 4.",
   "lines": [
    L("Repasemos. Lo lento va en segundo plano: consejos, historias y matches."),
    L("La historia vive en su propio servicio, lejos del currículum."),
    L("La IA se prueba con conjuntos grandes y por tramos, gracias al punto intermedio del capítulo 6. El resto, con dobles que reemplazan al LLM."),
    L("Y lo que no se automatiza, como la anonimización, lo revisan personas.", p=1),
    L("Quedaba una cuenta pendiente: pagar una IA cara con el dinero de una ONG. Capítulo 8: ahorrar donde no duele."),
   ],
   "audit": A([("Repaso", [0, 1, 2, 3]), ("Avance", [4])], "—", "—", "—", "Sí", "Bien")},
 ],
}

CH8 = {
 "n": 8, "title": "Ahorrar donde no duele",
 "ideas": [
  "La tesis del diseño, escrita después de la entrega: ahorrar a propósito en el resto para pagar una IA de precio impredecible.",
  "Tres ahorros con su resguardo: una base compartida con un solo dueño por dato (ADR-014/015); reportes por lotes, fuera del camino del usuario y por correo (ADR-003/017/019, con la seguridad cedida a la vista); encuestas alquiladas y disparadas desde servicios existentes (ADR-018/020).",
  "Lo que decidieron no hacer, a la vista: ADR rechazados y abiertos, y limitaciones conocidas en la portada.",
  "El cierre: las dos semanas de pulido y el método completo del equipo en seis pasos.",
 ],
 "anchors": [
  "`README.md`, introducción (`9891219`, 15/10) y *Known limitations* (`8516c51`, `d4c4fbb`, `ed4dc28`).",
  "`ADR/ADR-014-multiple-services-on-same-database.md`, `ADR/ADR-015-schema-ownership-and-permissions.md`.",
  "`ADR/ADR-003-batch-for-analytics.md`, `ADR/ADR-017-analytics-and-reporting-as-own-service.md`, `ADR/ADR-019-data-transmission-for-analytics.md`.",
  "`ADR/ADR-018-location-of-survey-triggers.md` (esqueleto «Survey service as its own service → Denied»), `ADR/ADR-020-externalizing-survey-processes.md`.",
  "`ADR/ADR-021-addressing-concurrency-of-hiring-managers.md` (*Denied*), `ADR/ADR-022-initial-technology-decisions.md` (*Open*).",
  "Actividad de los finalistas por fecha (ver `HISTORIA.md` §3.9).",
 ],
 "learn": [
  "Identificar dónde un diseño puede ahorrar sin dañar lo esencial, y qué resguardo exige cada ahorro.",
  "Explicar una regla de dueño único sobre una base compartida.",
  "Separar procesos operativos de procesos por lotes.",
  "Reconstruir el método del equipo y aplicarlo a otro caso.",
 ],
 "cut": [
  "La arquitectura hexagonal dentro del servicio de analytics (ADR-017).",
  "Las opciones 2 y 3 de ADR-019 en detalle.",
  "La gestión de usuarios y proveedores de identidad (limitación del README, ADR-022).",
  "El reparto de autores del equipo.",
 ],
 "questions": [
  "«¿Por qué compartir base no es un error?» Se explica que el estilo lo permite, se nombra el riesgo con el texto del ADR y se muestra el resguardo.",
  "«¿Por lotes?» Se define con su horario fijo, frente a «en el momento».",
  "«¿Bloqueo optimista?» Se define en una frase.",
  "«¿Por qué contar el silencio de dos semanas?» Se dice qué prueba y qué no (fecha de entrega inferida del patrón de todos los finalistas).",
  "«¿Qué me llevo del curso entero?» La escena `cierre` da el método en seis pasos.",
 ],
 "scenes": [
  {"id": "intro", "kicker": "Capítulo 8",
   "visual": "La barra de 25× del capítulo 4 y la alcancía de la ONG. Una balanza con «IA» de un lado y «todo lo demás» del otro. Título.",
   "lines": [
    L("¿Recuerdas el precio de la IA del capítulo 4? Impredecible, y el más alto del sistema."),
    L("Este capítulo trata del otro lado de la cuenta.", p=0.6),
    L("Capítulo 8: ahorrar donde no duele."),
   ],
   "audit": A([("Puente", [0, 1])], "—", "—", "—", "Sí", "Bien")},
  {"id": "tesis", "kicker": "La tesis",
   "visual": "La introducción del README con fecha 15/10. La frase original resaltada con su traducción. Después, un mapa del sistema en dos colores: oro para IA, integración y pruebas; gris para todo lo demás. Tres lupas sobre lo gris: base de datos, reportes, encuestas.",
   "lines": [
    L("Después de la entrega, el equipo reescribió la introducción de su repositorio. Una frase resume el diseño entero."),
    L("«Ahorramos costo deliberadamente en otras partes de la arquitectura, para mitigar el precio impredecible de la IA».", p=1.2),
    L("Lo esencial recibe lo mejor: la IA, la integración y las pruebas. El resto, lo más barato que funcione."),
    L("Mira tres lugares donde lo hicieron."),
   ],
   "audit": A([("La tesis de ahorro", [0, 1, 2])],
              "Sí: viene del costo de la IA", "—", "Sí: es la frase del equipo", "Sí: la cita queda ~8 s con pausa", "Bien")},
  {"id": "base", "kicker": "Una base para varios",
   "visual": "Primero, microservicios: cada servicio con su propia base (muchos cilindros). Después, service-based: cuatro servicios sobre una base compartida (un cilindro). Una maraña de flechas de escritura cruzadas: rótulo «acoplamiento caótico». Después, cada tabla con un solo escritor (flecha gruesa) y los demás leen (flechas finas); un candado de permisos en la base.",
   "lines": [
    L("Primero, la base de datos. En microservicios, que son muchos servicios pequeños, cada uno suele tener su base propia."),
    L("En el estilo basado en servicios del capítulo 2, se puede compartir. ADR 014: varios servicios usan la misma base. Es más barato, y más simple."),
    L("El riesgo quedó anotado en el mismo ADR: acoplamiento caótico. Si todos escriben en todo, nadie sabe qué cambio rompe a quién.", p=1),
    L("Por eso agregaron una regla, el ADR 015: cada tipo de dato tiene un solo dueño. Solo ese servicio lo escribe. Los demás, lo leen."),
    L("Y se hace cumplir con permisos de la base de datos, no con buena voluntad.", p=1),
    L("¿Te suena? Es la idea del capítulo 6: una regla que la arquitectura hace cumplir."),
   ],
   "audit": A([("Base compartida (ADR-014) y su riesgo", [0, 1, 2]), ("Dueño único con permisos (ADR-015)", [3, 4, 5])],
              "Sí: la maraña antes de la regla", "Microservicios, en una frase; acoplamiento caótico, por su efecto", "Sí: barato y simple; el resguardo, por el riesgo", "Sí", "Bien")},
  {"id": "reportes", "kicker": "Los reportes",
   "visual": "La nota amarilla del tablero del capítulo 1 («la mayoría de los eventos sirven para los reportes»). Un servicio de análisis y reportes con un reloj de luna (de noche) y un calendario (mensual). Una línea roja separa los procesos que atienden usuarios del servicio de reportes: ninguna flecha cruza hacia él desde el camino del usuario. El reporte sale como un sobre de correo. Al final, una flecha directa a la base de candidatos con un rótulo «seguridad cedida».",
   "lines": [
    L("Segundo, los reportes. ¿Recuerdas la nota del taller del capítulo 1? La mayoría de los eventos sirven para los reportes."),
    L("El pliego pide un reporte mensual para cada empresa. El equipo lo resolvió con un solo servicio de análisis y reportes, que trabaja por lotes."),
    L("Un proceso por lotes junta muchos datos y los procesa de una vez, en un horario fijo, como cada noche o cada mes, en lugar de en el momento.", p=0.8),
    L("Y una regla: ningún proceso que atiende a un usuario depende de este servicio. Si se cae, ninguna candidata ni empresa se queda esperando."),
    L("Los reportes salen por correo, no en una pantalla propia: una interfaz menos que construir.", p=1),
    L("Para los datos demográficos, el servicio lee directo de la base de candidatos. Es lo más simple, y el equipo anotó lo que cede: un servicio que accede a casi todo es un riesgo de seguridad.", p=1),
   ],
   "audit": A([("Un servicio de reportes por lotes", [1, 2]), ("Fuera del camino del usuario; por correo", [3, 4]), ("Lectura directa y seguridad cedida (ADR-019)", [5])],
              "Sí: la nota del taller del capítulo 1", "Sí: por lotes", "Sí: separación operativo / analítico; el trade-off de seguridad escrito", "Sí", "Bien")},
  {"id": "encuestas", "kicker": "Lo que se alquila",
   "visual": "El esqueleto del 26/09: «Survey service as its own service → Denied». Un servicio de encuestas tachado. En su lugar, un logo genérico de herramienta de encuestas externa; el servicio de candidatos y el de empresas disparan el correo, cada uno con su libreta de contactos que no sale de su caja. Contador: «servicios nuevos: 0».",
   "lines": [
    L("Tercero, las encuestas del pliego: cinco preguntas a cada parte."),
    L("En la sesión de diseño, la nota fue corta: un servicio propio de encuestas, rechazado."),
    L("Se alquilan, con SurveyMonkey o algo parecido. Y el envío lo dispara el servicio de cada usuario, que ya tiene su correo: los datos de contacto no salen de su lugar."),
    L("Cero servicios nuevos.", p=1),
    L("El mismo criterio de la IA: lo que no diferencia a ClearView, se alquila."),
   ],
   "audit": A([("Encuestas alquiladas y disparadas desde servicios existentes", [1, 2, 3]), ("El criterio común con la IA", [4])],
              "Sí", "—", "Sí: costo y datos de contacto en su lugar", "Sí", "Bien")},
  {"id": "no", "kicker": "Lo que no hicieron",
   "visual": "Tres sellos: ADR-021 «Denied», ADR-022 «Open», y la sección *Known limitations* del README. Bajo el 021, dos responsables editando el mismo puesto y un aviso al guardar (bloqueo optimista). Bajo el 022, casillas vacías: base de datos, cola, nube; una nota «RabbitMQ > Kafka, por costo». Bajo las limitaciones, tres renglones.",
   "lines": [
    L("Un repositorio honesto también muestra lo que no se hizo."),
    L("ADR 021, rechazado: dos responsables editando el mismo puesto a la vez. Se resuelve con la interfaz, o más adelante con bloqueo optimista: detectar el choque al guardar."),
    L("ADR 022, abierto: base de datos, colas, nube. Las tecnologías concretas quedaron sin elegir. Solo una pista: una cola liviana como RabbitMQ antes que Kafka, por costo."),
    L("Y en la portada, sus limitaciones conocidas: el límite de uso del LLM, sin resolver; matches que no son en tiempo real; y características legibles, difíciles de definir.", p=1),
    L("Nada de eso está escondido."),
   ],
   "audit": A([("ADR rechazado (021) y bloqueo optimista", [1]), ("ADR abierto (022)", [2]), ("Limitaciones a la vista", [3, 4])],
              "—", "Bloqueo optimista, en una frase", "Sí: simplicidad y costo", "Sí: tres sellos fijos", "Aceptable: tres detalles compactos; el valor está en mostrarlos, no en desarrollarlos")},
  {"id": "final", "kicker": "Las dos semanas",
   "visual": "Un gráfico de commits por día: el pico del 30/09 (23 commits), dos semanas vacías, un rebrote del 14 al 16/10. Debajo, las barras de Katamarans, Jazz-Executor, ArchZ y DevExperts, con su pico el mismo 30/09, rotulado «inferido: fecha de entrega». Lo que cambió después: enlaces, nombres, el C3 de matching alineado, el porqué del ADR-002, la introducción.",
   "lines": [
    L("Queda una última pista del historial. El 30 de septiembre, el equipo hizo 23 commits. Después, dos semanas de silencio.", say="Queda una última pista del historial. El treinta de septiembre, el equipo hizo veintitrés commits. Después, dos semanas de silencio."),
    L("Varios finalistas tienen su pico de commits ese mismo día, así que muy probablemente esa fue la fecha de entrega."),
    L("Cuando volvieron, no rediseñaron nada. Corrigieron enlaces y nombres, alinearon un diagrama con el ADR del matching, y escribieron el porqué que les faltaba."),
    L("El diseño ya estaba decidido. Lo que pulieron fue que se entendiera.", p=1),
   ],
   "audit": A([("Lo que muestra el corte (y lo que se infiere)", [0, 1]), ("Pulir para que se entienda", [2, 3])],
              "Sí: el gráfico antes de la conclusión", "—", "Sí, marcando la inferencia", "Sí", "Bien")},
  {"id": "cierre", "kicker": "El método",
   "visual": "Seis tarjetas que se acumulan, cada una con su artefacto real en miniatura: la mesa de post-its; la hoja de características; el archivo R/Q/A con la libreta del experto; la estimación de tokens; el diagrama de los seis caminos con B marcada; el mapa oro y gris. Al final, el logo del equipo.",
   "lines": [
    L("Repasemos este capítulo: una base con un solo dueño por dato, reportes por lotes fuera del camino del usuario, encuestas alquiladas, y lo no resuelto a la vista.", p=1),
    L("Y ahora, el curso entero, en el orden del equipo."),
    L("Uno: entender el negocio con todos, en post-its, con las dudas a la vista."),
    L("Dos: elegir pocas características, con su porqué. Y de ahí, el estilo."),
    L("Tres: numerar requisitos y supuestos. Y lo que no sabes, preguntárselo a quien sabe."),
    L("Cuatro: medir antes de decidir. Un prompt de prueba, con precios y con fecha."),
    L("Cinco: poner la IA donde se pueda probar, y contar sus prompts."),
    L("Seis: ahorrar en todo lo demás, para pagar lo que importa.", p=1.2),
    L("El diseño ganador no apuesta todo a la IA. La usa poco, en un lugar donde se puede probar, y deja escrito por qué."),
   ],
   "audit": A([("Repaso del capítulo", [0]), ("Repaso del curso (6 pasos)", [2, 3, 4, 5, 6, 7]), ("Síntesis final", [8])],
              "—", "—", "—", "Sí: una tarjeta por paso, ~4 s cada una más la pausa", "Bien")},
 ],
}
