# Capítulos 1 a 4. L(texto, say=None, p=pausa). Los índices de "concepts" apuntan a líneas de la escena (desde 0).

def L(text, say=None, p=None):
    d = {"text": text}
    if say: d["say"] = say
    if p: d["pauseAfter"] = p
    return d

def A(concepts, case, defined, why, read, verdict):
    return {"concepts": concepts, "case": case, "defined": defined, "why": why, "read": read, "verdict": verdict}

CH1 = {
 "n": 1, "title": "El encargo",
 "ideas": [
  "Qué pide ClearView, como un recorrido: el currículum se vuelve una historia anónima, se compara con puestos, la empresa paga por desbloquearlo y todo se mide para detectar sesgos.",
  "Lo que el pliego no dice: ningún volumen, sistemas de RR. HH. «de ejemplo» y una sola frase sobre la IA. Con huecos así, cada integrante imagina un sistema distinto.",
  "El primer movimiento del equipo: un event storming (ADR-001). Hechos del negocio en orden, quién los provoca, y las dudas en rosado.",
  "La primera duda escrita: ¿la historia es legible por humanos? Es la semilla de la decisión central (capítulo 6).",
 ],
 "anchors": [
  "Pliego: documento de Google enlazado desde `Equihire-Architects/README.md` (ver `HISTORIA.md` §1).",
  "`ADR/ADR-001-use-ddd.md` (`35471ec`, 23/09 08:52).",
  "`EventStorming/assets/eventstorming_stickynotes.jpeg` y `Eventstorming.png` (fechado 23.09.2024; subidos en `0f2599c`).",
  "`Requirements/requirements-and-assumptions.md`, Q3 (representación legible más una condensada para comparar).",
 ],
 "learn": [
  "Contar el recorrido de un currículum en ClearView, de la subida al reporte.",
  "Separar lo que el pliego da de lo que deja abierto.",
  "Correr un event storming mínimo: eventos en pasado y en orden, después comandos y actores, y las dudas a la vista.",
 ],
 "cut": [
  "Los consultores de DEI que acompañan entrevistas (el pliego los menciona; el equipo los reduce a R29, hallazgos cargados a mano).",
  "Los recorridos detallados de cada usuario y la lista de 11 sistemas de RR. HH. (aparece en pantalla, no se lee).",
  "La discusión sobre «contratado» (Data Point 1) y la nota de pago sincrónico: detalle secundario.",
  "El detalle de DDD como disciplina: aquí solo importa el taller.",
 ],
 "questions": [
  "«¿Qué es un kata? ¿Y un pliego?» Se definen en las dos primeras líneas, con el ejemplo concreto.",
  "«¿Qué es S.M.A.R.T.?» Se dice qué significa la sigla, en una frase, sin detenerse: no vuelve a importar.",
  "«¿Qué es un ATS?» Se nombra con su traducción («programas de seguimiento de candidatos») y su problema.",
  "«¿Qué es un LLM?» Se define con un referente cotidiano (ChatGPT). Se retoma en el capítulo 3.",
  "«¿Por qué post-its y no diagramas?» La escena `huecos` planta el riesgo (cada uno imagina un sistema distinto) antes de nombrar la técnica.",
  "«¿Evento, comando, actor?» Cada uno con su color y un ejemplo del tablero real.",
 ],
 "scenes": [
  {"id": "intro", "kicker": "Capítulo 1",
   "visual": "Logo de O'Reilly Architecture Katas, otoño 2024. La palabra «kata» se descompone: un cliente entrega un documento (el pliego) a varios equipos; cada uno dibuja cajas y flechas. Aparece el nombre del equipo, Pragmatic, con una línea de commits que avanza. Título del capítulo.",
   "lines": [
    L("En otoño de 2024, O'Reilly organizó otra Architecture Kata.", say="En otoño de dos mil veinticuatro, O'Reilly organizó otra Architecture Kata."),
    L("Una kata es un ejercicio de práctica: un cliente entrega un pliego, el documento con lo que necesita."),
    L("Y cada equipo diseña la arquitectura: qué piezas tiene el sistema, y cómo se hablan."),
    L("Ganó un equipo de tres personas llamado Pragmatic. Este curso sigue su repositorio, en el orden en que razonaron.", p=0.6),
    L("Capítulo 1: el encargo."),
   ],
   "audit": A([("Kata y pliego", [1, 2]), ("El método del curso (seguir el orden real)", [3])],
              "Sí: se muestra el cliente entregando el pliego", "Sí", "Sí: el curso sigue el orden del razonamiento", "Sí", "Bien")},
  {"id": "cliente", "kicker": "El cliente",
   "visual": "Tarjeta de Diversity Cyber Council («501c3, sin fines de lucro»). Un currículum en pantalla: tres indicios (raza, cultura, estilo de vida) se iluminan en rojo y una balanza se inclina. Rótulo «sesgo». Después, una pila de currículums entra en una caja gris «ATS» y salen emparejados con puestos equivocados.",
   "lines": [
    L("El cliente era Diversity Cyber Council, una organización sin fines de lucro de Estados Unidos."),
    L("Ayuda a personas de grupos poco representados en tecnología a formarse y a conseguir empleo."),
    L("Su pliego parte de un problema: al leer un currículum, pueden pesar indicios de raza, de cultura o de estilo de vida, aunque nadie lo quiera."),
    L("Eso se llama sesgo: una inclinación que decide por ti, sin que lo notes.", p=1),
    L("Y hay un segundo problema: los programas de seguimiento de candidatos que usan las empresas, los ATS, emparejan mal personas con puestos."),
   ],
   "audit": A([("Sesgo", [2, 3]), ("ATS", [4])],
              "Sí: el currículum con indicios antes de la palabra «sesgo»", "Sí", "Sí: es el problema que justifica el producto", "Sí: dos imágenes, una por problema", "Bien")},
  {"id": "clearview", "kicker": "La idea",
   "visual": "El recorrido de ClearView como una línea horizontal que se arma paso a paso: currículum → (IA) → historia sin nombre → comparación con puestos (un puntaje) → la empresa lee la historia → candado que se abre con un pago → el currículum viaja a un sistema de RR. HH. Debajo, los cinco data points se encienden uno por uno. Al final, cuatro verbos: anonimizar, comparar, cobrar, medir.",
   "lines": [
    L("La respuesta se llama ClearView. Mira el recorrido de un currículum."),
    L("La candidata lo sube. Una IA lo reescribe como una historia: su formación, su experiencia y sus logros, sin nada que revele quién es."),
    L("El pliego pide el formato S.M.A.R.T.: metas específicas, medibles, alcanzables, relevantes y con plazo.", say="El pliego pide el formato smart: metas específicas, medibles, alcanzables, relevantes y con plazo."),
    L("Esa historia se compara con los puestos abiertos, y recibe un puntaje de parecido."),
    L("Si el puntaje pasa un umbral, hay un match: la historia y el puesto encajan."),
    L("Con un match, la empresa lee la historia. Y si le interesa, paga para desbloquear el perfil completo.", p=0.8),
    L("Recién ahí aparece la persona, y su currículum viaja al sistema de recursos humanos de la empresa.", p=1),
    L("Además, el pliego pide medir: quién avanzó, a quién contrataron, una encuesta a cada parte, y datos demográficos."),
    L("Todo, para revelar diferencias entre contratados y descartados que no deberían existir."),
    L("Anonimizar, comparar, cobrar y medir: esa es la promesa.", p=1),
   ],
   "audit": A([("La historia anónima", [1, 2]), ("Puntaje y match", [3, 4]), ("Desbloquear y pagar", [5, 6]), ("Medir (data points)", [7, 8]), ("Síntesis", [9])],
              "Sí: se cuenta como recorrido de un caso", "Sí: historia, match, desbloquear y S.M.A.R.T., cada uno en su línea", "Sí: medir para revelar diferencias", "Sí: la línea se arma al ritmo de la voz y queda completa ~6 s", "Bien")},
  {"id": "huecos", "kicker": "Lo que no dice",
   "visual": "El pliego como documento. Tres huecos marcados con signos de pregunta: «volumen: ?», «sistemas de RR. HH.: 11 ejemplos» (logos que se desvanecen), «IA: supón un LLM entrenado». Después, tres burbujas de pensamiento sobre tres siluetas, cada una con un sistema distinto.",
   "lines": [
    L("Ahora fíjate en lo que el pliego no dice."),
    L("No dice cuántos candidatos habrá, ni cuántos puestos. No trae un solo número de volumen."),
    L("Nombra once sistemas de recursos humanos, como Workday o SAP, y aclara que son solo ejemplos."),
    L("Y sobre la IA dice una sola frase: supón un LLM entrenado."),
    L("Un LLM, un modelo de lenguaje grande, es el tipo de IA detrás de herramientas como ChatGPT: recibe texto, y responde con texto.", p=1),
    L("Con tantos huecos, hay un riesgo: que cada integrante del equipo se imagine un sistema distinto.", p=1),
   ],
   "audit": A([("Los huecos del pliego", [0, 1, 2, 3]), ("LLM", [4]), ("El riesgo de los modelos mentales distintos", [5])],
              "Sí: los huecos antes del riesgo, y el riesgo antes de la técnica", "Sí: LLM con referente cotidiano", "Sí: prepara la razón del taller", "Sí: un hueco por línea", "Bien")},
  {"id": "storming", "kicker": "Event storming",
   "visual": "Calendario: lunes 23/09. Una tarjeta de ADR con tres secciones (contexto, decisión, consecuencias) que se llenan con el texto del ADR-001. Después, una mesa vacía y la leyenda real del tablero: amarillo = evento, azul = comando, naranja = actor, verde = sistema externo, rosado = duda. Aparecen tres eventos amarillos de ejemplo en orden.",
   "lines": [
    L("Por eso, el lunes 23 de septiembre, lo primero que hizo el equipo no fue dibujar cajas. Fue un taller.", say="Por eso, el lunes veintitrés de septiembre, lo primero que hizo el equipo no fue dibujar cajas. Fue un taller."),
    L("Lo dejó escrito en su primer ADR. Un ADR es un registro de decisión de arquitectura: un documento corto con el contexto, la decisión y sus consecuencias."),
    L("Este dice: tenemos poco tiempo, así que usamos event storming, para entender el problema juntos."),
    L("Event storming es un taller con post-its. Se escribe, en orden, todo lo que pasa en el negocio.", p=0.6),
    L("Cada post-it amarillo es un evento: algo que ya ocurrió, escrito en pasado. Currículum subido. Historia publicada. Candidato contratado."),
    L("Después, para cada evento, quién lo provoca y con qué acción: el actor, en naranja, y el comando, en azul."),
    L("Y en rosado, todo lo que nadie sabe responder todavía.", p=1),
    L("Primero, los hechos del negocio en orden. Las piezas del software, después."),
   ],
   "audit": A([("ADR", [1, 2]), ("Event storming", [3]), ("Evento", [4]), ("Actor y comando", [5]), ("Notas de duda", [6]), ("Síntesis", [7])],
              "Sí: viene del riesgo de la escena anterior", "Sí: ADR, evento, actor, comando, cada uno en su línea", "Sí: «para entender el problema juntos» y «poco tiempo» (texto del ADR)", "Sí: la leyenda de colores queda fija toda la escena", "Bien")},
  {"id": "mesa", "kicker": "La mesa",
   "visual": "La foto real de la mesa con post-its, que se funde en el tablero digital redibujado. Se resalta la fila central evento por evento al ritmo de la voz. Al final, zoom a la nota amarilla de la esquina («Most events are used for analytics & reports»), con su traducción.",
   "lines": [
    L("Así quedó la mesa. Sigue la fila del medio."),
    L("Currículum enviado. Currículum publicado. Currículum anonimizado como historia. Historia publicada."),
    L("Match creado. La empresa revisa, desbloquea y paga. El currículum sale hacia uno o varios sistemas de recursos humanos."),
    L("Al final, candidato contratado, y una encuesta para cada parte.", p=1),
    L("Y en una esquina, una nota: la mayoría de los eventos sirven para los reportes."),
    L("Guarda esa nota. Vuelve en el capítulo 8."),
   ],
   "audit": A([("El flujo del negocio en eventos", [1, 2, 3]), ("Eventos para reportes (plantado)", [4, 5])],
              "Sí: es el tablero real", "—", "—", "Sí: la fila se resalta por tramos; la nota queda ~6 s", "Bien (consolida lo anterior con el artefacto real)")},
  {"id": "piensalo", "kicker": "Piénsalo tú",
   "visual": "Zoom al tramo «currículum anonimizado como historia → historia publicada». Debajo, un post-it rosado en blanco. Anillo de cuenta regresiva de 3 s. Después el post-it se llena con las notas reales de la foto: «What format?» y «Human readable?», traducidas. Dos caminos salen de la historia: hacia una persona (texto) y hacia una máquina (números).",
   "lines": [
    L("Mira el tramo de la historia. Pegada debajo, hay una nota rosada."),
    L("Piénsalo tú: con lo que sabes del pliego, ¿qué preguntarías sobre esa historia?", p=3),
    L("El equipo escribió dos preguntas: ¿qué formato tiene? ¿Y es legible por humanos?"),
    L("Parece un detalle. Pero si la historia la lee una persona, tiene que ser texto. Si la compara una máquina, conviene que sean números."),
    L("Y para dar un puntaje de parecido, hacen falta las dos cosas.", p=1),
    L("De esa nota rosada va a salir la decisión central del equipo, en el capítulo 6."),
   ],
   "audit": A([("Aplicar: leer una duda en el tablero", [1]), ("La tensión texto legible frente a números comparables", [2, 3, 4]), ("Puente al capítulo 6", [5])],
              "Sí: la pregunta llega después de conocer la historia y el puntaje", "—", "Sí: quién lee la historia decide su forma", "Sí: las notas reales quedan en pantalla hasta el final", "Bien")},
  {"id": "outro", "kicker": "Para llevarte",
   "visual": "Cuatro tarjetas, una por idea, que se acumulan: el recorrido (cuatro verbos), el pliego con huecos, la mesa de post-its, la nota rosada. Al final, una hoja de trabajo en blanco con siete renglones: avance del capítulo 2.",
   "lines": [
    L("Repasemos. ClearView anonimiza el currículum, lo compara con puestos, cobra por desbloquearlo y mide los sesgos."),
    L("El pliego deja huecos: ningún volumen, y una sola frase sobre la IA."),
    L("El equipo empezó con un event storming: los hechos del negocio en orden, y las dudas a la vista."),
    L("Y la primera duda fue si la historia la lee una persona o una máquina.", p=1),
    L("Ese mismo día, el equipo eligió las tres cualidades que iban a mandar sobre todo lo demás. Capítulo 2: tres de siete."),
   ],
   "audit": A([("Repaso de las 4 ideas", [0, 1, 2, 3]), ("Avance", [4])],
              "—", "—", "—", "Sí: una tarjeta por idea", "Bien")},
 ],
}

CH2 = {
 "n": 2, "title": "Tres de siete",
 "ideas": [
  "Qué es una característica de arquitectura: cómo debe comportarse el sistema, no qué hace. Se eligen pocas porque cada una cuesta algo.",
  "El top 3 de Pragmatic (factibilidad, interoperabilidad, testabilidad) sale de tres desafíos del caso: el dinero de una ONG, los sistemas ajenos y una IA no determinista. Y bajaron otras con su motivo.",
  "De características a estilo con la hoja de Mark Richards. La hoja no tiene factibilidad: la reemplazan por costo y simplicidad a medio peso, y lo anotan. Gana service-based, con event-driven donde hace falta conectar; microkernel se descarta.",
  "Lo que muestra el historial: estilo y top 3 se fijaron el primer día y no cambiaron; el porqué completo del estilo se escribió después de la entrega.",
 ],
 "anchors": [
  "`ArchitectureCharacteristics/images/architecture-characteristics.png` (versión `1e333a8`, 23/09, top 3 ya marcado; final `548bbe0`).",
  "`ArchitectureCharacteristics/Characteristics.md` (`c277932` 24/09: las 7; `d093b51` 25/09: el top 3; `19cdc81` 26/09: integridad de datos).",
  "`ADR/ADR-002-architecture-style.md` y `ADR/images/ADR-002-architecture-style.png` (hoja fechada 23/09; «*» = sustituto de feasibility, 0,5 de peso).",
  "`ADR/ADR-004-data-integrity-downplayed.md` (`8c0e5f4`, 30/09).",
  "El porqué del ADR-002 agregado el 15/10 (`c6523b5`).",
 ],
 "learn": [
  "Distinguir una característica de arquitectura de un requisito funcional.",
  "Justificar un top 3 con desafíos concretos del caso, y bajar prioridades con motivo.",
  "Usar una hoja de estilos con estrellas, y adaptar el método cuando le falta un criterio, dejándolo escrito.",
 ],
 "cut": [
  "Las definiciones textuales de las 12 características de la tabla (se ven en pantalla).",
  "Abstracción y extensibilidad como descartes (se mencionan en pantalla; la voz se queda con configurabilidad, que vuelve en el capítulo 5).",
  "Observabilidad como característica implícita.",
  "El detalle de las ocho columnas de la hoja de estilos: la voz compara solo service-based, event-driven y microkernel.",
  "El contrapunto del podio sobre el top 3 (Katamarans: costo, abstracción, integración; Ctrl+Alt+Elite: escalabilidad, rendimiento, interoperabilidad): queda en `HISTORIA.md` §8 para usar el podio una sola vez, en el capítulo 6.",
 ],
 "questions": [
  "«¿Característica de arquitectura? ¿No es un requisito?» La escena `que` abre con dos sistemas que hacen lo mismo y se comportan distinto, antes del nombre.",
  "«¿Por qué solo tres?» Se dice que cada una cuesta y que algunas se estorban; la hoja pone el límite de siete.",
  "«¿Factibilidad?» Se define con las palabras del equipo: dinero, tiempo y gente.",
  "«¿Determinista?» Se define al pasar: misma entrada, misma salida.",
  "«¿Service-based? ¿Event-driven? ¿Microkernel?» Cada uno en una línea propia, con un ancla al capítulo 1 para los eventos.",
  "«¿Elegir el estilo el primer día está bien?» La escena `historial` lo trata como apuesta, con su condición.",
 ],
 "scenes": [
  {"id": "intro", "kicker": "Capítulo 2",
   "visual": "Las notas rosadas del capítulo 1 se apilan a un costado («todavía abiertas»). En el centro, la hoja de características de Mark Richards en blanco, con siete renglones. Título.",
   "lines": [
    L("¿Recuerdas las notas rosadas del capítulo 1? Esas dudas siguieron abiertas."),
    L("Pero ese mismo lunes, el equipo hizo otra cosa: decidir qué cualidades del sistema importaban más.", p=0.6),
    L("Capítulo 2: tres de siete."),
   ],
   "audit": A([("Puente desde el capítulo 1", [0, 1])], "—", "—", "—", "Sí", "Bien")},
  {"id": "que", "kicker": "Características",
   "visual": "Dos cajas idénticas, «Sistema A» y «Sistema B», con las mismas funciones listadas. Un proveedor externo se cae: A sigue en verde, B se pone rojo. Dos etiquetas de costo: A barato, B caro. Rótulo: «características de arquitectura = cómo se comporta». Una balanza: subir una característica baja otra.",
   "lines": [
    L("Dos sistemas pueden hacer exactamente lo mismo, y aun así ser muy distintos."),
    L("Si un proveedor externo se cae, uno sigue funcionando y el otro se detiene. Uno es barato de construir. El otro, no."),
    L("Esas cualidades se llaman características de arquitectura: no dicen qué hace el sistema, sino cómo tiene que comportarse."),
    L("Y no se pueden tener todas. Cada una cuesta algo, y algunas se estorban entre sí.", p=1),
    L("Por eso se eligen pocas, y se dice por qué."),
   ],
   "audit": A([("Característica de arquitectura", [0, 1, 2]), ("Por qué pocas (trade-off)", [3, 4])],
              "Sí: dos sistemas iguales que se comportan distinto", "Sí", "Sí: cada una cuesta", "Sí", "Bien")},
  {"id": "siete", "kicker": "Las siete",
   "visual": "La hoja real del 23/09 redibujada. Siete renglones que se escriben a mano uno por uno; cuando la voz nombra una, aparece su motivo en una línea a la derecha. Al final, la columna «otras consideradas» con configurabilidad tachada y su motivo; más abajo, integridad de datos con una etiqueta «26/09».",
   "lines": [
    L("El equipo usó una hoja de trabajo de Mark Richards, coautor de un libro clásico de arquitectura. Su regla: como máximo, siete."),
    L("Anotaron siete, cada una con su motivo. Seguridad: el valor del producto es, justamente, anonimizar."),
    L("Tolerancia a fallos: si el sistema de recursos humanos de una empresa se cae, ClearView sigue."),
    L("Adaptabilidad: la IA cambia rápido, y el sistema tiene que cambiar con ella."),
    L("Escalabilidad: comparar todas las historias con todos los puestos podría crecer de forma cuadrática. Guarda esa palabra.", p=1),
    L("También dejaron afuera otras, con su motivo. Por ejemplo, poder configurar cada integración en caliente: las integraciones nuevas llegarían con versiones nuevas del sistema."),
    L("Tres días después, bajaron también la integridad de los datos: creían que se cuida en el código, y que la cubren las pruebas.", p=1),
   ],
   "audit": A([("La hoja y su límite de siete", [0]), ("Cuatro de las siete, con motivo", [1, 2, 3, 4]), ("Bajar con motivo (configurabilidad, integridad)", [5, 6])],
              "Sí: cada característica se ata a un hecho del caso", "Sí, por su motivo (la definición formal queda en pantalla)", "Sí: una razón por característica, del texto del equipo", "Sí: cada motivo queda escrito junto a su renglón", "Bien (cuatro características son detalle: una frase cada una, como admite la guía; el top 3 tiene escena propia)")},
  {"id": "top3", "kicker": "El top 3",
   "visual": "Tres casillas que se marcan con una X, una por desafío. Cada desafío aparece primero como un dibujo (una alcancía de donaciones con una moneda que se va por cada consulta a la IA; muchos enchufes de formas distintas; una IA que responde distinto a la misma pregunta) y después su característica y su definición. Al final, las tres juntas bajo el rótulo «dinero, sistemas ajenos, IA impredecible».",
   "lines": [
    L("De las siete, marcaron tres. Y las justificaron con tres desafíos del caso."),
    L("Primero: el cliente es una ONG que vive de donaciones, y la IA cobra por cada uso."),
    L("De ahí, factibilidad: que el sistema se pueda construir y mantener con el dinero, el tiempo y la gente que hay.", p=1),
    L("Segundo: cada empresa usa su propio sistema de recursos humanos, y cada uno tiene una API distinta."),
    L("De ahí, interoperabilidad: poder conectarse con sistemas ajenos para completar una tarea."),
    L("Para ClearView, eso es entregar un currículum a cualquier sistema de recursos humanos. Y también poder cambiar de modelo de IA sin rehacer todo.", p=1),
    L("Tercero: la IA no es determinista. Determinista quiere decir: misma entrada, misma salida. Con la IA, cada versión nueva puede cambiar los resultados."),
    L("De ahí, testabilidad: qué tan fácil y completo es probar el sistema. Si no puedes revisar lo que hace la IA, nadie puede confiar en sus resultados.", p=1),
    L("Mira las tres juntas: dinero, sistemas ajenos e IA impredecible. Ninguna habla de velocidad, ni de millones de usuarios."),
   ],
   "audit": A([("Factibilidad", [1, 2]), ("Interoperabilidad", [3, 4, 5]), ("Testabilidad y determinismo", [6, 7]), ("Síntesis", [8])],
              "Sí: cada desafío del caso antes de su característica", "Sí, las tres y «determinista»", "Sí: es el razonamiento escrito por el equipo (`Characteristics.md`)", "Sí: cada casilla se marca y queda", "Bien")},
  {"id": "piensalo", "kicker": "Piénsalo tú",
   "visual": "La hoja de estilos de Richards: ocho columnas con iconos (layered, modular monolith, microkernel, microservices, service-based, service-oriented, event-driven, space-based) y filas con estrellas. Las filas de interoperabilidad y testabilidad se resaltan. Un hueco donde debería estar «factibilidad». Anillo de 3 s. Después aparecen resaltadas «cost» y «simplicity» con un asterisco y la nota al pie real: «* used as a substitute for feasibility (each 0.5x weight)».",
   "lines": [
    L("Con las tres elegidas, faltaba lo grande: el estilo de arquitectura, la forma general del sistema. Una sola pieza o muchas, y cómo se hablan."),
    L("La misma hoja compara ocho estilos, con estrellas, una fila por característica."),
    L("Pero hay un problema: la hoja no tiene una fila para factibilidad.", p=0.8),
    L("Piénsalo tú: si lo que más te importa no está en la tabla, ¿qué haces?", p=3),
    L("El equipo la reemplazó por dos filas que sí están: costo y simplicidad, cada una con la mitad del peso."),
    L("Y lo dejó anotado al pie de la hoja. Un atajo, pero a la vista.", p=1),
   ],
   "audit": A([("Estilo de arquitectura", [0, 1]), ("Aplicar: adaptar la herramienta cuando le falta un criterio", [2, 3]), ("La sustitución y por qué se anota", [4, 5])],
              "Sí: el hueco en la tabla antes de la pregunta", "Sí: estilo", "Sí: anotarlo deja revisar el atajo", "Sí: la nota al pie queda ~6 s", "Bien")},
  {"id": "estilo", "kicker": "El estilo",
   "visual": "Columna service-based resaltada con sus recuadros reales: costo ★★★★, simplicidad ★★★, testabilidad ★★★★, interoperabilidad ★★. Diagrama simple: cuatro servicios grandes (candidatos, empleadores, historia, matching) sobre una base compartida. Después, la columna event-driven con su recuadro en interoperabilidad ★★★ y una flecha de aviso entre dos servicios, con un post-it amarillo del capítulo 1 encima. Por último, microkernel: núcleo con complementos, sus filas de escalabilidad ★ y tolerancia a fallos ★ en rojo, y una X.",
   "lines": [
    L("Con esas filas, ganó un estilo llamado service-based, basado en servicios."),
    L("Son unos pocos servicios grandes, uno por área del negocio, como candidatos o matching. Se despliegan por separado, y suelen compartir la base de datos."),
    L("Saca cuatro estrellas en costo y en testabilidad, y tres en simplicidad. Pero en interoperabilidad, solo dos.", p=0.8),
    L("Para eso sumaron un segundo estilo, solo donde haga falta: event-driven, dirigido por eventos."),
    L("Un servicio publica un aviso de que algo pasó, y los demás reaccionan cuando pueden, sin esperarse. ¿Recuerdas los eventos del taller? Son esos avisos, ahora entre programas.", p=1),
    L("Hubo un candidato serio: microkernel, un núcleo pequeño al que se le enchufan complementos. Es barato y simple."),
    L("Lo descartaron porque saca una sola estrella en escalabilidad y en tolerancia a fallos, dos de las siete del equipo.", p=1),
    L("Servicios grandes para ahorrar y probar. Eventos donde hay que conectar."),
   ],
   "audit": A([("Service-based", [0, 1, 2]), ("Event-driven", [3, 4]), ("Microkernel y su descarte", [5, 6]), ("Síntesis", [7])],
              "Sí: el estilo aparece después de los criterios que lo eligen", "Sí, los tres", "Sí: estrellas en las filas elegidas; el descarte con sus dos filas", "Sí: cada columna se resalta mientras se habla de ella", "Bien")},
  {"id": "historial", "kicker": "Lo que muestra git",
   "visual": "Línea de tiempo del repositorio. Las dos hojas caen en el 23/09. Más adelante: «requisitos 25/09», «experto 26–27/09», «entrega 30/09». Una línea continua marca que el estilo no cambia. El 15/10 aparece la sección «fortalecidas / debilitadas» del ADR-002 (testabilidad, costo, agilidad / elasticidad).",
   "lines": [
    L("Ahora, un detalle que solo se ve en el historial de git."),
    L("Las dos hojas tienen la misma fecha: 23 de septiembre. El primer día.", say="Las dos hojas tienen la misma fecha: veintitrés de septiembre. El primer día."),
    L("El estilo se eligió antes de escribir la lista de requisitos, y antes de hablar con un experto en IA. Y nunca cambió."),
    L("Lo que llegó tarde fue el porqué completo: lo que el estilo gana y lo que cede se escribió después de la entrega.", p=1),
    L("Por ejemplo, lo que cede: con la base compartida, el sistema crece peor cuando la carga sube de golpe."),
    L("Elegir el estilo temprano es una apuesta. Lo que la vuelve defendible es que el criterio quedó por escrito: tres características y una hoja que cualquiera puede revisar.", p=1),
   ],
   "audit": A([("El orden real (estilo antes que requisitos)", [1, 2]), ("El porqué escrito tarde; elasticidad cedida", [3, 4]), ("La regla: criterio por escrito", [5])],
              "Sí: las fechas antes de la conclusión", "Elasticidad, con su efecto, sin el nombre", "Sí", "Sí: la línea de tiempo queda toda la escena", "Bien")},
  {"id": "outro", "kicker": "Para llevarte",
   "visual": "Cuatro tarjetas: «cómo se comporta, no qué hace»; las tres casillas con sus desafíos; la hoja con el asterisco; service-based + eventos. Avance: un signo de pregunta sobre la palabra «LLM».",
   "lines": [
    L("Repasemos. Las características dicen cómo se comporta el sistema. Se eligen pocas, y con su porqué."),
    L("Pragmatic eligió factibilidad, interoperabilidad y testabilidad, por tres desafíos: dinero, sistemas ajenos e IA impredecible."),
    L("Cuando a la hoja le faltó factibilidad, la reemplazaron por costo y simplicidad, y lo anotaron."),
    L("Resultado: servicios grandes, y eventos donde hay que conectar.", p=1),
    L("Pero quedaba lo más incierto: nadie en el equipo sabía bien cuánto cuesta, ni cómo se comporta, un LLM. Capítulo 3: lo que no sabían."),
   ],
   "audit": A([("Repaso", [0, 1, 2, 3]), ("Avance", [4])], "—", "—", "—", "Sí", "Bien")},
 ],
}

CH3 = {
 "n": 3, "title": "Lo que no sabían",
 "ideas": [
  "Requisitos y supuestos numerados con códigos estables (R, Q, A; nunca renumerar) para que cada ADR se pueda rastrear hasta lo que lo sostiene. Y cuando falta un dato, se supone con fuente (A17).",
  "La contradicción escrita como «nota para después»: un proceso justo pide determinismo (A9), y la IA cambia con cada versión (A10). Debajo: «usar la menor IA posible».",
  "Lo que no sabían, lo preguntaron: la entrevista al experto como curso rápido de LLM (prompt, token, temperatura, rate limit, vida útil, conjuntos de prueba).",
  "Las respuestas se vuelven supuestos numerados y requisitos (A20–A28, Q14, Q15).",
 ],
 "anchors": [
  "`Requirements/requirements-and-assumptions.md`: primera versión `cad0b4f` (25/09 00:30) con «Open Questions» y «Notes for later»; A17 en `870a617`; A20–A31 y Q12–Q16 en `72923e5` (29/09).",
  "`Requirements/Research/interview-ai-expert.md`: preguntas `870a617` (25/09), pregunta extra `6af9574` (26/09), notas `4923a1c` (27/09), limpieza `a774a6b` (30/09).",
  "Referencia colgada: ADR-010 cita Q4, borrado en `c7a9e8e`.",
 ],
 "learn": [
  "Escribir requisitos y supuestos con identificadores estables y citarlos desde las decisiones.",
  "Suponer un número que falta, con su fuente, y dejarlo discutible.",
  "Explicar qué es un prompt, un token, la temperatura y un rate limit, y por qué importan en un diseño.",
 ],
 "cut": [
  "La lista completa de requisitos (pantalla, no voz).",
  "Las preguntas abiertas del primer borrador, salvo la nota de la contradicción.",
  "El precio por flat rate (PTU): las notas crudas y las limpias se contradicen (ver `HISTORIA.md` §6).",
  "Contexto frente a fine-tuning, OCR y modelos multimodales, privacidad de Azure: detalle para el curso escrito (privacidad vuelve en el capítulo 4).",
  "Prompt injection: el experto lo advierte, pero ningún ADR lo trata; se menciona en `HISTORIA.md` §7.",
 ],
 "questions": [
  "«¿Supuesto? ¿No es lo mismo que requisito?» Se definen juntos, en contraste, con el par A1 → R11.",
  "«¿Por qué no renumerar?» Se responde con la consecuencia: las citas apuntarían a otra cosa. Y se muestra que al equipo se le escapó una.",
  "«¿De dónde sale 25.000?» Se dice la fuente (Statista) y la cuota supuesta (10 %).",
  "«¿Token? ¿Prompt? ¿Temperatura? ¿Rate limit?» Cada uno con su línea, y con la cifra o consecuencia que lo hace importar.",
  "«¿Por qué Q15 importa?» Se ata al trato justo de A9: si a unos los midió un modelo y a otros otro, el trato no es el mismo.",
 ],
 "scenes": [
  {"id": "intro", "kicker": "Capítulo 3",
   "visual": "La línea de tiempo del capítulo 2 con el estilo fijado. A la derecha, un LLM como caja negra con signos de pregunta. Título.",
   "lines": [
    L("En el capítulo 2, el equipo eligió el estilo en un día. Pero tenía una deuda."),
    L("El pliego dejaba huecos, y nadie en el equipo sabía bien cómo se comporta un LLM.", p=0.6),
    L("Capítulo 3: lo que no sabían."),
   ],
   "audit": A([("Puente", [0, 1])], "—", "—", "—", "Sí", "Bien")},
  {"id": "lista", "kicker": "Requisitos y supuestos",
   "visual": "Un archivo que se abre a las 00:30 del 25/09. Tres columnas con color: R (qué hace), Q (cómo debe hacerlo), A (supuestos). Una flecha une A1 con R11. Arriba, la regla original resaltada: «When deleting, do not reorder or reassign numbers but just leave a gap». Un ADR con una cita «Q5» que apunta al renglón correcto; si se renumera, la flecha queda apuntando a otro. Al final, el ADR-010 con su cita a «Q4» y un renglón vacío.",
   "lines": [
    L("El miércoles 25, pasada la medianoche, apareció un archivo nuevo: requisitos y supuestos.", say="El miércoles veinticinco, pasada la medianoche, apareció un archivo nuevo: requisitos y supuestos."),
    L("Un requisito es algo que el sistema tiene que hacer o cumplir. Un supuesto es algo que el equipo da por cierto, sin que el cliente lo haya dicho."),
    L("Cada uno lleva un código: R para lo que el sistema hace, Q para cómo tiene que hacerlo, y A para los supuestos."),
    L("Por ejemplo, el supuesto A1: una empresa puede tener varios responsables de contratación, uno por área. De ahí sale el requisito R11: la empresa puede abrirles cuentas.", p=0.8),
    L("Arriba del archivo, una regla: si borras uno, no renumeres. Deja el hueco."),
    L("¿Por qué? Porque las decisiones van a citar esos códigos. Si los números se corren, las citas apuntan a otra cosa.", p=1),
    L("Así, cada decisión se puede seguir hasta el supuesto que la sostiene. Eso se llama trazabilidad."),
    L("Y aun así, se les escapó una: un ADR terminó citando un requisito que ya habían borrado.", p=1),
   ],
   "audit": A([("Requisito y supuesto", [1, 2, 3]), ("Códigos estables", [4, 5]), ("Trazabilidad", [6]), ("El error real", [7])],
              "Sí: el par A1 → R11 antes de la regla", "Sí", "Sí: la regla se justifica por sus citas", "Sí: cada flecha queda ~5 s", "Bien")},
  {"id": "numero", "kicker": "Un número propio",
   "visual": "El pliego con su hueco de «volumen: ?». Al lado, el supuesto A17 con la fuente Statista. Un embudo: 250.000 puestos por mes → 10 % → 25.000 puestos y unos 25.000 candidatos. El número queda en una tarjeta «guárdalo».",
   "lines": [
    L("El pliego no traía volúmenes, así que el equipo los supuso. Supuesto A17."),
    L("En Estados Unidos, en el sector de la información, se abren como máximo unos 250.000 puestos por mes, según Statista.", say="En Estados Unidos, en el sector de la información, se abren como máximo unos doscientos cincuenta mil puestos por mes, según Statista."),
    L("Si ClearView llegara al 10 % de ese mercado: 25.000 puestos por mes, y más o menos la misma cantidad de candidatos activos.", say="Si ClearView llegara al diez por ciento de ese mercado: veinticinco mil puestos por mes, y más o menos la misma cantidad de candidatos activos."),
    L("No es un dato del cliente. Es un supuesto con su fuente, que cualquiera puede discutir.", p=1),
    L("Guarda este número: en el capítulo 6 decide mucho."),
   ],
   "audit": A([("Suponer un número con fuente (A17)", [0, 1, 2, 3])],
              "Sí: el hueco del pliego del capítulo 1", "—", "Sí: sin volumen no se puede dimensionar nada", "Sí: el embudo queda armado", "Bien")},
  {"id": "nota", "kicker": "Una nota para después",
   "visual": "Al pie del archivo, la sección «Notes for later» con su texto original y la traducción. A9 y A10 aparecen como dos tarjetas que chocan: «trato justo = siempre igual» contra «la IA cambia con cada versión». En el centro, el producto: «IA para contratar con justicia». Después, la segunda nota en grande: «Use as little AI as necessary» / «usar la menor IA posible».",
   "lines": [
    L("Al pie del archivo, el equipo dejó una nota para después. Dice: «A9 y A10 muestran una contradicción. Podría ser la base de un buen argumento».", say="Al pie del archivo, el equipo dejó una nota para después. Dice: A nueve y A diez muestran una contradicción. Podría ser la base de un buen argumento."),
    L("A9: un proceso de contratación justo busca más determinismo, y menos arbitrariedad. Que la misma persona reciba siempre el mismo trato."),
    L("A10: los modelos de IA cambian. Cada versión nueva da resultados distintos."),
    L("Y el producto entero consiste en usar IA para que contratar sea más justo.", p=1.2),
    L("Debajo, una segunda nota, muy corta: usar la menor IA posible."),
    L("Quédate con esa frase. Es la semilla del capítulo 6.", p=1),
   ],
   "audit": A([("La contradicción A9/A10", [0, 1, 2, 3]), ("«Usar la menor IA posible»", [4, 5])],
              "Sí: las dos tarjetas antes de la conclusión", "Determinismo ya definido en el capítulo 2", "Sí: el producto promete justicia con una herramienta cambiante", "Sí: la nota original con traducción queda ~10 s", "Bien")},
  {"id": "experto", "kicker": "Preguntar",
   "visual": "Una libreta con las preguntas reales, que se escriben una por una (costo, previsibilidad del costo, determinismo, pruebas, vida útil). El 26/09 a la mañana se agrega la última, sobre las API. Después, la libreta se llena de respuestas (sin nombre del experto).",
   "lines": [
    L("Para salir de dudas, el equipo hizo algo poco común en un kata: preparó una entrevista con un experto en IA."),
    L("Escribió las preguntas antes: cuánto cuesta, si se puede predecir el costo, cuándo es determinista, cómo se prueba, y cuánto dura un modelo."),
    L("La mañana del jueves, agregó una más: ¿las API de los modelos responden al instante, o tardan?"),
    L("Las respuestas quedaron en el repositorio, resumidas. Son un curso rápido de LLM.", p=0.8),
   ],
   "audit": A([("Preguntar a un experto con preguntas preparadas", [0, 1, 2, 3])],
              "Sí: viene de la contradicción y de los huecos", "—", "Sí: lo que no sabes, lo preguntas", "Sí", "Bien")},
  {"id": "respuestas", "kicker": "Lo que respondió",
   "visual": "Cuatro tarjetas que entran de a una. 1) Costo: un prompt partido en tokens (pedazos de colores) que entran a un medidor; cifra «500.000 prompts ≈ 500.000 USD». 2) Temperatura: un dial que baja a 0, y aun así dos prompts casi iguales dan respuestas distintas. 3) Límites: un medidor de tokens por minuto que llega al tope y corta; un reloj de 60 s. 4) Vida útil: una línea de 1 a 2 años con el modelo retirado al final. Al pie, una pila «conjunto de pruebas».",
   "lines": [
    L("Primero, el costo. Lo que le envías al modelo se llama prompt."),
    L("Y se cobra por token: un pedazo de texto, más o menos una parte de una palabra. Pagas los tokens que envías, y los que vuelven."),
    L("El experto contó un proyecto con prompts largos: medio millón de prompts, medio millón de dólares.", p=1),
    L("Segundo, el determinismo. Hay un ajuste, la temperatura, que controla cuánto azar mete el modelo."),
    L("Puedes bajarla a cero. Aun así, cambiar el prompt, o cambiar de modelo, puede cambiar mucho el resultado."),
    L("El experto lo llamó comportamiento caótico: un cambio pequeño en la entrada, y un cambio grande en la salida.", p=1),
    L("Tercero, los límites. Cada servicio impone un rate limit: cuántos tokens por minuto acepta. Si lo pasas, te corta."),
    L("Para un sistema que procesa miles de currículums, ese corte no es un detalle: es un techo."),
    L("Y una respuesta puede tardar hasta 60 segundos.", say="Y una respuesta puede tardar hasta sesenta segundos.", p=0.8),
    L("Cuarto, la vida útil. Con tanta competencia, un modelo queda viejo en uno o dos años, y el proveedor lo retira.", p=0.8),
    L("Y para probar, hace falta un conjunto de pruebas grande, que se vuelve a correr cada vez que cambia el prompt o el modelo."),
   ],
   "audit": A([("Prompt y token", [0, 1, 2]), ("Temperatura (determinismo)", [3, 4, 5]), ("Rate limit y demora", [6, 7, 8]), ("Vida útil del modelo", [9]), ("Conjunto de pruebas (plantado para el capítulo 7)", [10])],
              "Sí: cada término llega como respuesta a una pregunta ya planteada", "Sí, todos", "Sí: cada uno con su consecuencia (costo, resultados que cambian, cortes, migraciones)", "Sí: una tarjeta por respuesta, ~15 s cada una", "Bien (vida útil recibe ~9 s: se trabaja de nuevo en el capítulo 4)")},
  {"id": "piensalo", "kicker": "Piénsalo tú",
   "visual": "Dos columnas de costo: «servidores de ClearView» y «la IA». Anillo de 3 s. Después la balanza cae del lado de la IA, con la frase de las notas crudas: «el costo operativo lo dominará la IA».",
   "lines": [
    L("Piénsalo tú. Con lo que dijo el experto, ¿qué va a costar más en ClearView: los servidores propios, o la IA?", p=3),
    L("La IA. El mismo experto lo dijo: el costo de operar lo va a dominar el LLM, y el resto será despreciable.", p=1),
   ],
   "audit": A([("Aplicar: dónde está el costo", [0, 1])],
              "Sí: después de token y medio millón de dólares", "—", "Sí, con la frase del experto", "Sí", "Bien")},
  {"id": "supuestos", "kicker": "De la charla a la lista",
   "visual": "Las tarjetas de la entrevista se convierten en renglones numerados A20…A28, que entran al archivo de requisitos. Se resaltan A25 y A26. Flechas hacia Q14 y Q15. Al final, una cadena: duda → pregunta → supuesto → requisito.",
   "lines": [
    L("Nada de esto quedó como anécdota. Se convirtió en nueve supuestos nuevos, numerados."),
    L("Por ejemplo, A25: contando pruebas, conocimiento y uso, los LLM son el mayor costo técnico de ClearView."),
    L("Y A26: a una ONG le cuesta conseguir fondos, sobre todo si el costo es difícil de estimar.", p=0.8),
    L("De esos supuestos salen requisitos. Q14: cambiar el prompt o el modelo no debe empeorar los matches."),
    L("Q15: si cambian, hay que volver a calcular los puntajes de todos los matches.", p=0.8),
    L("¿Por qué todos? Por A9: si a unos los midió un modelo y a otros otro, el trato ya no es el mismo.", p=1),
    L("La cadena completa: una duda, una pregunta al experto, un supuesto con número, y un requisito que lo cita."),
   ],
   "audit": A([("Supuestos A25 y A26", [0, 1, 2]), ("Q14 y Q15", [3, 4, 5]), ("La cadena de trazabilidad", [6])],
              "Sí: salen de la entrevista recién vista", "—", "Sí: Q15 atado al trato justo de A9", "Sí: cada renglón queda escrito", "Bien")},
  {"id": "outro", "kicker": "Para llevarte",
   "visual": "Cuatro tarjetas: R/Q/A con la regla del hueco; el embudo de 25.000; la nota de la contradicción; las cuatro respuestas del experto. Avance: una nube con «alquilar» y un servidor con «correr propio».",
   "lines": [
    L("Repasemos. Requisitos y supuestos numerados, sin renumerar, para que cada decisión se pueda rastrear."),
    L("Cuando falta un dato, se supone, con fuente: 25.000 puestos por mes.", say="Cuando falta un dato, se supone, con fuente: veinticinco mil puestos por mes."),
    L("La contradicción entre una IA cambiante y un trato justo quedó escrita, junto a una idea: usar la menor IA posible."),
    L("Y lo que no sabían, lo preguntaron: tokens, temperatura, límites, y modelos que envejecen.", p=1),
    L("Con eso, había que decidir dónde vive la IA: ¿la corren ellos, o la alquilan? Capítulo 4: alquilar la IA."),
   ],
   "audit": A([("Repaso", [0, 1, 2, 3]), ("Avance", [4])], "—", "—", "—", "Sí", "Bien")},
 ],
}

CH4 = {
 "n": 4, "title": "Alquilar la IA",
 "ideas": [
  "La primera idea fue correr los modelos en contenedores propios (ADR-006), con buenas razones: el modelo pesa y se usa poco, así que conviene que escale aparte.",
  "Tres caminos (ADR-007): LLM externo, open source en la nube, open source en servidores propios. Gana alquilar, por factibilidad. ADR-006 no se borra: queda «reemplazado por ADR-007».",
  "Medir antes de decidir: un prompt de prueba con tokens y precios con fecha. Una historia cuesta entre una décima de centavo y 2,5 centavos según el modelo (A24).",
  "El precio de alquilar: rate limit, modelos que se retiran, privacidad. Por eso todo cliente del LLM es asíncrono. Y la tesis: ahorrar en el resto para pagar la IA.",
 ],
 "anchors": [
  "`ADR/ADR-006-ai-models-run-on-separate-containers.md`: esqueleto *Accepted* en `4923a1c`; texto y estado *Superseded* en `72923e5`.",
  "`ADR/ADR-007-use-of-external-llms.md`: esqueleto «Flexibility toward AI models» en `4923a1c`; renombrado y escrito en `72923e5`.",
  "`Requirements/Research/token-estimation.md` (`72923e5`, 29/09; precios archivados el 29/09).",
  "C2 del 28/09 (`ab2291b`): leyenda «Service with external AI».",
  "`README.md`: *Known limitations* (rate limit, `d4c4fbb`) e introducción (`9891219`, 15/10).",
 ],
 "learn": [
  "Comparar alojar un modelo propio frente a alquilarlo, con pros y contras concretos.",
  "Estimar el costo de una llamada a un LLM con tokens de entrada, de salida y una tabla de precios.",
  "Usar el estado «reemplazado» de un ADR para registrar un cambio de opinión.",
 ],
 "cut": [
  "El detalle de PTU (tarifa plana) y su contradicción en las notas.",
  "Las características «fortalecidas y debilitadas» completas de ADR-006 y ADR-007 (pantalla).",
  "La contradicción de ADR-007 «el costo es más predecible» frente a A25/A26 (en `HISTORIA.md` §6; la voz sigue a la entrevista).",
  "La verificación propia de los precios por millón de tokens (en `HISTORIA.md` §6).",
 ],
 "questions": [
  "«¿Contenedor?» Se define al nombrarlo, con su ventaja (se enciende en cualquier servidor).",
  "«¿Por qué no correr el modelo propio, si es más privado?» Se dan sus pros reales antes del contra del experto.",
  "«¿Qué es «reemplazado»?» Se define: no se borra, queda enlazado al que lo sustituye.",
  "«¿850 tokens es mucho?» Se descompone: instrucciones más un currículum de ejemplo.",
  "«¿Por qué veinticinco veces?» Se dice que es la misma tarea con otro modelo, y se ata a A24.",
  "«¿Asíncrono?» Se usa sin definir formalmente; la definición completa llega en el capítulo 5. Aquí se explica por su efecto: nada se traba si el modelo tarda.",
 ],
 "scenes": [
  {"id": "intro", "kicker": "Capítulo 4",
   "visual": "La balanza del capítulo 3 inclinada hacia la IA. Una pregunta: «¿dónde corre?». Título.",
   "lines": [
    L("¿Recuerdas al experto del capítulo 3? Dijo que la IA iba a ser el mayor costo del sistema."),
    L("Ahora tocaba decidir dónde corre.", p=0.6),
    L("Capítulo 4: alquilar la IA."),
   ],
   "audit": A([("Puente", [0, 1])], "—", "—", "—", "Sí", "Bien")},
  {"id": "primera", "kicker": "La primera idea",
   "visual": "El ADR-006 en su esqueleto del 26/09 (una línea, estado «Accepted»). Diagrama: servicio de candidatos y de empleadores (livianos) y, aparte, un contenedor grande «modelo de IA» con un chip. Cuando el tráfico sube, el servicio de candidatos se duplica, y el modelo no. Al final, un signo de pregunta adentro del contenedor del modelo.",
   "lines": [
    L("En la sesión de diseño del jueves 26, el equipo anotó una primera decisión: los modelos de IA corren en sus propios contenedores.", say="En la sesión de diseño del jueves veintiséis, el equipo anotó una primera decisión: los modelos de IA corren en sus propios contenedores."),
    L("Un contenedor es un paquete con un programa y todo lo que necesita para correr. Se enciende y se apaga en cualquier servidor."),
    L("La razón era buena. Un modelo pide mucha memoria, y a veces hardware especial. Y se usa en pocas funciones."),
    L("Si el servicio de candidatos se duplica por tráfico, no tiene sentido duplicar también el modelo. Separados, cada uno crece a su ritmo.", p=1),
    L("Pero esa decisión traía otra pregunta, escondida: ¿qué modelo corre ahí adentro? ¿Uno propio?"),
   ],
   "audit": A([("Contenedor", [1]), ("Separar el modelo (ADR-006) y su porqué", [0, 2, 3]), ("La pregunta escondida", [4])],
              "Sí: el problema de escalar juntos antes de la solución", "Sí", "Sí: memoria, hardware y uso desigual", "Sí", "Bien")},
  {"id": "tres", "kicker": "Tres caminos",
   "visual": "Tres columnas que se arman de a una, con iconos: A) una nube con logos genéricos de proveedor y una flecha de API; B) una nube con un contenedor propio y un modelo open source; C) un edificio con servidores, un enchufe y personas. Debajo de cada una, sus pros en verde y contras en rojo, con las palabras exactas de la voz.",
   "lines": [
    L("El ADR 007 pone tres caminos sobre la mesa, con sus pros y sus contras."),
    L("A: alquilar un LLM externo, de Azure, Google u OpenAI. Se usa por una API: envías el prompt, y te devuelve la respuesta."),
    L("A favor: casi no hay que desarrollar nada, se sale rápido, y siempre tienes el modelo más nuevo."),
    L("En contra: es caro, tiene límites de uso, los modelos se retiran pronto, y el texto del candidato viaja a otra empresa.", p=1),
    L("B: un modelo de código abierto, como los de Meta o Mistral, en contenedores propios en la nube."),
    L("Da más control, y más privacidad. Pero según el experto no sale más barato, y exige gente que sepa operarlo.", p=1),
    L("C: ese mismo modelo, en servidores propios. Control total."),
    L("Pero hay que comprar hardware especial, contratar personal y pagar la electricidad, y eso demora el proyecto.", p=1),
   ],
   "audit": A([("A: LLM externo", [1, 2, 3]), ("B: open source en la nube", [4, 5]), ("C: on-prem", [6, 7])],
              "Sí: la pregunta escondida de la escena anterior", "Sí: cada opción por lo que es", "Sí: pros y contras del ADR, con el dato del experto", "Sí: la tabla queda armada al final", "Bien")},
  {"id": "piensalo", "kicker": "Piénsalo tú",
   "visual": "Las tres columnas en pantalla. Arriba, las tres casillas del top 3, con factibilidad resaltada, y una alcancía de donaciones. Anillo de 3 s.",
   "lines": [
    L("Piénsalo tú. Recuerda el top 3: factibilidad primero, para una ONG que vive de donaciones. ¿A, B o C?", p=3),
   ],
   "audit": A([("Aplicar el top 3 a una decisión", [0])],
              "Sí: después de las tres opciones y del top 3", "—", "—", "Sí: la tabla sigue visible", "Bien")},
  {"id": "decision", "kicker": "La decisión",
   "visual": "La columna A se ilumina. Tres razones aparecen debajo. Después, el ADR-006 cambia su estado: «Accepted» se tacha y aparece «Superseded by ADR-007» con una flecha hacia el ADR-007. El C2 del 28/09 con su leyenda «Service with external AI» se ilumina.",
   "lines": [
    L("El equipo eligió A: alquilar."),
    L("Por factibilidad: sin hardware, sin especialistas propios, y con el modelo más nuevo desde el primer día."),
    L("Y porque los precios tienden a bajar: alquilando, esa baja llega sola.", p=1),
    L("Con esto, el ADR 006 cambió de estado: reemplazado por el ADR 007."),
    L("No se borró. Quedó marcado como reemplazado, con un enlace a la decisión que lo sustituye.", p=0.8),
    L("Así, quien lea el repositorio ve también el camino que no se tomó, y por qué.", p=1),
    L("Un registro de decisiones guarda también las que cambian."),
   ],
   "audit": A([("La elección y su porqué", [0, 1, 2]), ("Estado «reemplazado»", [3, 4, 5]), ("Síntesis", [6])],
              "Sí", "Sí: reemplazado", "Sí: factibilidad y tendencia de precios (ADR-007)", "Sí: el cambio de estado se anima y queda", "Bien")},
  {"id": "precio", "kicker": "Cuánto cuesta una historia",
   "visual": "El prompt de prueba real, traducido, con la lista de factores a eliminar resaltada. Un contador de tokens: 850 de entrada (instrucciones + un currículum de ejemplo), 1.400 de salida. La página de precios con fecha 29/09. Dos monedas: GPT-4o ≈ 0,025 USD; GPT-4o mini ≈ 0,001 USD. Una barra 25 veces más larga que la otra. Al final, el renglón A24.",
   "lines": [
    L("Alquilar tiene una consecuencia: se paga por uso. Entonces, ¿cuánto cuesta crear una historia?"),
    L("El equipo no se quedó con la duda. Escribió un prompt de prueba: transforma este currículum en una historia, y elimina la raza, el sexo, el género, la orientación sexual, la salud y el atractivo."),
    L("Con el texto de un currículum de ejemplo, unos 850 tokens de entrada.", say="Con el texto de un currículum de ejemplo, unos ochocientos cincuenta tokens de entrada."),
    L("Para una historia de unas 400 palabras, supusieron unos 1.400 tokens de salida.", say="Para una historia de unas cuatrocientas palabras, supusieron unos mil cuatrocientos tokens de salida.", p=0.8),
    L("Y consultaron la página de precios de OpenAI ese mismo domingo."),
    L("Con el modelo más nuevo, GPT-4o, unos dos centavos y medio de dólar por historia. Con el más barato, GPT-4o mini, una décima de centavo.", say="Con el modelo más nuevo, G-P-T cuatro o, unos dos centavos y medio de dólar por historia. Con el más barato, G-P-T cuatro o mini, una décima de centavo."),
    L("La misma tarea, veinticinco veces más cara según el modelo.", p=1.5),
    L("De ahí salió el supuesto A24: el costo varía muchísimo con el tamaño del prompt y con el modelo elegido."),
    L("Fíjate en el método: no adivinaron. Midieron un caso concreto, con fuente y con fecha.", p=1),
   ],
   "audit": A([("El prompt de prueba", [0, 1]), ("Tokens de entrada y salida", [2, 3]), ("Precio por modelo (25 veces)", [4, 5, 6]), ("A24 y el método", [7, 8])],
              "Sí: la pregunta concreta antes de la cuenta", "Tokens ya definidos en el capítulo 3", "Sí: medir para estimar un costo incierto", "Sí: la barra de 25× queda ~5 s con pausa", "Bien")},
  {"id": "costo", "kicker": "El precio de alquilar",
   "visual": "Tres iconos de costo que se encienden: un semáforo (rate limit) con la etiqueta «limitación conocida»; un modelo con fecha de retiro; un sobre que sale hacia otra empresa (privacidad). Después, un servicio que deja un mensaje en un buzón hacia el LLM y sigue trabajando; el LLM tarda, y nada se traba. Al final, la frase de la introducción del README con su fecha (15/10).",
   "lines": [
    L("Alquilar resuelve mucho, pero el equipo anotó lo que paga."),
    L("Los límites de uso: si se pasan, el servicio corta. Eso quedó como una limitación conocida, sin resolver."),
    L("Los modelos que se retiran: cada cambio obliga a probar todo de nuevo. Y la privacidad: el texto viaja a otra empresa, y hay que revisar las reglas.", p=1),
    L("Por eso, cada parte del sistema que le habla a un LLM lo hace con mensajes, sin quedarse esperando la respuesta."),
    L("Si el modelo tarda un minuto, o corta, nada se traba.", p=1),
    L("Y después de la entrega, el equipo escribió la idea que ordena todo lo demás: ahorrar a propósito en el resto del sistema, para poder pagar una IA de precio impredecible."),
    L("Cómo lo hicieron, lo verás en el capítulo 8."),
   ],
   "audit": A([("Los costos de alquilar", [0, 1, 2]), ("Clientes del LLM por mensajes", [3, 4]), ("La tesis de ahorro (plantada)", [5, 6])],
              "Sí: los contras de la opción A vuelven como costos", "Mensajes ya vistos como eventos en el capítulo 2", "Sí", "Sí", "Bien (la asincronía se formaliza en el capítulo 5)")},
  {"id": "outro", "kicker": "Para llevarte",
   "visual": "Cuatro tarjetas: el contenedor separado (con «reemplazado»); las tres columnas con A marcada; la barra de 25×; la frase de ahorro. Avance: muchas puertas de colores distintos.",
   "lines": [
    L("Repasemos. La primera idea fue correr los modelos en contenedores propios. Tenía razones, y quedó registrada."),
    L("Comparados tres caminos, ganó alquilar: factibilidad para una ONG."),
    L("El ADR viejo no se borró: quedó como reemplazado."),
    L("Y midieron cuánto cuesta una historia: de una décima de centavo a dos centavos y medio, según el modelo.", p=1),
    L("Antes de escribir todo esto, el equipo ya había dibujado en detalle otra parte del sistema: la que conecta con miles de sistemas ajenos. Capítulo 5: miles de puertas."),
   ],
   "audit": A([("Repaso", [0, 1, 2, 3]), ("Avance", [4])], "—", "—", "—", "Sí", "Bien")},
 ],
}
