// Renders the Lucide icons this chapter uses into assets/icons.js (window.ICONS), so the video needs no network.
//
//   node tools/icons.mjs
//
// It scans compositions/*.html for icon names: data-icon="x", IC.x, IC['x'] and any quoted word that names an icon
// (so arrays like ['fridge', 'Texto'] are covered). A name resolves through ALIAS, or as the PascalCase Lucide name
// (heartPulse → HeartPulse). Unknown words are skipped; kit.js throws at runtime if a scene asks for a missing icon.
// Needs react, react-dom and lucide-react: they resolve from the worktree's node_modules.
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import * as L from 'lucide-react';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';

const ALIAS = {
  chef: 'ChefHat', fridge: 'Refrigerator', phone: 'Smartphone', card: 'CreditCard', heart: 'HeartPulse', doc: 'ScrollText',
  db: 'Database', check: 'Check', file: 'FileText', help: 'CircleHelp', calendar: 'CalendarDays', pin: 'MapPin', alert: 'TriangleAlert',
  hospital: 'Hospital', bed: 'BedDouble', pulse: 'HeartPulse', pressure: 'Gauge', oxygen: 'Wind', sugar: 'Droplet', lungs: 'Wind',
  ecg: 'Activity', temp: 'Thermometer', sleep: 'Moon', sun: 'Sun', bell: 'BellRing', monitor: 'Monitor', cloud: 'Cloud', cloudOff: 'CloudOff',
  wifiOff: 'WifiOff', server: 'Server', rack: 'Server', users: 'Users', user: 'User', nurse: 'UserRound', camera: 'Camera', trash: 'Trash2',
  sticky: 'StickyNote', git: 'GitCommitHorizontal', branch: 'GitBranch', link: 'Link', lock: 'Lock', shield: 'ShieldCheck', clock: 'Clock',
  timer: 'Timer', search: 'Search', filter: 'Filter', upload: 'Upload', x: 'X', arrowRight: 'ArrowRight', arrowDown: 'ArrowDown', pause: 'Pause',
  sliders: 'SlidersHorizontal', star: 'Star', table: 'Table2', boxes: 'Boxes', box: 'Box', layers: 'Layers', radio: 'Radio', mail: 'Mail',
  scale: 'Scale', gauge: 'Gauge', target: 'Target', flag: 'Flag', key: 'KeyRound', cpu: 'Cpu', memory: 'MemoryStick', plug: 'Plug',
  rotate: 'RotateCw', gavel: 'Gavel', trophy: 'Trophy', book: 'BookOpen', listChecks: 'ListChecks', pencil: 'PenLine', eye: 'Eye', eyeOff: 'EyeOff',
  sparkles: 'Sparkles', calc: 'Calculator', receipt: 'Receipt', network: 'Network', zap: 'Zap', volume: 'Volume1', volumeOff: 'VolumeX',
  ruler: 'Ruler', hourglass: 'Hourglass', cart: 'ShoppingCart', question: 'CircleHelp', thumbsDown: 'ThumbsDown', stamp: 'Stamp',
};
const dir = new URL('../compositions/', import.meta.url);
const src = readdirSync(dir).filter((f) => f.endsWith('.html')).map((f) => readFileSync(new URL(f, dir), 'utf8')).join('\n');
const names = new Set(['pause', 'doc', 'calendar']); // the kit's own (question ring, ADR card, stamp)
for (const m of src.matchAll(/data-icon="([A-Za-z0-9]+)"|IC\.([A-Za-z0-9]+)|IC\[['"]([A-Za-z0-9]+)['"]\]|['"]([a-z][A-Za-z0-9]*)['"]/g)) names.add(m[1] ?? m[2] ?? m[3] ?? m[4]);
const lucide = (k) => ALIAS[k] ?? k[0].toUpperCase() + k.slice(1);
const out = {};
for (const k of [...names].sort()) {
  const n = lucide(k);
  const C = L[n];
  if (!C || /^[a-z]/.test(n) || ['Icon', 'LucideProvider', 'Lucide'].includes(n)) continue;
  out[k] = renderToStaticMarkup(createElement(C, { size: 24, strokeWidth: 1.75, color: 'currentColor' })).replace(/ class="[^"]*"/, '');
}
writeFileSync(new URL('../assets/icons.js', import.meta.url), '/* generated by tools/icons.mjs (Lucide, ISC) */\nwindow.ICONS = ' + JSON.stringify(out) + ';\n');
console.log(Object.keys(out).length, 'icons');
