// One-off: renders the Lucide icons the video uses into assets/icons.js (window.ICONS), so the composition needs no network.
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import * as L from 'lucide-react';
import { writeFileSync } from 'node:fs';
const names = {
  chef: 'ChefHat', fridge: 'Refrigerator', store: 'Store', user: 'User', userCheck: 'UserCheck', calendar: 'CalendarCheck',
  phone: 'Smartphone', server: 'Server', card: 'CreditCard', books: 'BookOpenCheck', truck: 'Truck', cpu: 'Cpu',
  packageX: 'PackageX', pin: 'MapPin', heart: 'HeartPulse', cash: 'Banknote', radio: 'Radio', lock: 'Lock',
  doc: 'ScrollText', trophy: 'Trophy', x: 'X', users: 'Users', clock: 'Clock', building: 'Building2', utensils: 'UtensilsCrossed',
  receipt: 'Receipt', book: 'BookOpen', inbox: 'Inbox', heart2: 'Heart', chart: 'BarChart3', db: 'Database', container: 'Container', check: 'Check', gavel: 'Gavel', network: 'Network', scale: 'Scale', ruler: 'Ruler', file: 'FileText', square: 'Square', sparkles: 'Sparkles', coins: 'Coins', hammer: 'Hammer', listChecks: 'ListChecks', flag: 'Flag', help: 'CircleHelp', brain: 'Brain', activity: 'Activity', mail: 'Mail', boxes: 'Boxes', box: 'Box', target: 'Target', calendarDays: 'CalendarDays', glossary: 'BookA', shieldAlert: 'ShieldAlert', notebook: 'NotebookPen', key: 'KeyRound', arrowRight: 'ArrowRight', pencil: 'PenLine', search: 'Search', thumbsDown: 'ThumbsDown', eyeOff: 'EyeOff', pause: 'Pause', apple: 'Apple', wheat: 'Wheat', stethoscope: 'Stethoscope', terminal: 'MonitorSmartphone', cloudRain: 'CloudRain', gauge: 'Gauge', map: 'Map', wifiOff: 'WifiOff', message: 'MessageSquare', rotate: 'RotateCw', camera: 'Camera', compass: 'Compass', git: 'GitBranch', swords: 'Swords', route: 'Route', alert: 'TriangleAlert',
};
const out = {};
for (const [k, n] of Object.entries(names)) {
  if (!L[n]) throw new Error('missing icon ' + n);
  out[k] = renderToStaticMarkup(createElement(L[n], { size: 24, strokeWidth: 1.75, color: 'currentColor' })).replace(/ class="[^"]*"/, '');
}
writeFileSync(new URL('../assets/icons.js', import.meta.url), '/* generated by tools/icons.mjs (Lucide, ISC) */\nwindow.ICONS = ' + JSON.stringify(out, null, 0) + ';\n');
console.log(Object.keys(out).length, 'icons');
