/**
 * The video edition's editorial layer: each chapter's phase, one-line description and the ideas its
 * closing recap leaves (taken from the recap scene of each narration). Timings, sections and the
 * transcript come from chapters.json, generated by scripts/build-video-data.mjs.
 */
import data from './chapters.json';

export interface VideoSection { title: string; start: number }
export interface VideoLine { start: number; end: number; text: string }
export interface VideoChapter {
  id: string;
  number: number;
  title: string;
  duration: number;
  video: string;
  poster: string;
  sections: VideoSection[];
  transcript: VideoLine[];
  phase: string;
  blurb: string;
  ideas: string[];
}

/** Where the MP4s live (Cloudflare R2). Override with PUBLIC_VIDEO_BASE, e.g. a custom domain. */
export const VIDEO_BASE = (import.meta.env.PUBLIC_VIDEO_BASE ?? 'https://pub-6f7b6eb91057473ca260f6f34d89ad81.r2.dev').replace(/\/$/, '');
/** The written course, on its own subdomain. */
export const TEXT_SITE = (import.meta.env.PUBLIC_TEXT_SITE ?? 'https://texto.katarch.workers.dev').replace(/\/$/, '');

const META: Record<string, { phase: string; blurb: string; ideas: string[] }> = {
  terreno: {
    phase: 'El problema',
    blurb: 'El negocio, sus piezas físicas, lo que ya existía y el número que gobierna todo el caso.',
    ideas: ['Primero el negocio: cada forma de vender y de pagar es un problema distinto.', 'Separa lo que recibes de lo que construyes: el diagrama de contexto lo dibuja.', 'Haz la cuenta: menos de una petición por segundo.'],
  },
  podio: {
    phase: 'El problema',
    blurb: 'Tres finalistas, tres respuestas opuestas a la misma pregunta económica, y la vara del jurado.',
    ideas: ['La pregunta de fondo es económica: cuánta maquinaria pagar hoy, en un negocio nuevo.', 'Ninguna postura es la correcta: todo es un trade-off.', 'El jurado midió trazabilidad, del negocio hasta el costo de cada decisión.'],
  },
  principios: {
    phase: 'El marco de decisión',
    blurb: 'Leer el negocio, preguntar, fijar principios y anotar cada decisión antes de dibujar.',
    ideas: ['Lee el negocio antes de dibujar, y pregunta lo que no esté claro.', 'Los principios salen de las restricciones y desempatan las discusiones.', 'Cada decisión va a un ADR, con lo que se gana y lo que se paga.'],
  },
  estilo: {
    phase: 'El marco de decisión',
    blurb: 'Una sola pieza o muchas: la trampa de las entidades, la cuenta y el monolito modular.',
    ideas: ['No cortes por sustantivos: corta por lo que hacen los actores.', 'La tabla de estilos no decide sola: el contexto le da peso a cada fila.', 'Un monolito modular es barato hoy y deja extraer módulos cuando la telemetría lo pida.'],
  },
  dominio: {
    phase: 'El diseño',
    blurb: 'Qué se construye y qué se alquila, y cómo se protege lo que diferencia al negocio.',
    ideas: ['Dos preguntas clasifican cada capacidad: ¿diferencia al negocio? ¿ya existe?', 'El core se construye, el soporte se adapta, lo genérico se alquila.', 'Una capa anticorrupción protege el core de los formatos ajenos.'],
  },
  concurrencia: {
    phase: 'El diseño',
    blurb: 'El último plato, el dinero y la falta de señal: el software limpio choca con la realidad.',
    ideas: ['Un actor por refrigerador evita los locks.', 'El dinero exige guardar cada hecho y un cobro que no se pierda ni se duplique.', 'Lo que va a fallar se prepara antes.'],
  },
  suscriptor: {
    phase: 'El diseño',
    blurb: 'Del calendario al refrigerador: la agenda del suscriptor, comandos, eventos y reembolsos.',
    ideas: ['El futuro se guarda como una agenda que genera las órdenes del día.', 'El viaje es una cadena de comandos, que piden, y eventos, que anuncian.', 'Nada se anuncia antes de que pase.'],
  },
  infraestructura: {
    phase: 'El diseño',
    blurb: 'La red privada, la identidad en la puerta, la confianza cero y cuándo crecer.',
    ideas: ['Lo que no necesita internet no tiene camino a internet.', 'La identidad se valida una vez, en la puerta, y adentro cada módulo igual pide credenciales.', 'Crecer cuando los números lo pidan: primero más grande, después más copias.'],
  },
  costos: {
    phase: 'La realidad económica',
    blurb: 'Volumetría, costos fijos y variables, y comprar o construir: la factura de un año.',
    ideas: ['Mide bytes y frecuencias antes de elegir servidores.', 'Separa los costos fijos de los variables.', 'El costo real incluye a quién lo mantiene.'],
  },
  mapa: {
    phase: 'La realidad económica',
    blurb: 'Las diez decisiones del caso, en tres pilares, y los hilos que las atan.',
    ideas: ['Cada decisión se lee como problema, decisión y renuncia.', 'Las diez se ordenan en tres pilares: la forma, el mundo real y el dinero.', 'Ninguna decisión está sola: cada renuncia la paga la siguiente.'],
  },
  guia: {
    phase: 'Para llevar',
    blurb: 'El método en cuatro pasos, con la pregunta que te llevas para tu próximo sistema.',
    ideas: ['¿Qué volumen tiene el sistema real?', '¿Qué criterios desempatan, y qué va a fallar?', '¿Cuánto cuesta por año, contando a las personas?'],
  },
};

export const VIDEO_CHAPTERS: VideoChapter[] = (data as Omit<VideoChapter, 'phase' | 'blurb' | 'ideas'>[]).map((c) => ({ ...c, ...META[c.id] }));
export const videoUrl = (c: VideoChapter) => `${VIDEO_BASE}/${c.video}`;
export const chapterPath = (id: string) => `/${id}/`;
export const TOTAL_SECONDS = VIDEO_CHAPTERS.reduce((a, c) => a + c.duration, 0);
export const fmt = (s: number) => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, '0')}`;
export const PHASES = [...new Set(VIDEO_CHAPTERS.map((c) => c.phase))];
